### ISSUE TITLE
Could not load assembly 'Validation, Version=2.2.0.0' 

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-iot-sdks#851] opened 2016-10-01 05:58 UTC
I am trying to run some integration test on visual studio that test sending data to IoT Hub. When trying to send data using the `DeviceClient.SendEventAsync()` method, the application crashes with the following exception:

``` 
{"Could not load file or assembly 'Validation, Version=2.2.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7' or one of its dependencies. 
The system cannot find the file specified.":"Validation, Version=2.2.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7"} 
```

I have also noticed the following in the `app.config` file:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Validation" publicKeyToken="2fc06f0d701809a7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

I am using version 10.0.20 of the C# SDK
My project is targeting .NET 4.5.1
The Validation package installed is version 2.2.8

Can anyone provide some pointers about what is going wrong in the use of the SDK?

**Comment by sergaz-msft** [comment] 2016-10-03 14:22
Hi @murdockcrc I will have a look at this. Can you be more specific on the Validation package you are using (nuget link) and if you are following any specific sample? I want to reproduce your issue on my side as a first step. Thanks!

**Comment by rajeevmv** [comment] 2016-10-03 16:09
Everything appears to be correct. The version 1.0.20 works for me with the package "Validation - 2.2.8".
Can you verify that the location reference for the "Validation" package in your project file matches its actual location? The project file should have an entry like this:

    "<Reference Include="Validation, Version=2.2.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7, processorArchitecture=MSIL">
      <HintPath>..\packages\Validation.2.2.8\lib\dotnet\Validation.dll</HintPath>
      <Private>True</Private>
    </Reference>"

The actual "Validation.dll" file will also be copied into your runtime folder - something like /bin/Debug. Can you also verify that the file version there is 2.2.8 with the above key - 2fc06f0d701809a7?

**Comment by rajeevmv** [comment] 2016-10-04 15:45
Customer has verified that it was an issue with his environment.

Closing this issue.

**Closed by rajeevmv** 2016-10-04 15:45 UTC
Labels: CSS, investigation-required

**Comment by NickDarvey** [comment] 2016-11-30 00:58
@murdockcrc could you please share your solution? We are having the same issue (and the same scenario)

**Comment by sergaz-msft** [comment] 2016-11-30 09:40
Hi @NickDarvey can you clone the SDK again and test it? The solution for @murdockcrc  was to clone it again. You can clone it like that:

git clone --recursive https://github.com/Azure/azure-iot-sdks.git

Also have a look at what @rajeevmv says:

"The actual "Validation.dll" file will also be copied into your runtime folder - something like /bin/Debug. Can you also verify that the file version there is 2.2.8 with the above key - 2fc06f0d701809a7?"

**Comment by NickDarvey** [comment] 2016-11-30 22:01
@sergaz-msft we're actually using via NuGet package `Microsoft.Azure.Devices.Client` (the latest version, 1.0.22).

The Validation library file isn't copied to the runtime folder, but copying it manually works. Any pointers on how where to look for issues?

Two more specifics of our scenario:
* We're using the client library in a class library and referencing that class library from a test project.
* x64 platform configuration

**Comment by BertKleewein** [comment] 2016-11-30 23:59
@NickDarvey - I've been seeing this error lately and I have a theory.  I'm testing it out right now and I don't want to shout Eureka until I've done some more verification.  Can you tell me where your test project came from?  Did you create it manually and add the nuget packages, or did you copy one of the sample apps from the repo?

**Comment by BertKleewein** [comment] 2016-12-01 00:04
Without explaining too much (because I'm not sure I completely understand what's happening yet), I think you may be able to get around this by manually adding a nuget reference in your project to PCLCrypto.1.0.86.  If this doesn't work, you can also try adding Validation.2.2.8 to the project.  I'm not clear why we have to add these dependencies at all, but they're scattered around the code with various versions and I'm trying to untangle them.

**Comment by NickDarvey** [comment] 2016-12-01 00:55
@BertKleewein Thanks! I'll give that a try in a moment.
RE: Test project---it's manually created using the Unit Test project template in VS. The class library was using the Class Library template in VS. Test project is referencing the class library project

**Comment by NickDarvey** [comment] 2016-12-01 00:58
@BertKleewein Success! Adding PCLCrypto 1.0.86 works. Thank you (and good luck with the dependency clean-up >_<)

**Comment by NickDarvey** [comment] 2016-12-01 01:04
@BertKleewein Success! Installing Validation 2.2.4 into the test project (not the class library) works.
