### ISSUE TITLE
System.NullReferenceException using Microsoft.Azure.Devices.Client 1.0.19 / 1.0.20

### ISSUE THREAD

**Issue by zetanet** [Azure/azure-iot-sdks#842] opened 2016-09-26 06:50 UTC
Hello ,

I'm developing an application that runs on backgroud UWP Rasp Pi2 (Windows 10 IoT Core 10.0.14393.187) .This uses the Azure client libraries to implement messaging and D2C C2D with Azure IoT Hub

After you update the client libraries to the latest versions available with NuGet the application crash after a few minutes when connected to IoT Hub.

Exception thrown: 'System.NullReferenceException' in Microsoft.Azure.Amqp.Uwp.dll

System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.ni.dll
Additional information: Object reference not set to an instance of an object.

This is the code to create the client ..

`Dim logicaldeviceid As UInteger = 0
Dim MyDevice As TpmDevice = New TpmDevice (logicaldeviceid) As String Dim hubUri myDevice.GetHostName = ()
Dim deviceId As String = myDevice.GetDeviceId ()
Dim sasToken As String = myDevice.GetSASToken ()

DeviceClient = DeviceClient.Create (hubUri,AuthenticationMethodFactory.CreateAuthenticationWithToken (deviceId, sasToken), TransportType.Amqp)`

A timer then checks every x seconds if there are messages from the Hub Iot

`Private Function ReceiveMessage Async () As Task (Of String)

```
        Dim messageData As String = String.Empty
        Try


            As Object Dim receivedMessage = Await deviceClient.ReceiveAsync ()

            If Not receivedMessage Is Nothing Then

                messageData = Encoding.ASCII.GetString (receivedMessage.GetBytes ())

                deviceClient.CompleteAsync (receivedMessage)


            end If

        Catch ex As Exception
            Debug.WriteLine ( "ReceiveMessage Exception:" + ex.Message)
            ETWTracing.LogEvent (ex.Message.ToString, Windows.Foundation.Diagnostics.LoggingLevel.Error)
        end Try

        Return messageData

    end Function`
```

 I also tried changing the type of client creation ..

`DeviceClient = DeviceClient.CreateFromConnectionString (iotHubConnectionString, "ZetaHouseIoTDevice" TransportType.Amqp)`

or

`DeviceClient = DeviceClient.Create (iotHubUri, New DeviceAuthenticationWithRegistrySymmetricKey ( "ZetaHouseIoTDevice" deviceKey), TransportType.Amqp)
`

but the error Runtime persists ..

Has anyone encountered the same type of problem?

Thank you.

**Comment by arturl** [comment] 2016-09-26 21:01
Thanks @zetanet, @tameraw, I'm taking a look.

**Comment by zetanet** [comment] 2016-10-03 13:36
Hello ,
I checked the verbose log of MSBUILD compiling and noticed some warning .. these may be the cause of error? ...


There was a conflict between "Windows.Foundation.FoundationContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" and "Windows.Foundation.FoundationContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
      "Windows.Foundation.FoundationContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" was chosen because it had a higher version.
      References which depend on "Windows.Foundation.FoundationContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" [].
          C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Amqp\1.1.5\lib\uap10.0\Microsoft.Azure.Amqp.Uwp.dll
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Amqp\1.1.5\lib\uap10.0\Microsoft.Azure.Amqp.Uwp.dll".
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Amqp\1.1.5\lib\uap10.0\Microsoft.Azure.Amqp.Uwp.dll
      References which depend on "Windows.Foundation.FoundationContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" [].
          C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd".
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd






  There was a conflict between "Windows.Foundation.UniversalApiContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" and "Windows.Foundation.UniversalApiContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
      "Windows.Foundation.UniversalApiContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" was chosen because it had a higher version.
      References which depend on "Windows.Foundation.UniversalApiContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" [].
          C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Amqp\1.1.5\lib\uap10.0\Microsoft.Azure.Amqp.Uwp.dll
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Amqp\1.1.5\lib\uap10.0\Microsoft.Azure.Amqp.Uwp.dll".
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Amqp\1.1.5\lib\uap10.0\Microsoft.Azure.Amqp.Uwp.dll
      References which depend on "Windows.Foundation.UniversalApiContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" [].
          C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd".
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd






 There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
      "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
      References which depend on "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll].
          C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll".
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
              C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll
          C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd".
              C:\Users\tiziano\.nuget\packages\Microsoft.Azure.Devices.Client\1.0.19\lib\uap10.0\Microsoft.Azure.Devices.Client.winmd
      References which depend on "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
          C:\Users\tiziano\.nuget\packages\Microsoft.Net.Http\2.2.22\lib\win8\System.Net.Http.Extensions.dll
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Net.Http\2.2.22\lib\win8\System.Net.Http.Extensions.dll".
              C:\Users\tiziano\.nuget\packages\Microsoft.Net.Http\2.2.22\lib\win8\System.Net.Http.Extensions.dll






 There was a conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
      "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
      References which depend on "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\System.Core.dll].
          C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\System.Core.dll
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\System.Core.dll".
              C:\Users\tiziano\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\System.Core.dll
      References which depend on "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
          C:\Users\tiziano\.nuget\packages\Microsoft.Net.Http\2.2.22\lib\win8\System.Net.Http.Extensions.dll
            Project file item includes which caused reference "C:\Users\tiziano\.nuget\packages\Microsoft.Net.Http\2.2.22\lib\win8\System.Net.Http.Extensions.dll".
              C:\Users\tiziano\.nuget\packages\Microsoft.Net.Http\2.2.22\lib\win8\System.Net.Http.Extensions.dll


Thanks for collaboration...

**Comment by zetanet** [comment] 2016-10-03 13:56
Full compilation log..

[Conflict.txt](https://github.com/Azure/azure-iot-sdks/files/506370/Conflict.txt)

**Comment by arturl** [comment] 2016-10-03 17:30
Hi @zetanet,

I just submitted a fix for this bug, which looks like this: https://github.com/Azure/azure-iot-sdks/commit/da20d49f295dde600cdfb8e92a9dda8740e1205f.
Both Azure.Devices.Client and AMQP library were broken in the same way. The fix above is for Azure.Devices.Client. The fix for AMQP is going to be the same -- making its way through our checkin system now.

**Comment by zetanet** [comment] 2016-10-22 22:35
..After recreate a blank uwp background application wirh latest packages of azure.device.client application woks good!!..the original project instead ,after update library ,still have same issue..probabilly is broken in some way..but the new application continusly shows a conflict warning between assembly..

**Comment by jsiegmund** [comment] 2016-10-28 06:45
I'm having similar issues and it seems to be related to incoming messages in particular. I see this error pop-up in my logs: 

Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException' in mscorlib.ni.dll
2016-10-28 08:40:41:4029	Type: Error	Id: 4	Message: 'Unexpected exception listening to incoming cloud messages: Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException: Exception of type 'Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException' was thrown.

And then after some time I get a NullReferenceException without any stacktrace information. I'm still trying to isolate the issue to ensure that it's caused by the devices library, but it sure seems to be related.

**Comment by alexiordan** [comment] 2016-11-06 18:03
I'm running ver. 1.0.21 of 'Microsoft.Azure.Devices.Client' nugget package.
I also get the "Object reference not set to an instance of an object" exception that shuts my app down.
I managed to get the stacktrace that looks like:
```
 at Microsoft.Azure.Amqp.Amqp.Resources.get_AmqpTimeout()
   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1.CompleteOnTimer()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```
My app is an UWP app and I'm getting this error while I'm testing connectivity feedback with several connects/disconnects of my internet connection.

**Comment by tameraw** [comment] 2016-11-21 20:54
The fix for the AMQP lib has been published to NuGet and will make its way to the client once we go through testing.

**Comment by maxuptime** [comment] 2016-12-04 15:03
This issue is partially fixed for me in Microsoft.Azure.Devices.Client 1.1.1.

It's working if I connect with the shared access key in the connection string:
`var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Amqp);`

But not if I'm attempting to obtain the credentials from the TPM (software emulator on RPi):
```
TpmDevice myDevice = new TpmDevice(0); // Use logical device 0 on the TPM
        string hubUri = myDevice.GetHostName();
        string deviceId = myDevice.GetDeviceId();
        string sasToken = myDevice.GetSASToken();

        var deviceClient = DeviceClient.Create(
            hubUri,
            AuthenticationMethodFactory.
                CreateAuthenticationWithToken(deviceId, sasToken), TransportType.Amqp);
```

It connects and can send/receive messages, but then throws a NullReferenceException after 10ish minutes:
```
System.NullReferenceException was unhandled
Exception thrown: 'System.NullReferenceException' in Microsoft.Azure.Amqp.Uwp.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.ni.dll
Additional information: Object reference not set to an instance of an object.
```

Anyone else using the TPM have this working?

I reproduced the problem with a new Background Application (IoT) project template and the Azure IoT Hub Connected Service 1.5.0.

Device Model:	Raspberry Pi 3
OS Version:	10.0.14393.448

**Comment by arturl** [comment] 2016-12-05 18:51
Hi @maxuptime, this is most likely SAS token expiration issue. You will need to refresh the token periodically.
The `NullReferenceException`  will be replaced with a more meaningful exception when the bug fix is integrated (sorry it's taking us so long)

**Comment by tameraw** [comment] 2017-01-09 21:19
Fix checked in. Please let us know if still having any issues in the new csharp repo:
https://github.com/Azure/azure-iot-sdk-csharp

**Closed by tameraw** 2017-01-09 21:19 UTC
Labels: bug
