### ISSUE TITLE
Java Service SDK - Cloud 2 Device client hanging and doesn't throw any error when the connection string is incorrect

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#938] opened 2016-11-09 20:48 UTC
code: https://gist.github.com/dluc/adb431f0cfd67e55e4bf6dbd30e039ae

Note: the code is a copy of the [sample code](https://github.com/Azure/azure-iot-sdks/blob/master/java/service/samples/service-client-sample/src/main/java/samples/com/microsoft/azure/iot/service/sdk/ServiceClientSample.java) from the SDK, with a fake connection string and a fake deviceID for the purpose of the test.

The code as is doesn't throw any error and the client seems to hang forever. 
It's not possible to understand if a message is delivered.

Output:
```
Preparing message...
HostName=iothubreact-demo5p-temper.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=7YMwcekzZdESRB9OcNJiUH61f+N3mj1K//T1jFyejP8=
Creating client to iothubreact-demo5p-temper.azure-devices.net...
Connecting to iothubreact-demo5p-temper.azure-devices.net...
Sending message...
Nov 09, 2016 12:39:27 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory getClass
WARNING: unable to load org.bouncycastle.openssl.PEMReader
Nov 09, 2016 12:39:27 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory getClass
WARNING: unable to load org.bouncycastle.openssl.PasswordFinder
Nov 09, 2016 12:39:27 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory <clinit>
WARNING: unable to load bouncycastle provider
```

Using `com.microsoft.azure.iothub-java-client`:`iothub-java-service-client`:`1.0.10`

**Comment by dluc** [comment] 2016-11-09 21:08
Note: the same behavior occurs with valid credentials (e.g. using `iothubowner`) and a valid device ID (verified from the portal)

**Comment by enuysa-msft** [comment] 2016-11-10 16:03
Hi @dluc 

I have tested your code by changing connection string and a deviceID 
As seen below I can receive feedback information
![1](https://cloud.githubusercontent.com/assets/21202184/20183819/8d378ebe-a75e-11e6-8cef-f3076409c879.PNG)
And I can also see below that my message is recived by device
![2](https://cloud.githubusercontent.com/assets/21202184/20183824/90d29b9a-a75e-11e6-8f52-178db985165c.PNG)

**Comment by enuysa-msft** [comment] 2016-11-14 09:19
Closing. Please re-activate if you still are having issues. Thanks !

@tameraw Could you please close this?

**Comment by dluc** [comment] 2016-11-17 19:07
hi @enuysa-msft 

with a correct connection string and device ID the sample works. The issue I reported is different though:

> when using a *wrong* connection string, the sample doesn't fail

The SDK should report an error to the user, something like "authentication failed".

**Comment by dluc** [comment] 2016-11-17 19:09
I think the issues should be addressed, could you reopen it?

**Comment by cwrenniks** [comment] 2016-11-17 20:22
This should definitely be re-opened, as the issue is about incorrect connection string and the lack of messaging around it.

**Comment by enuysa-msft** [comment] 2016-11-18 09:21
Hi @dluc, 

Sorry for misunderstanding, You are right it is not showing an error to the user, something like "authentication failed". I will working on it now.

**Comment by tameraw** [comment] 2017-01-12 18:59
This issue was moved to Azure/azure-iot-sdk-java#11

**Closed by tameraw** 2017-01-12 18:59 UTC
Labels: CSS, enhancement
