### ISSUE TITLE
AMQP library conflicts when trying to send device to cloud messages using Java API

### ISSUE THREAD

**Issue by UmerF920** [Azure/azure-iot-sdks#274] opened 2016-02-03 06:49 UTC
AMQP library throws connection timeout exception when trying to send device to cloud messages using JAVA API.

**Comment by iluican** [comment] 2016-02-03 10:34
Hello,

I cannot seem to be able to repro this. Could you please give me more information? A screenshot with the error would be of great help. 

Just a few pointers, can you please check that the hub is correctly configured? Using Device Explorer (https://github.com/Azure/azure-iot-sdks/releases/download/2016-01-15/SetupDeviceExplorer.msi), can you see the list of devices? It could also be that you have a firewall which blocks out the AMQP port. Did you try the other protocols, and, if so, what is the result?

Thank you,
Ilie.

**Comment by tameraw** [comment] 2016-02-12 23:10
@UmerF920 - We're closing this issue as we could not reproduce. Please feel free to reopen if still having problems. Note that we have updates since then.

**Closed by tameraw** 2016-02-12 23:10 UTC
Labels: bug
