### ISSUE TITLE
[Java Device Client]Multiple open sockets during reconnect

### ISSUE THREAD

**Issue by BlueBasher** [Azure/azure-iot-sdks#655] opened 2016-06-23 16:00 UTC
To reconnect it keeps open several sockets in parallel, but no more than 13.
All these TCP sockets are of course stuck in the TCP SYN phase and when a new socket is opened, it closes the oldest of the 13.
When the network is back, the connection is re-established within 10 seconds.
However, after connection-reestablishment all 13 sockets reconnect, resulting in over 100K of data usage. But only one of those sockets is actually used, the other 12 are immediately put to CLOSE_WAIT state where they stay indefinitely.
Only exiting the application releases/closes those sockets. When the connection is lost again, the same process will repeat, increasing the sockets in CLOSE_WAIT with every connection-reestablishment. In my tests I got more than 40 sockets in CLOSE_WAIT. This is probably a resource leak, a bug in the code.

**Comment by jtanner-msft** [comment] 2016-06-27 22:36
Are you still seeing this issue?  Can you please clarify exactly which sample and transport you are using when you see the problem?
Is there anything else involved in reproducing the issue that we should know about?

**Comment by BlueBasher** [comment] 2016-07-01 13:29
We've seen this using Java SDK 1.0.5 using the AMQPS protocol.
We didn't use one of the samples from GitHub, but our test-application was pretty much the same as the Send-Event sample. We simply create a DeviceClient, open it, wait for keypress and close it.

For reproducing it, after the deviceClient established connection with the IoTHub, we disconnected the ethernet-cable, waited a while and the plug the cable back in.

**Comment by zolvarga** [comment] 2016-07-08 22:15
Hi BlueBasher.

Could you please specify what environment you are using? Windows, Linux etc... Also what tool you are using to see the CLOSE_WAIT state? (I am using TCPViewer on Windows) I have the hanging sockets from the Java processes but none of them has changed its state. Either in LISTENING or ESTABLISHED state they are.

Thanks,
Zoltan

**Comment by BlueBasher** [comment] 2016-07-11 14:08
We saw this on a Linux (Ubuntu) machine. The capture has been made using TcpDump.

If you also saw the hanging sockets, did you also see the reconnecting over all of those sockets?
The biggest issue for us is the 100K in data being used by reconnecting over those multiple sockets, not per se the sockets themselves.

**Comment by zolvarga** [comment] 2016-07-12 19:01
@BlueBasher 

I have checked in a workaround/fix into azure-iot-sdks develop branch. The fix worked well in our tests, the sockets are not held anymore and the reconnect works fine. 
I will continue the talk to proton guys (because their state variable handling is not correct) but regardless that, the issue you filed has been fixed and you can test is with our SDK.

We are going to release the next version of our SDK early next week and after that you can test it with the master branch also.

Please let me know...

Regards,
Zoltan

**Comment by BlueBasher** [comment] 2016-07-13 14:04
Cool, thanks! We'll grab the develop branch and will start testing asap.
I'll let you know the outcome as soon as we're done.

**Comment by BlueBasher** [comment] 2016-07-15 13:04
We haven't seen the hanging sockets in our tests so the workaround/fix seems to fix the issue.
From my perspective this issue can be closed.

**Comment by tameraw** [comment] 2016-07-22 18:16
@BlueBasher - Thanks for confirming. Closing this issue.

**Closed by tameraw** 2016-07-22 18:16 UTC
Labels: CSS, investigation-required
