### ISSUE TITLE
[C][Linux] client sample amqp websockets run error

### ISSUE THREAD

**Issue by tlautens** [Azure/azure-iot-sdks#664] opened 2016-06-28 12:48 UTC
Hi,
I'm trying to run the iothub_client_sample_amqp_websockets.  It stops with a segmentation fault. The ConnectionString was insert properly. Also the http-sample works fine.

This is the gdb output:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Program received signal SIGILL, Illegal instruction.
0xb6ec1848 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
```
So I masked SIGILL with `<gdb> handle SIGILL nostop`
But now the following error occurs:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Program received signal SIGILL, Illegal instruction.
Starting the IoTHub client sample AMQP over WebSockets...
Info: IoT Hub SDK for C, version 1.0.9
Program received signal SIGSEGV, Segmentation fault.
0x0004fc4a in indicate_all_messages_as_error ()
```
Would you please provide some help at this point?

**Comment by chrit-msft** [comment] 2016-07-05 22:42
@tlautens Thank you for raising this issue.  I have built the sample and hit the same error and it appears there is a function table that has a pointer math error in it.  I will bring this up with the code owner and update you when I have more information.

**Comment by chrit-msft** [comment] 2016-07-13 17:22
@tlautens can you confirm is you are still seeing this issue after updating your repository including submodules?  On my end I can no longer reproduce the segfault using the latest pull.

**Comment by chrit-msft** [comment] 2016-07-20 13:52
@tlautens I will be closing this issue since I am unable to reproduce this behavior.  If you encounter this behavior again please reopen the issue.

**Closed by chrit-msft** 2016-07-20 13:52 UTC
Labels: CSS, help wanted
