### ISSUE TITLE
unknown errors 

### ISSUE THREAD

**Issue by Maximus1129** [Azure/azure-iot-sdks#562] opened 2016-05-16 20:41 UTC
Hello I was following the following tutorial 
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md
and came with the following errors after I ran " ./build.sh --no-mqtt" on the terminal. Anyone faced those problems before?
CMake Error at CMakeLists.txt:62 (add_subdirectory):
  The source directory

    /home/root/azure-iot-sdks/c/azure-uamqp-c

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:63 (add_subdirectory):
  The source directory

    /home/root/azure-iot-sdks/c/azure-umqtt-c

  does not contain a CMakeLists.txt file.

CMake Error at iothub_client/tests/iothubclient_ll_unittests/CMakeLists.txt:21 (build_test_artifacts):
  Unknown CMake command "build_test_artifacts".

**Comment by markrad** [comment] 2016-05-17 00:01
If I had to guess, I would suspect that you forgot to add the --recursive flag to the git clone command and did not clone the git subprojects. Look and see if there any files in the directory to which you referred.

_Mark Radbourne MSFT_

**Comment by Maximus1129** [comment] 2016-05-17 01:21
thank you for your reply Markrad. Do you mean the following command "git clone --recursive https://github.com/Azure/azure-iot-sdks.git"? I checked twice, and I am sure I added recursive just like the command above. 
Do you have any other suggestions for me ? And one more thing, I was asked to Change line "make --jobs=nproc" to "make --jobs=2" in my "build.sh" file. I can not find exact line "make --jobs=nproc", instead what I found was like "make --jobs=$.....(something like this but not "make --jobs=nproc")",and what I did was just change it to "make --jobs=2". Should it be like that?
BTW, I was using Intel Edison.

**Comment by markrad** [comment] 2016-05-18 00:31
Hi @Maximus1129,

So if you _cd_ into _/home/root/azure-iot-sdks/c/azure-uamqp-c_ and run the _ls_ command do you see a) any files and b) a CMakeLists.txt file? You cloning appears to be correct, I just want to see if it failed to download those submodules for some reason. You should see something akin to this:
```
markrad@MRUBUDT1510:~/Source/azure-iot-sdks-xcomp/c$ ls
azure-c-shared-utility  azure-uamqp-c  azure-umqtt-c  build_all  certs  CMakeLists.txt  doc  iothub_client  readme.md  serializer  service  testtools  tools
markrad@MRUBUDT1510:~/Source/azure-iot-sdks-xcomp/c$
```

I have an Intel Edison here on my desk and I've been looking for an excuse to fire it up. I'll also try this for myself to see if I can reproduce your issue.

_Mark Radbourne MSFT_

**Comment by Maximus1129** [comment] 2016-05-18 00:59
Hello @markrad I checked there existed CMakeLists.txt file. What I am thinking is that the error was probably caused by the following "git: 'submodule' is not a git command. See 'git --help'."   after I run  "git clone --recursive https://github.com/Azure/azure-iot-sdks.git" . I do not know it is an error or I should just ignore it.
I am also trying to figure it out. Thanks for your help!

**Comment by markrad** [comment] 2016-05-27 01:45
Hi @Maximus1129,

I've done some further research into this issue. As I suspected the version of git that is available from the opkg repository does not have the submodule support included. This leaves you with three options.

1. You can git clone the azure-c-shared-utility, the azure-uamqp-c and the azure-amqtt-c repositories into the appropriate locations in the tree. You will also need to clone the azure-c-shared-utitlity into both the azure-uamqp-c and azure-umqtt-c repositories too since they both also reference it.
2. You could download the source of git and build the full version on your Intel Edison.
3. You could build the SDK on a different host using the cross compiler tool chain provided for that purpose.

Of the three, I would recommend option three. You can find a discussion that should assist you setting up the cross compiler environment in issue https://github.com/Azure/azure-iot-sdks/issues/435 (see the response by ashokkhurana on Apr 15) and a cross compile example using the Raspberry Pi as a target at https://github.com/markrad/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md. All this assumes that you are running a Linux desktop of some sort.
Let me know if you have further problems.

**Comment by Maximus1129** [comment] 2016-06-01 19:05
Hello @markrad thanks for your reply. My boss told me to let me work on anther board, I may go back to Intel edison after that. Your suggestions have been really helpful, I will let you know if I have any problem. Thanks for your help for the past several days!

**Comment by markrad** [comment] 2016-06-06 18:15
Hi @Maximus1129,

You're very welcome. Since you are not working on the Intel Edison for the time being, I have gone ahead and closed this issue. If you encounter further problems with this platform please reopen the issue and I will continue to assist you.

_Mark Radbourne MSFT_

**Closed by markrad** 2016-06-06 18:15 UTC
Labels: CSS, help wanted
