### ISSUE TITLE
get stuck while running about 30 minutes with the latest master release of Java SDK

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#403] opened 2016-03-21 09:51 UTC
Hi, 
I ran the sample code with just a little modification. and it went well with the older master releases.
But, i found that it got unresponsive when i ran the app with the latest Java SDK for 30 minutes.
I tested a few computers and the same reault showed up. My colleague had the same experiences as well. Have you run the Java SDK for more than 30 minutes?

**Comment by iluican** [comment] 2016-03-21 20:43
Hello,

Thank you for using our SDK. Yes, we have run the Java SDK for more than 30 minutes. I would appreciate very much if you could you please give us more details about your particular application. More precisely, what protocol are you using to send data? Are you also receiving data from IotHub? Also, how exactly do you define "unresponsive"? When attempting to send a message, do you get some kind of error, or simply nothing happens?

Thank you,
Ilie.

**Comment by eissi** [comment] 2016-03-21 23:10
I ran two patterns. one is just sending events and another is receiving and responding events. Both have the problem if my memory serves well. if you haven't seen the issue occurring, I will gather more data for you. No exception was received when the event callback wasn't hit while event was in the device queue of IoT Hub. (I'm working with Samsung that you might have called with CAT a couple of weeks ago.)

**Comment by GwangseokHahm** [comment] 2016-03-22 09:54
Hello.

I'm working with eissi.
When I tested, exception occurred as below.

'Failed to send message because: The AMQPS IotHub Connection is currently closed. Call open() before attempting to schedule a message.'

This exception occuurs when the ReactorState is CLOSED in AmqpsIotHubConnection.java.

When I tested previous release, this exception occurred too and the status was recovered shortly.

But in latest realese this exception occurred unceasingly and the staus wasn't receverd.

Finnally, IOConsole Updater error with out of heap memory in eclipse occurred for too many stdout with exception log.

Thanks.

**Comment by iluican** [comment] 2016-03-22 17:27
Thank you for the details. I will investigate this.

**Comment by iluican** [comment] 2016-03-23 02:34
Upon my investigation I was able to repro the issue, which is a regression. I also have a fix in the pipeline, which will probably be checked in tomorrow. The fix will be incorporated in our upcoming release, which will happen at the end of this week.

Thank you,
Ilie.

**Comment by eissi** [comment] 2016-03-28 03:27
Hi, Iluican

I haven’t seen the latest release you mentioned in GitHub. Can you share any update when the new release will be?
And when released, all codes in the developer branch right now will go into master branch release or some of codes will be in master?

감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by iluican** [comment] 2016-03-29 01:49
Hello,

Turned out I was wrong, my assumption for the root cause of the bug was incorrect. Today I was working on this, but I was not able to identify the root cause. I will update the issue the moment I figure out what is going on. Also, when I have the fix ready, I will release the package to maven. This should not take more than a couple of days.

Thank you,
Ilie.

**Comment by eissi** [comment] 2016-03-31 15:09
iluican, do you have any update on this issue?
My customer is running out of time for the dead line...

**Comment by iluican** [comment] 2016-03-31 19:51
Yes, the code has been checked in yesterday and the package was released to Maven. Please let us know how it works out for you.

Thank ou,
Ilie.

**Comment by eissi** [comment] 2016-04-01 00:35
Do you have any plan when to release to master with your fix?

Sent from Outlook<https://aka.ms/kr63o9> on iOS




On Thu, Mar 31, 2016 at 12:51 PM -0700, "iluican" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, the code has been checked in yesterday and the package was released to Maven. Please let us know how it works out for you.

Thank ou,
Ilie.

-

**Comment by iluican** [comment] 2016-04-01 19:06
Our next release will happen the upcoming Friday, April 8th. That's when the code will be pushed into master. Meanwhile please grab the code from develop and let us know if you find anything wrong. Also, please let me know whether I can close this issue.

Thank you,
Ilie.

**Comment by eissi** [comment] 2016-04-02 00:56
I will test and get back here.

감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by eissi** [comment] 2016-04-02 14:05
Sorry, it seems that the problem isn’t fixed yet.
I ran HandleMessages.java a few times. It stopped receiving a message less than 2,100 messages total from Cloud about 8 minutes later.
I might go deep with SDK, but you could repro this symptom easily.

감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by iluican** [comment] 2016-04-04 08:36
This sounds like a different issue from the one I fixed. I did not touch the receive code at all as a part of my fix. I will look into that first thing tomorrow.

**Comment by eissi** [comment] 2016-04-06 11:24
Hi, is there any update on this?

**Comment by iluican** [comment] 2016-04-11 20:20
This is fixed.

**Closed by iluican** 2016-04-11 20:20 UTC
Labels: bug
