### ISSUE TITLE
[C][Linux] Iothub_client_sample_http can't run

### ISSUE THREAD

**Issue by kevin0402** [Azure/azure-iot-sdks#590] opened 2016-05-30 09:00 UTC
Running Iothub_client_sample_http on my embedded device and get following error messages:

_Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.0.7
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
Error: Time:Mon May 30 16:44:01 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure-iot-sdks/c/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:489 curl_easy_perform() failed: Unsupported protocol

Error: Time:Mon May 30 16:44:01 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure-iot-sdks/c/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:491 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon May 30 16:44:01 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure-iot-sdks/c/azure-c-shared-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Mon May 30 16:44:01 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure-iot-sdks/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1573 unable to HTTPAPIEX_SAS_ExecuteRequest_

The example code is on the develop branch.
Linux kernel version : 2.6.31
Curl version : 7.48.0

**Comment by anhashia** [comment] 2016-05-31 21:00
Looking into this.

**Comment by anhashia** [comment] 2016-06-02 23:47
Hi @kevin0402 
I wasn't able to reproduce the issue on Ubuntu using master branch. I then looked at the error code CURLE_UNSUPPORTED_PROTOCOL.It is an error coming from call to curl library and covered in **detail** under https://curl.haxx.se/libcurl/c/libcurl-errors.html
The error code seems to coming from **missing** curl functionality in your curl client library.
For your reference, below are my `curl --version `details on which I don't see your issue.


```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

```

**Comment by kevin0402** [comment] 2016-06-07 09:46
Hi @anhashia 

I cross compile libcurl for my target ARM based platform as below:

_./configure --build=i686-pc-linux-gnu --target=arm-none-linux-gnueabi --host=arm-none-linux-gnueabi --disable-ipv6 --with-ssl=/root/test/project/openssl --with-zlib=/root/test/project/zlib CC=/root/test/toolchain/bin/arm-none-linux-gnueabi-gcc_

I upload both libcurl.so.4 and curl executable file to my target board because I am not sure which one will be used by HTTP example.

My curl --version details as below:

_curl 7.48.0-DEV (arm-none-linux-gnueabi) libcurl/7.48.0-DEV OpenSSL/1.0.2g zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets_

I got different failed result when running iothub_client_example_http:

_Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.0.7
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
Error: Time:Tue Jun  7 17:24:33 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure/c/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:489 curl_easy_perform() failed: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision._

_Error: Time:Tue Jun  7 17:24:33 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure/c/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:491 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Tue Jun  7 17:24:33 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure/c/azure-c-shared-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Tue Jun  7 17:24:33 2016 File:/root/moxa/mg5105_azure/application/shareApps/cloud/azure/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1573 unable to HTTPAPIEX_SAS_ExecuteRequest_

According to above messsage, I have no idea about which feature or option is missing in libcurl.

**Comment by anhashia** [comment] 2016-06-07 18:52
From the error code, it looks like right version of the curl library is not linked which has the feature to run the sample. \c\iothub_client\samples\iothub_client_sample_http\linux\CMakeLists.txt file points to curl library under  target_link_libraries. Do you also cross compile the HTTP sample after updating the curl library for target platform ? 

Below link covers example of **cross compiling** for reference
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md

**Comment by anhashia** [comment] 2016-06-21 22:59
Closing this. Please let us know if you're still having issues. Thanks !

**Closed** 2016-06-24 23:34 UTC
Labels: CSS, help wanted
