### ISSUE TITLE
Timed out trying to create FaultTolerantAmqpObject`1

### ISSUE THREAD

**Issue by hotants** [Azure/azure-iot-sdks#568] opened 2016-05-18 03:58 UTC
Hi guys,
     Would you help me to clarify what's the possible reason for this exception, which I faced randomly:
     

Error message: Timed out trying to create FaultTolerantAmqpObject`1 
T:    Stack Trace:    at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<OnReceiveAsync>d__33.MoveNext()
T:--- End of stack trace from previous location where exception was thrown ---
T:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
T:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
T:   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
T:   at Microsoft.Azure.Devices.Client.Transport.TransportHandlerBase.<ReceiveAsync>d__14.MoveNext()

I'm using 
 Microsoft.Azure.Amqp" version="1.1.1"
Microsoft.Azure.Devices.Client" version="1.0.5" 
thanks
Denny

**Comment by rajeevmv** [comment] 2016-05-18 17:28
This indicates that the C# device client was unable to establish an Amqp connection to IotHub to receive Commands.

Can you provide some more info:

1. Which DeviceClient API are you using to create the device client instance?

2. Are you specifying a protocol type (Amqp, Amqp over TCP, Amqp over WS)?

3. Are you behind a firewall which blocks port 5671?

Also, if you could provide the IotHubName and time frame when this occurred that would be useful.

**Comment by hotants** [comment] 2016-05-19 05:48
Here are the answers to the questions:
1. DeviceClient.CreateFromConnectionString
2. Amqp
3. Port 5671 allowed
The IotHubName is cbpt01datdev
Time when the exception is raised:
2016-05-17 13:55:38.873
2016-05-17 13:57:30.189 
2016-05-17 14:00:01.231

Thanks
Denny

**Comment by rajeevmv** [comment] 2016-05-21 01:22
I do not see any errors on the service-side for your IotHub on 05/17.

Can you comment on how frequently these occur and also indicate what activity is happening at that time? Is it idle or receiving a lot of commands?

Is there a simple repro sample that you could share?

**Comment by rainmakerho** [comment] 2016-06-20 01:46
I had the same problem, 
2016-06-17T22:42:34.9613813+00:00|FATAL|3|MainPage|exception:System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<OnReceiveAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.TransportHandlerBase.<ReceiveAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
The IotHubName is gsstddhub.azure-devices.net

**Comment by jtanner-msft** [comment] 2016-06-22 18:54
Hello,

  I tried to see if I could reproduce the issue you have mentioned using the default C# AMQP Sample and switching the UWP App to use AMQP as well, but so far no luck.

  Can you please provide a few more details on exactly which sample you were running, how many messages are getting sent, how many device(s) are being used what frequency that you experience the exception?

  As Rajeev had asked if have a simple repro sample or instructions you can share that would be helpful.

Thanks!

**Comment by hotants** [comment] 2016-06-23 02:50
It’s not easy for me to extract code as sample from our production code, Finally I gave it up. Sorry for the delay response
The exception is occasionally raised during SpecFlow tests which running in parallel, for my case still able to send and receive message although the exception is raised.

**Comment by rainmakerho** [comment] 2016-06-25 10:29
Hi Sirs, 
     ServiceClient will send message to IOT Hub when our app called.

var serviceClient = ServiceClient.CreateFromConnectionString("IOTHubConnectionString", TransportType.Amqp);
var commandMessage = new Message(Encoding.UTF8.GetBytes(message));
commandMessage.Ack = DeliveryAcknowledgement.None;
await serviceClient.SendAsync(deviceName,commandMessage);

    UWP App is running in Raspberry Pi every day. Thanks.

**Comment by rainmakerho** [comment] 2016-06-27 00:58
My  uwp app still had exception, 

2016-06-24T01:25:25.7978462+00:00|FATAL|3|MainPage|exception:System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<OnReceiveAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.TransportHandlerBase.<ReceiveAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RaspJob.MainPage.<ReceiveCloudToDeviceMessagesAsync>d__16.MoveNext()DateTime:20160624 09:25:25.78
27|2016-06-24T01:25:36.9683771+00:00|FATAL|3|MainPage|exception:System.InvalidOperationException: A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<OnOpenAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<TryOpenPrioritizedTransportsAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.DeviceClient.<TryOpenPrioritizedTransportsAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<EnsureOpenedAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<EnsureOpenedAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<<ReceiveAsync>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by jtanner-msft** [comment] 2016-06-27 22:25
I’m sorry but I’m still unclear on the steps you are following before you see this issue reproduce.

You mentioned that you are running on a Raspberry Pi, is it a Rpi2 or an Rpi3 that you are using?  Since it’s a UWP app I’m guessing that you are running Windows 10 IoT Core, but what OS version are you using on the device?

Once you start the sample running, do you see the exception immediately, or only after it’s run for a full day?

The more you can provide us with step by step instructions, the quicker we should be able to reproduce the problem and hopefully determine why you are seeing this exception.

Thanks.

**Comment by rainmakerho** [comment] 2016-06-29 03:24
I deploy uwp app to Raspberry Pi 2 Model B (Windows 10 IoT Core 10.0.14366.0).
I start app from Web Browser  AppManager.htm that connect to Raspberry Pi  
and let app run full days. 
Thank for your help.

**Comment by jtanner-msft** [comment] 2016-07-14 18:27
Hi rainmakerho,

  As you suggested I’ve tried to repro the issue you were seeing with a Rpi2, but I chose to run the slightly newer OS version 10.0.14376.0.  I’ve tested within the latest develop branch from github as of this past Friday.

  Next, to keep things simple I modified the UWP Sample app which is included in the solution iothub_cshare_deviceclient.sln with the following changes:

1.	Change the transport from http to amqp.
2.	Set the message count to 6000 so it would run for a few days.
3.	Added a 15 second time delay after reach message send:
                	await deviceClient.SendEventAsync(eventMessage);
              await Task.Delay(TimeSpan.FromSeconds(15));

  After running this test for a few days I have yet to see the exception you were describing.  If you run the sample as I’ve described, do you see anything still?  If not, please let me know if we can close this issue.

Thanks.

**Comment by rainmakerho** [comment] 2016-07-19 03:24
Hi Jtanner,
   I use two console to test(SendC2DMessage and ReadC2DMessage).

*** SendC2DMessage create ServiceClient instance first and loop send message everydays.
static void Main(string[] args)
{
	Console.WriteLine("Send Cloud-to-Device message\n");
	Stopwatch stopwatch = new Stopwatch();
	stopwatch.Start();
	serviceClient = ServiceClient.CreateFromConnectionString(connectionString, TransportType.Amqp);
	stopwatch.Stop();
	Console.WriteLine(" ServiceClient.CreateFromConnectionString Time elapsed: {0}", stopwatch.Elapsed);
	while (true)
	{
		stopwatch.Restart();
		SendCloudToDeviceMessageAsync().Wait();
		stopwatch.Stop();
		var et = stopwatch.Elapsed;
		if(et > TimeSpan.FromSeconds(1))
		{
			Console.BackgroundColor = ConsoleColor.Red;
		}
		Console.WriteLine("SendCloudToDeviceMessageAsync().Wait()  Time elapsed: {0}, {1} ", et, DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss.ttt"));
		Thread.Sleep(TimeSpan.FromMinutes(20));
		Console.BackgroundColor = ConsoleColor.Black;
	}
	Console.ReadLine();
}

private async static Task SendCloudToDeviceMessageAsync()
{
	var commandMessage = new Microsoft.Azure.Devices.Message(Encoding.ASCII.GetBytes(DateTime.Now.ToString("HH:mm:ss:fff")));
	await serviceClient.SendAsync("0521", commandMessage);
}

*** ReadC2DMessage create DeviceClient instance first and loop receive the message everydays.

private static async void ReceiveC2dAsync()
{
	Console.WriteLine("\nReceiving cloud to device messages from service");
	DeviceClient deviceClient = DeviceClient.CreateFromConnectionString(
				"mydeviceConnstring",  TransportType.Amqp 
				);
	while (true)
	{
		Message receivedMessage = await deviceClient.ReceiveAsync();
		if (receivedMessage == null) continue;

		Console.ForegroundColor = ConsoleColor.Yellow;
		Console.WriteLine("Received message: {0} @ {1}"
			, Encoding.ASCII.GetString(receivedMessage.GetBytes())
			, DateTime.Now.ToString("HH:mm:ss.fff"));
		Console.ResetColor();
		await deviceClient.CompleteAsync(receivedMessage);
	}
}

The applications will cause exceptions until about 24 hours.
SendC2DMessage's Exception 
未處理的例外狀況: System.AggregateException: 發生一或多項錯誤。 ---> System.Time
outException: Unable to retrieve AMQP Artifacts for iothub.gsstddhub.11093.cad1e
113/fcd6a959-0ce0-4800-82f6-8fbbd21b1f49. Timeout: 00:00:30.
Tracking Id:26a2dd03142e43548981ac889c02a457-G:9-TimeStamp:07/01/2016 01:00:24
   於 Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__26.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   於 SendC2DMessage.Program.<SendCloudToDeviceMessageAsync>d__10.MoveNext() 於
D:\Temp\CreateDeviceIdentity\SendC2DMessage\Program.cs: 行 34
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   於 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   於 System.Threading.Tasks.Task.Wait()
   於 SendC2DMessage.Program.Main(String[] args) 於 D:\Temp\CreateDeviceIdentity
\SendC2DMessage\Program.cs: 行 201

 ReadC2DMessage's exception
未處理的例外狀況: Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Put token failed. status-code: 500, status-description: Unable to retrieve AMQP Artifacts for iothub.gsstddhub.11093.cad1e113/fcd6a959-0ce0-4800-82f6-8fbbd21b1f49.
 Timeout: 00:00:45..
   於 Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<ReceiveAsync>d__22.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__13`1.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<ReceiveAsync>d__10.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<ReceiveAsync>d__7.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   於 ReadC2DMessage.Program.<ReceiveC2dAsync>d__1.MoveNext() 於 D:\Temp\CreateDeviceIdentity\ReadC2DMessage\Program.cs: 行 26
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   於 System.Threading.ThreadPoolWorkQueue.Dispatch()

So.. I recreate ServiceClient instance (serviceClient = ServiceClient.CreateFromConnectionString(connectionString, TransportType.Amqp);) pass by 23 hours. 

It looks OK until now.
Is it necessary to recreate ServiceClient instance everydays? 

Thank for your help.

**Comment by anhashia** [comment] 2016-07-26 23:38
Investigating why you are seeing exceptions after around 24 hours.

**Comment by anhashia** [comment] 2016-08-05 19:40
Checking if issue can be locally reproduced by running send and receive samples for extended period of time.

**Comment by anhashia** [comment] 2016-08-08 17:39
I tried with both 1 second and 20 second iterations but I don't see the exception after 24 hours in either send or receive sample. I tested it on Windows 10 PC. Can you try it on different device and see if you see the same issue ?

**Comment by rainmakerho** [comment] 2016-08-09 05:00
I don't see any exception currently.
Thank for your help.

**Comment by anhashia** [comment] 2016-08-12 23:13
Closing. Please re-activate if you still are having issues. Thanks !

**Closed by anhashia** 2016-08-12 23:13 UTC
Labels: CSS, help wanted
