### ISSUE TITLE
Raspberry Pi blocks while running build.sh for Python

### ISSUE THREAD

**Issue by HeinPauwelyn** [Azure/azure-iot-sdks#897] opened 2016-10-26 15:16 UTC
I've cloned this project on 2016/10/26 on my Raspberry Pi 2 Model B+ with this command:

```
git clone --recursive https://github.com/Azure/azure-iot-sdks
```

After that I've run this two files:

```
./azure-iot-sdks/python/build_all/linux/setup.sh
./azure-iot-sdks/python/build_all/linux/build.sh
```

With the first file I haven't any problem. The problem occurs when I run the file `build.sh`. This code will block my Raspberry Pi while the build is done for 98%. I've uploaded an image with the output.

[![Problem](https://cloud.githubusercontent.com/assets/16222780/19731069/7e8898fe-9b9c-11e6-947a-cac6aa5a1fb6.jpg)](https://cloud.githubusercontent.com/assets/16222780/19731069/7e8898fe-9b9c-11e6-947a-cac6aa5a1fb6.jpg)
<sub>Couldn't take a print screen because Pi was blocked and had to reboot the Pi.</sub>

Did I miss anything or is this a bug in the code?

Btw, I'm using the SDK for Python.

**Comment by anhashia** [comment] 2016-10-26 20:45
Investigating !

**Comment by anhashia** [comment] 2016-10-26 20:55
Try with `./build.sh --use-websockets --skip-unittests`  : This option will skip unit tests and will include AMQP over WebSockets sample. Check if you see the same issue with this command.

**Comment by anhashia** [comment] 2016-10-29 01:47
HI @HeinPauwelyn 
I had a chance to try it **locally** on Raspberry Pi 2 and I was able to successfully move to 100%. It does take couple of minutes  to move from 98% to 100% and show final results.

Below is the log for your reference

````````````
[ 98%] Built target iothub_client_python
Scanning dependencies of target iothub_client_mock
[ 99%] Building CXX object python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o
[100%] Building CXX object python/test/CMakeFiles/iothub_client_mock.dir/__/src/iothub_client_python.cpp.o
Linking CXX shared library iothub_client_mock.so
[100%] Built target iothub_client_mock
Test project /home/pi/works/azure-iot-develop/c/cmake/iotsdk_linux
No tests were found!!!
~/works/azure-iot-develop
copy iothub_client library to samples folder
copy iothub_client_mock library to tests folder
python2.7 iothub_client_ut.py

```````````````````

**Comment by HeinPauwelyn** [comment] 2016-10-29 06:52
By me it was more than a couple of minutes. Maby a hour for move from 98% to 100%.

**Comment by anhashia** [comment] 2016-11-01 23:50
Hi @HeinPauwelyn 

There does seem to be good amount of **memory** consumption while building `Building CXX object python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o`

When your build gets stuck, check you memory consumption by running `free -m` command on another terminal window and see how your memory availability looks like.

**Comment by mregen** [comment] 2016-11-05 08:26
This is likely a duplicate of #458. 
Please follow instructions: [Change swap file size](https://www.bitpi.co/2015/02/11/how-to-change-raspberry-pis-swapfile-size-on-rasbian/) on Raspbian and let me know if this fixes the build.

**Comment by anhashia** [comment] 2016-11-10 22:34
Closing this. Please re-activate if you have any further questions on this. Thanks !

**Closed** 2016-11-11 08:05 UTC
Labels: build issue, CSS, question

**Comment by stevebus** [comment] 2016-12-05 20:10
Just to revisit - For what it's worth, I have found that increasing the swap space on raspbian has had a significant impact on performance of build.sh  (it doesn't 'hang', and finishes faster).

**Comment by anhashia** [comment] 2016-12-05 20:14
Hi @stevebus 
Thanks for the information !
