### ISSUE TITLE
[DM][Node] Can't properly send messages

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#623] opened 2016-06-13 12:52 UTC
Hi,
As @damonbarry point me to the iothub-explore, I've try to see my devices on the hub.
My device are connected with AMQPWS and LWM2M, I first try to send a cloud to device message from iothub-explore
```
lmussier@ubuntu:~$ iothub-explorer send ludo hello --ack==full

Message sent
Unhandled rejection TypeError: done is not a function
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/amqp.js:38:7
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iot-amqp-base/lib/amqp.js:147:17
    at tryCatcher (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
I don't get the ack but the message reaches my device, the tool crashed but the message is send.

**Comment by damonbarry** [comment] 2016-06-13 20:18
@lmussier, is your device simultaneously connected to IoT Hub via both the messaging (via AMQP-WS) and DM (via LWM2M) channels?  Does `iothub-explorer send ludo hello --ack==full` work if the device is _only_ connected over AMQP-WS, not LWM2M?  Just trying to narrow this down...

**Comment by pierreca** [comment] 2016-06-14 04:32
That reminds me of a bug in iothub-explorer that was solved with the latest version (1.0.7). What version of iothub-explorer are you running?

**Comment by lmussier** [comment] 2016-06-14 07:26
@pierreca I've install iothub-explrer@dmpreview yesterday
@damonbarry I'll try this.

Thanks

**Comment by damonbarry** [comment] 2016-06-21 20:03
OK.  Can you try it
1. without LWM2M
2. using iothub-explorer@latest (_not_ dmpreview)
...and let me know if the problem is fixed?

We believe the bug is fixed in the `develop` and `master` branches, but hasn't made its way into dmpreview yet.

**Comment by lmussier** [comment] 2016-06-23 08:03
@damonbarry it works for me on develop.
Any idea when develop or master will be merged in dmpreview ?

Thanks

**Comment by damonbarry** [comment] 2016-06-23 17:35
It's a bit ad-hoc right now, but we generally merge develop into dmpreview at least once every two weeks.  We'll also need to publish new packages to npm. I'll take a stab at it today.

**Comment by damonbarry** [comment] 2016-06-27 19:52
FYI I'm working on the merge...

**Comment by damonbarry** [comment] 2016-07-06 20:04
Merge was completed shortly after my previous message, but I forgot to update this thread...sorry  :(

Closing.  Please reopen if needed.

**Closed by damonbarry** 2016-07-06 20:04 UTC
Labels: DM

**Comment by MarceloOrbital** [comment] 2016-10-07 14:43
Hi,

I'm testing with NodeJS running on a Raspberry PI. Although the device to cloud messages reachs its destination, Node always gives the following error:

Unhandled rejection TypeError: done is not a function
at /home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/lib/amqp.js:43:7
at /home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:181:21
at tryCatcher (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:687:18)
at Async._drainQueue (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:17:14)
at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by damonbarry** [comment] 2016-10-07 15:59
@MarceloOrbital can you file a new issue for this? Thanks!
