### ISSUE TITLE
Null Thrown From AMQP10 Library 

### ISSUE THREAD

**Issue by dmoreland** [Azure/azure-iot-sdks#320] opened 2016-02-22 08:59 UTC
```
TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\frames.js:41:9)
    at Connection.sendFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\connection.js:336:10)
    at ReceiverLink.Link.attach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:102:27)
    at ReceiverLink.Link._attemptReattach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:205:8)
    at null._onTimeout (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:193:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

After leaving my code sending messages to Azure after about an hour i get this,

**Comment by pierreca** [comment] 2016-02-22 19:18
Hi @dmoreland 

Do you use client.fromConnectionString() (which is supposed to renew the SAS token automatically) or client.fromSharedAccessSignature() (which lets you handle the SAS token lifecycle) to create your client?

**Comment by dmoreland** [comment] 2016-02-22 19:33
client.fromConnectionString()

**Comment by pierreca** [comment] 2016-02-22 19:55
Ok we might have a bug here. can you share a little bit more of your code or the logs so that we get context? the stack trace is truncated. 
Also, what version of the SDK are you using?

**Comment by dmoreland** [comment] 2016-02-23 07:47
im using version 1.0.1 of the azure-iot-device-amqp and 1.0.1 of azure-iot-device 

```
var openConnectionCB = function(err){
    if(err){
        self.emit('error', err);
    }
        
    azureClient.on('message', function (message) {
        console.log("IOT Message to Broadcast:" + message.data.toString());      
        self.emit('message', JSON.parse(message.data.toString()));
    });

    azureClient.on('disconnect', function() {
        console.log("IOT Client Disconnected");      
        azureClient.removeAllListeners();    
        self.configure();
    });

    azureClient.on('error', function (err) {
        self.emit('error', err);
    });                         
}

IOT.prototype.configure = function configure(connectionString){
    
    azureClient = clientFromConnectionString(connectionString);   
    azureClient.open(function (err) {                  
        openConnectionCB();
        ready = true;
    });    
}

IOT.prototype.send = function send(message){
    var azureMessage = new azureDevice.Message(message);
    console.log("IOT Send:" + message);
    azureClient.sendEvent(azureMessage, function (err) {
        if (err != null) {          
            self.emit('error', err);
        }       
    });
}
```

**Comment by pierreca** [comment] 2016-02-23 19:18
Ok, that should be working. I just ran the sample we provide in the repository for over 12 hours, sending close to 1800 messages, and the token was renewing fine every 45 minutes (auto-generated tokens are valid for 1 hour so we renew early). 

can you activate debug traces and share the part around which disconnection happens? to do so, just define a `DEBUG` environment variable to `*` before running the script. it should spew a lot of stuff, I'm guessing we only need the couple of minutes where the code actually fails. Please make sure to double check logs for sensitive information before you post!

**Comment by dmoreland** [comment] 2016-02-24 10:49
```
amqp10:link Attempting to reattach /devices/XXX/messages/devicebound_3fab864a-dbd3-432f-8176-27fd1d740582 +1s
  amqp10:link /devices/XXX/messages/devicebound_3fab864a-dbd3-432f-8176-27fd1d740582:0: Transitioning from DETACHED to ATTACHING due to sendAttach +1ms
  amqp10:link attach CH=1, Handle=0 +0ms
  amqp10:framing Encoding performative: {"descriptor":18,"value":{"name":"/devices/XXX/messages/devicebound_3fab864a-dbd3-432f-8176-27fd1d740582","handle":{"typeName":"uint","value":0},"role":true,"senderSettleMode":{"typeName":"ubyte","value":2},"receiverSettleMode":{"typeName":"ubyte","value":1},"source":{"descriptor":40,"address":"/devices/XXX/messages/devicebound","durable":0,"expiryPolicy":"session-end","timeout":0,"dynamic":false},"target":{"descriptor":41,"address":"localhost","durable":0,"expiryPolicy":{"contents":"session-end"},"timeout":0,"dynamic":false},"unsettled":{},"incompleteUnsettled":false,"initialDeliveryCount":{"typeName":"uint","value":1},"maxMessageSize":{"typeName":"ulong","value":10000},"offeredCapabilities":null,"desiredCapabilities":null,"properties":{"com.microsoft:client-version":"azure-iot-device/1.0.1"},"encodeOrdering":["name","handle","role","senderSettleMode","receiverSettleMode","source","target","unsettled","incompleteUnsettled","initialDeliveryCount","maxMessageSize","offeredCapabilities","desiredCapabilities","properties"]}} +1ms
  amqp10:framing sending frame: AttachFrame: {"type":"Buffer","data":[0,0,1,26,2,0,0,1,0,83,18,208,0,0,1,10,0,0,0,14,161,73,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,100,101,118,105,99,101,98,111,117,110,100,95,51,102,97,98,56,54,52,97,45,100,98,100,51,45,52,51,50,102,45,56,49,55,54,45,50,55,102,100,49,100,55,52,48,53,56,50,67,65,80,2,80,1,0,83,40,192,65,11,161,36,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,100,101,118,105,99,101,98,111,117,110,100,67,163,11,115,101,115,115,105,111,110,45,101,110,100,67,66,193,1,0,64,193,1,0,64,64,64,0,83,41,192,32,7,161,9,108,111,99,97,108,104,111,115,116,67,163,11,115,101,115,115,105,111,110,45,101,110,100,67,66,193,1,0,64,193,1,0,66,82,1,128,0,0,0,0,0,0,39,16,64,64,193,55,2,163,28,99,111,109,46,109,105,99,114,111,115,111,102,116,58,99,108,105,101,110,116,45,118,101,114,115,105,111,110,161,22,97,122,117,114,101,45,105,111,116,45,100,101,118,105,99,101,47,49,46,48,46,49]}: 0000011a02000001005312d00000010a0000000ea1492f646576696365732f3173744875622f6d657373616765732f646576696365626f756e645f33666162383634612d646264332d343332662d383137362d323766643164373430353832434150025001005328c0410ba1242f646576696365732f3173744875622f6d657373616765732f646576696365626f756e6443a30b73657373696f6e2d656e644342c1010040c10100404040005329c02007a1096c6f63616c686f737443a30b73657373696f6e2d656e644342c1010040c101004252018000000000000027104040c13702a31c636f6d2e6d6963726f736f66743a636c69656e742d76657273696f6ea116617a7572652d696f742d6465766963652f312e302e31 +4ms
Caught unhandled exception: TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\frames.js:41:9)
    at Connection.sendFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\connection.js:336:10)
    at ReceiverLink.Link.attach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:102:27)
    at ReceiverLink.Link._attemptReattach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:205:8)
    at null._onTimeout (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:193:10)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\frames.js:41:9)
    at Connection.sendFrame (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\connection.js:336:10)
    at ReceiverLink.Link.attach (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:102:27)
    at ReceiverLink.Link._attemptReattach (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:205:8)
    at null._onTimeout (c:\Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:193:10)
    at Timer.listOnTimeout (timers.js:92:15)
  nodemon bus.emit(exit) via SIGUSR2 +45m
  nodemon bus emit: exit +2ms
[nodemon] clean exit - waiting for changes before restart
```

**Comment by pierreca** [comment] 2016-02-26 07:44
at that point it looks like you are already disconnected and trying to reconnect. I'd like to see the part where you actually get disconnected. do you have this somewhere or can you regenerate it? We need to see if it's an authorization error, or something else.

Also, since we used token with an expiry date, having the wrong system type will influence the token lifecycle. can you check you're on the right timezone/date/time? (it's a long shot, but it has happened...)

**Comment by dmoreland** [comment] 2016-02-26 13:07
I didnt realise the code auto reconnected now, i have removed the peice
that i had that was performing it and it looks like the problem has gone
away will leave it running over the weekend to make sure though

**Comment by pierreca** [comment] 2016-02-26 18:06
ok, thanks for letting us know. I'll close the issue on Monday or Tuesday if I don't hear from you by then, but feel free to reopen it later if you find something.

**Comment by dmoreland** [comment] 2016-03-01 07:52
```
 amqp10:connection Rx: 0000001b02000000005315c00e0641700000066b40410053244540 +194ms
  amqp10:session processing frame(DispositionFrame): {"type":0,"channel":0,"role":true,"first":1643,"last":null,"settled":true,"state":{"descriptor":36},"batchable":null} +1ms
UDP EMIT:{"timestamp": "01 Mar 2016 07:48:36 +0000", "type": "WirelessMessage", "network": "Serial", "data": ["LVAL77.44"], "id": "AN"}
{"timestamp": "01 Mar 2016 07:48:36 +0000", "type": "WirelessMessage", "network": "Serial", "data": ["LVAL77.44"], "id": "AN"}
Message to parse:{"timestamp": "01 Mar 2016 07:48:36 +0000", "type": "WirelessMessage", "network": "Serial", "data": ["LVAL77.44"], "id": "AN"}
IOT Send:{"timestamp":"01 Mar 2016 07:48:36 +0000","type":"WirelessMessage","network":"Serial","data":["LVAL77.44"],"id":"AN"}
  amqp10:link:sender canSend(958,56) = true +2s
  amqp10:link:sender sending:  +1ms AmqpMessage {
  properties: { to: '/devices/1stHub/messages/events' },
  body: '{"timestamp":"01 Mar 2016 07:48:36 +0000","type":"WirelessMessage","network":"Serial","data":["LVAL77.44"],"id":"AN"}' }
  amqp10:framing Encoding performative: {"descriptor":20,"value":{"handle":{"typeName":"uint","value":1},"deliveryId":{"typeName":"uint","value":1644},"deliveryTag":{"type":"Buffer","data":[49,54,52,52]},"messageFormat":{"typeName":"uint","value":0},"settled":false,"more":false,"receiverSettleMode":{"typeName":"ubyte","value":null},"state":null,"resume":false,"aborted":false,"batchable":false,"encodeOrdering":["handle","deliveryId","deliveryTag","messageFormat","settled","more","receiverSettleMode","state","resume","aborted","batchable"]}} +3ms
  amqp10:framing sending frame: TransferFrame: {"type":"Buffer","data":[0,0,0,208,2,0,0,1,0,83,20,192,22,11,82,1,112,0,0,6,108,160,4,49,54,52,52,67,66,66,64,64,66,66,66,0,83,115,192,46,13,64,64,161,31,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,101,118,101,110,116,115,64,64,64,64,64,64,64,64,64,64,0,83,117,160,117,123,34,116,105,109,101,115,116,97,109,112,34,58,34,48,49,32,77,97,114,32,50,48,49,54,32,48,55,58,52,56,58,51,54,32,43,48,48,48,48,34,44,34,116,121,112,101,34,58,34,87,105,114,101,108,101,115,115,77,101,115,115,97,103,101,34,44,34,110,101,116,119,111,114,107,34,58,34,83,101,114,105,97,108,34,44,34,100,97,116,97,34,58,91,34,76,86,65,76,55,55,46,52,52,34,93,44,34,105,100,34,58,34,65,78,34,125]}: 000000d002000001005314c0160b5201700000066ca004313634344342424040424242005373c02e0d4040a11f2f646576696365732f3173744875622f6d657373616765732f6576656e747340404040404040404040005375a0757b2274696d657374616d70223a223031204d617220323031362030373a34383a3336202b30303030222c2274797065223a22576972656c6573734d657373616765222c226e6574776f726b223a2253657269616c222c2264617461223a5b224c56414c37372e3434225d2c226964223a22414e227d +3ms
  amqp10:connection Rx: 0000001b02000000005315c00e0641700000066c40410053244540 +74ms
  amqp10:session processing frame(DispositionFrame): {"type":0,"channel":0,"role":true,"first":1644,"last":null,"settled":true,"state":{"descriptor":36},"batchable":null} +2ms
  amqp10:client disconnecting +2s
  amqp10:link Force-detach for /devices/1stHub/messages/events_37cc1127-b577-4945-a2ce-21ad92a2fdb1. Current state: attached +4ms
  amqp10:link /devices/1stHub/messages/events_37cc1127-b577-4945-a2ce-21ad92a2fdb1:1: Transitioning from ATTACHED to DETACHED due to forceDetach +2ms
  amqp10:framing Encoding performative: {"descriptor":24,"value":[]} +2ms
  amqp10:framing sending frame: CloseFrame: {"type":"Buffer","data":[0,0,0,12,2,0,0,0,0,83,24,69]}: 0000000c0200000000531845 +2ms
  amqp10:connection Transitioning from OPENED to CLOSE_SENT due to sendClose +2ms
  amqp10:connection Rx: 0000000f02000000005318c0020140 +20ms
  amqp10:client disconnected +2ms
  amqp10:connection Transitioning from CLOSE_SENT to DISCONNECTED due to closeReceived +1ms
  azure-iot-device.Client sas token updated: SharedAccessSignatureUpdated needToReconnect: true +45m
  amqp10:client connecting to: amqps://XXX+4ms
  amqp10:transport:tls Connecting to 365agileiotdev.azure-devices.net:5671 via TLS +6ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +2ms
  amqp10:link Attempting to reattach /devices/1stHub/messages/devicebound_9bfaf3a3-fa3c-4994-8dbe-f7d47712f516 +127ms
  amqp10:link /devices/1stHub/messages/devicebound_9bfaf3a3-fa3c-4994-8dbe-f7d47712f516:0: Transitioning from DETACHED to ATTACHING due to sendAttach +3ms
  amqp10:link attach CH=1, Handle=0 +2ms
  amqp10:framing Encoding performative: {"descriptor":18,"value":{"name":"/devices/1stHub/messages/devicebound_9bfaf3a3-fa3c-4994-8dbe-f7d47712f516","handle":{"typeName":"uint","value":0},"role":true,"senderSettleMode":{"typeName":"ubyte","value":2},"receiverSettleMode":{"typeName":"ubyte","value":1},"source":{"descriptor":40,"address":"/devices/1stHub/messages/devicebound","durable":0,"expiryPolicy":"session-end","timeout":0,"dynamic":false},"target":{"descriptor":41,"address":"localhost","durable":0,"expiryPolicy":{"contents":"session-end"},"timeout":0,"dynamic":false},"unsettled":{},"incompleteUnsettled":false,"initialDeliveryCount":{"typeName":"uint","value":1},"maxMessageSize":{"typeName":"ulong","value":10000},"offeredCapabilities":null,"desiredCapabilities":null,"properties":{"com.microsoft:client-version":"azure-iot-device/1.0.1"},"encodeOrdering":["name","handle","role","senderSettleMode","receiverSettleMode","source","target","unsettled","incompleteUnsettled","initialDeliveryCount","maxMessageSize","offeredCapabilities","desiredCapabilities","properties"]}} +2ms
  amqp10:framing sending frame: AttachFrame: {"type":"Buffer","data":[0,0,1,26,2,0,0,1,0,83,18,208,0,0,1,10,0,0,0,14,161,73,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,100,101,118,105,99,101,98,111,117,110,100,95,57,98,102,97,102,51,97,51,45,102,97,51,99,45,52,57,57,52,45,56,100,98,101,45,102,55,100,52,55,55,49,50,102,53,49,54,67,65,80,2,80,1,0,83,40,192,65,11,161,36,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,100,101,118,105,99,101,98,111,117,110,100,67,163,11,115,101,115,115,105,111,110,45,101,110,100,67,66,193,1,0,64,193,1,0,64,64,64,0,83,41,192,32,7,161,9,108,111,99,97,108,104,111,115,116,67,163,11,115,101,115,115,105,111,110,45,101,110,100,67,66,193,1,0,64,193,1,0,66,82,1,128,0,0,0,0,0,0,39,16,64,64,193,55,2,163,28,99,111,109,46,109,105,99,114,111,115,111,102,116,58,99,108,105,101,110,116,45,118,101,114,115,105,111,110,161,22,97,122,117,114,101,45,105,111,116,45,100,101,118,105,99,101,47,49,46,48,46,49]}: 0000011a02000001005312d00000010a0000000ea1492f646576696365732f3173744875622f6d657373616765732f646576696365626f756e645f39626661663361332d666133632d343939342d386462652d663764343737313266353136434150025001005328c0410ba1242f646576696365732f3173744875622f6d657373616765732f646576696365626f756e6443a30b73657373696f6e2d656e644342c1010040c10100404040005329c02007a1096c6f63616c686f737443a30b73657373696f6e2d656e644342c1010040c101004252018000000000000027104040c13702a31c636f6d2e6d6963726f736f66743a636c69656e742d76657273696f6ea116617a7572652d696f742d6465766963652f312e302e31 +7ms
Caught unhandled exception: TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\frames.js:41:9)
    at Connection.sendFrame (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\connection.js:336:10)
    at ReceiverLink.Link.attach (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:102:27)
    at ReceiverLink.Link._attemptReattach (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:205:8)
    at null._onTimeout (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:193:10)
    at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by dmoreland** [comment] 2016-03-01 07:53
I was testing again last night and got the same error 58 minutes after starting the code on windows.

**Comment by dmoreland** [comment] 2016-03-01 08:10
I'm wondering if it might have something to do with sending a message while the token is being renewed ?

**Comment by pierreca** [comment] 2016-03-01 18:41
I have another idea: it looks like the reattach issue is on the receiver link. I set the reconnect policy of the amqp10 client to not reconnect, and the sender link to not reattach, but it looks like we're missing the bit that tells the receiver link to not attempt to reattach (looks like the global client policy might not override the link policy).

Looking at the place where the links are configured, line 44, either in `node/common/transport/amqp/lib/amqp.js` if you cloned the repository, or in `node_modules/azure-iot-amqp-base/lib/amqp.js`) if you are using the npm packages:

can you try adding this and let us know if this helps: 
```js
      reattach: {
        retries: 0,
        forever: false
      }
```
to the `receiverLink` policy object in . It's basically a copy/paste of what is in the senderLink policy section.

I'm trying to find a way to reproduce the problem in the meantime.

**Comment by pierreca** [comment] 2016-03-01 22:37
Using the sample and sending messages aggressively I managed to have a collision between token renewal and sending a message, and the behavior I see is as designed (meaning send fails with the appropriate error and execution goes on).

These lines are what differ from the logs I see on my end when renewing the token:
```  
amqp10:link Attempting to reattach /devices/1stHub/messages/devicebound_9bfaf3a3-fa3c-4994-8dbe-f7d47712f516 +127ms
  amqp10:link /devices/1stHub/messages/devicebound_9bfaf3a3-fa3c-4994-8dbe-f7d47712f516:0: Transitioning from DETACHED to ATTACHING due to sendAttach +3ms
  amqp10:link attach CH=1, Handle=0 +2ms
  amqp10:framing Encoding performative: {"descriptor":18,"value":{"name":"/devices/1stHub/messages/devicebound_9bfaf3a3-fa3c-4994-8dbe-f7d47712f516","handle":{"typeName":"uint","value":0},"role":true,"senderSettleMode":{"typeName":"ubyte","value":2},"receiverSettleMode":{"typeName":"ubyte","value":1},"source":{"descriptor":40,"address":"/devices/1stHub/messages/devicebound","durable":0,"expiryPolicy":"session-end","timeout":0,"dynamic":false},"target":{"descriptor":41,"address":"localhost","durable":0,"expiryPolicy":{"contents":"session-end"},"timeout":0,"dynamic":false},"unsettled":{},"incompleteUnsettled":false,"initialDeliveryCount":{"typeName":"uint","value":1},"maxMessageSize":{"typeName":"ulong","value":10000},"offeredCapabilities":null,"desiredCapabilities":null,"properties":{"com.microsoft:client-version":"azure-iot-device/1.0.1"},"encodeOrdering":["name","handle","role","senderSettleMode","receiverSettleMode","source","target","unsettled","incompleteUnsettled","initialDeliveryCount","maxMessageSize","offeredCapabilities","desiredCapabilities","properties"]}} +2ms
  amqp10:framing sending frame: AttachFrame: {"type":"Buffer","data":[0,0,1,26,2,0,0,1,0,83,18,208,0,0,1,10,0,0,0,14,161,73,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,100,101,118,105,99,101,98,111,117,110,100,95,57,98,102,97,102,51,97,51,45,102,97,51,99,45,52,57,57,52,45,56,100,98,101,45,102,55,100,52,55,55,49,50,102,53,49,54,67,65,80,2,80,1,0,83,40,192,65,11,161,36,47,100,101,118,105,99,101,115,47,49,115,116,72,117,98,47,109,101,115,115,97,103,101,115,47,100,101,118,105,99,101,98,111,117,110,100,67,163,11,115,101,115,115,105,111,110,45,101,110,100,67,66,193,1,0,64,193,1,0,64,64,64,0,83,41,192,32,7,161,9,108,111,99,97,108,104,111,115,116,67,163,11,115,101,115,115,105,111,110,45,101,110,100,67,66,193,1,0,64,193,1,0,66,82,1,128,0,0,0,0,0,0,39,16,64,64,193,55,2,163,28,99,111,109,46,109,105,99,114,111,115,111,102,116,58,99,108,105,101,110,116,45,118,101,114,115,105,111,110,161,22,97,122,117,114,101,45,105,111,116,45,100,101,118,105,99,101,47,49,46,48,46,49]}: 0000011a02000001005312d00000010a0000000ea1492f646576696365732f3173744875622f6d657373616765732f646576696365626f756e645f39626661663361332d666133632d343939342d386462652d663764343737313266353136434150025001005328c0410ba1242f646576696365732f3173744875622f6d657373616765732f646576696365626f756e6443a30b73657373696f6e2d656e644342c1010040c10100404040005329c02007a1096c6f63616c686f737443a30b73657373696f6e2d656e644342c1010040c101004252018000000000000027104040c13702a31c636f6d2e6d6963726f736f66743a636c69656e742d76657273696f6ea116617a7572652d696f742d6465766963652f312e302e31 +7ms
Caught unhandled exception: TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\frames.js:41:9)
    at Connection.sendFrame (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\connection.js:336:10)
    at ReceiverLink.Link.attach (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:102:27)
    at ReceiverLink.Link._attemptReattach (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:205:8)
    at null._onTimeout (c:\Source\365Agile.Messenger\365Agile.Messenger\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\link.js:193:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

Even without the policy modification that I was suggesting I don't see any link trying to reattach so I wonder if this might be an environmental failure of some sort that makes the amqp library try to reconnect this receiver link. I also tried to disconnect the network to provoke connection failure, and the connection failed and sent the appropriate error messages.

By any chance are you rejecting messages at any point? we had a bug recently that was fixed in the amqp10 library that would cause client disconnections when rejecting messages. Can you run npm update and make sure you're running on the latest versions of everything?

**Comment by pierreca** [comment] 2016-03-01 23:25
Alright I am now fairly sure we're missing a policy that prevent receivers from attempting to reattach. The fix is what I mentioned above. I stepped in the code and I can clearly see that some receiver links are allowed to reconnect. So I'd be really interested in seeing if adding that policy mentioned above fixes your issue.

**Comment by pierreca** [comment] 2016-03-02 00:46
Quick update: 
- I'm going to add code to set the policy to not reattach by default, this should have been configured that way by default.
- there is also a bug on the node-amqp10 side that leave the receiver links trying to reconnect when the client was disconnected and @noodlefrenzy will fix this too. 

@dmoreland we'll let you know when this is checked in and you should be good to go. I'm still a little bit worried that I could not repro the problem though. if you have any additional information you can share (how many messages are you sending, how often, if you're sending cloud-to-device messages at the same time, etc) that'd help :)

**Comment by pierreca** [comment] 2016-03-02 03:15
@dmoreland a fix was pushed to the develop branch. if you could pull develop, run your own test and then let us know if you still see the problem that'd be great :)

**Comment by dmoreland** [comment] 2016-03-02 15:09
Kind of new to node so it might take me a bit of time to work out how to swap from npm to the git binaries, i did make the code change above and its been running most of the day and i havent seen the issue re present. 

As for my usage im sending multi devices through a single gateway at around 1500-1800 messages an hour.

**Comment by pierreca** [comment] 2016-03-02 22:10
Understood.
With the current state of things and the fix, you have to monitor that the message has been enqueued properly and resend it yourself if it fell in a time during which the token was being renewed. we'll look at improving this and having message buffering during the downtime when renewing the token. 

In the meantime since the code is checked in develop and will make it to the next release, I will close the issue. feel free to reopen and comment if you run into it again.

**Closed by pierreca** 2016-03-02 22:10 UTC
Labels: bug
