### ISSUE TITLE
Different experience while registering new devices between c# and java

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#267] opened 2016-02-02 10:14 UTC
Hi,
When a new device is registered, C# creates the device in Enabled status. But, Java creates in Disabled status. Can you make the same between them to make multi platform code look similar?

**Comment by iluican** [comment] 2016-02-02 23:39
This is a duplicate of the following issue:

https://github.com/Azure/azure-iot-sdks/issues/225

The fix was already checked into the develop branch. If you are using the master branch you will see the changes after our next release (which should happen later today or tomorrow).

Thank you,
Ilie.

**Closed by iluican** 2016-02-02 23:39 UTC
Labels: enhancement
