### ISSUE TITLE
Python Device SDK issue

### ISSUE THREAD

**Issue by subhendu-de** [Azure/azure-iot-sdks#458] opened 2016-04-08 18:48 UTC
While I tried running ./build.sh for python, it failed in raspbian jessie for desktop as well as lite version. The same was successful in Debian Jessie 8 in Microsoft Azure VM.

Any pointers or similar issue faced by anyone?

**Comment by mregen** [comment] 2016-04-08 18:59
@subhendu-de, could you provide logs? The build was tested on raspbian with Python 2.7 with most recent bits.

**Comment by subhendu-de** [comment] 2016-04-09 15:38
It failed while I ran ./build.sh from ~/azure-iot-sdks/c/build_all/linux

Ca you tell me path of the log file which I can retrieve and give it to you. FYI that cmake folder is created in the home directory

**Comment by mregen** [comment] 2016-04-12 17:32
@subhendu-de I tested latest bits in master and the build seems to hang at [100%] with the mouse getting unresponsive. 

> Linking C executable iothub_client_sample_http_shared
Linking C executable iothub_client_sample_mqtt
[100%] Built target iothub_client_sample_http_shared
[100%] Built target iothub_client_sample_mqtt
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
python/test/CMakeFiles/iothub_client_mock.dir/build.make:54: recipe for target 'python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o' failed
make[2]: *** [python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o] Error 4
CMakeFiles/Makefile2:3513: recipe for target 'python/test/CMakeFiles/iothub_client_mock.dir/all' failed
make[1]: *** [python/test/CMakeFiles/iothub_client_mock.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library iothub_client.so
[100%] Built target iothub_client_python
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/azure-iot-sdks/build $ ^C
pi@raspberrypi:~/azure-iot-sdks/build $ `

I was able to workaround the issue by commenting out this line in `python/device/iothub_client_python/CMakeLists.txt`

> add_subdirectory(src)
\# add_subdirectory(test)

**Comment by mregen** [comment] 2016-04-13 12:30
@subhendu-de the root cause for the problem that I hit is low swap space. Please follow instructions: [Change swap file size on Raspbian](https://www.bitpi.co/2015/02/11/how-to-change-raspberry-pis-swapfile-size-on-rasbian/) and let mw know if this fixes the build.
If you still experience RPi restarts as of my experience the reason could also be the power supply.

**Comment by mregen** [comment] 2016-04-21 14:43
Closing as there was no follow up

**Closed by mregen** 2016-04-21 14:43 UTC
Labels: build issue, help wanted
