### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by rishikeshayre1310** [Azure/azure-iot-sdks#841] opened 2016-09-24 12:03 UTC
hello i am using raspberry pi 3 running on rasbian jessie swap size = 2048
i cloned the the sdk and did sudo ./setup.sh 
then sudo ./build.sh   i got following errors 
Scanning dependencies of target iothub_messaging_ll_ut_exe
[ 65%] Building C object iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o
virtual memory exhausted: Cannot allocate memory
iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/build.make:54: recipe for target 'iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o' failed
make[2]: *** [iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o] Error 1
CMakeFiles/Makefile2:5302: recipe for target 'iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/all' failed
make[1]: *** [iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jtanner-msft** [comment] 2016-09-26 21:23
Hi  @rishikeshayre1310,

  You are likely hitting a known issue that we are in the process of trying to get checked in.  To fix it yourself you’ll need to modify this line:
https://github.com/Azure/azure-iot-sdks/blob/master/c/build_all/linux/build.sh#L132 

  Please change MINVSPACE="1000000" to MINVSPACE="1500000" and it should work.

  If for some reason that still fails, then you can always modify this line:
https://github.com/Azure/azure-iot-sdks/blob/master/c/build_all/linux/build.sh#L129 

  And simply set it to CORES=1 to force it to use only a single core for the build.

  I hope that helps to unblock you.

Thanks,

~Jonathan

**Comment by rishikeshayre1310** [comment] 2016-09-27 06:18
hi @jtanner-msft 
I did the two changes as you mentioned above but still I am getting the same error .

**Comment by jtanner-msft** [comment] 2016-09-27 17:27
Hi @rishikeshayre1310,

  Please continue using the above commands and also include this command line switch:
./build.sh --skip-unittests  

  Thanks,

~Jonathan

**Comment by rishikeshayre1310** [comment] 2016-09-28 05:26
Hi @jtanner-msft  
as you said i did ./build.sh --skip-unittests and it showed no error but then i went to run my the python sample "iothub_client_sample.py" and i got the following errors

pi@raspberrypi:~/azure-iot-sdks/python/device/samples $ sudo python iothub_client_sample.py
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2]
IoT Hub for Python SDK Version: 1.0.15
Starting the IoT Hub Python sample...
    Protocol AMQP
    Connection string=HostName=technixiothub1.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=J6XB8AMkb9DY52oDg1eT7kU6xjUlHvsneAr1rOScUlM=
Info: IoT Hub SDK for C, version 1.0.15
Error: Time:Wed Sep 28 10:39:46 2016 File:/home/pi/azure-iot-sdks/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_CreateFromConnectionString Line:242 deviceId is not found
Error: Time:Wed Sep 28 10:39:46 2016 File:/home/pi/azure-iot-sdks/c/iothub_client/src/iothub_client.c Func:IoTHubClient_CreateFromConnectionString Line:231 IoTHubClient_LL_CreateFromConnectionString failed
Unexpected error IoTHubClient.IoTHubClient, IoTHubClientResult.ERROR from IoTHub

**Comment by rishikeshayre1310** [comment] 2016-09-28 07:15
hi @jtanner-msft 
as you said i did ./build --skip-unittests and i got no errors in the build. but when i run the python sample code "iothub_client_sample/py" i am getthing following errors

IoTHubClient.send_event_async accepted message [3] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [4] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: BUSY
Error: Time:Wed Sep 28 12:42:01 2016 File:/home/pi/azure-iot-sdks/c/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:576 Failure in HTTP communication: server reply code is 400
Info: HTTP Response:{"Message":"ErrorCode:DefaultStorageEndpointNotConfigured;BadRequest","ExceptionMessage":"Tracking ID:2f1a25197757451b9bacbfb9390165a8-G:10-TimeStamp:09/28/2016 07:12:00"}
Error: Time:Wed Sep 28 12:42:01 2016 File:/home/pi/azure-iot-sdks/c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:363 HTTP code was 400
Error: Time:Wed Sep 28 12:42:01 2016 File:/home/pi/azure-iot-sdks/c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:782 error in IoTHubClient_LL_UploadToBlob_step1
Error: Time:Wed Sep 28 12:42:01 2016 File:/home/pi/azure-iot-sdks/c/iothub_client/src/iothub_client.c Func:uploadingThread Line:710 unable to IoTHubClient_LL_UploadToBlob
Blob upload confirmation[1001] received for message with result = ERROR

**Comment by jtanner-msft** [comment] 2016-09-29 00:05
Hi @rishikeshayre1310, 

 Based upon the output that you have provided it looks like you are no longer facing a build issue, but are now seeing an issue when running one of the Python samples.  The error seems to happen after it sends its five messages and then goes into the ‘waiting’ state to see if there are any messages sent from the Cloud to the Device.

  Since that sounds like a new problem I’d suggest that we close this current issue and that you submit a new one on the python sample code running on the Rpi3 device.  It helps us to better track which areas are having a problem that way.

  I’ve been working with a colleague to see if we can reproduce the problem you are reporting but have not had any luck yet.  Out of curiosity, do you only see the problem with the HTTP transport?  Also have you tried AMQP or MQTT as well to see if you do or do not see the same type of errors then?

Thanks,

~Jonathan

**Comment by rishikeshayre1310** [comment] 2016-09-30 06:50
hello @jtanner-msft  
i am getting errors in all the 3 protocols .

**Comment by bluemurder** [comment] 2016-10-05 09:02
Hello,
I tried to build the C sdk on a Ubuntu 16.04 LTS, as described in [https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#linux](https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#linux).
Also in my case I cloned the repository and built with following commands:
```bash
git clone --recursive https://github.com/Azure/azure-iot-sdks
cd c/build_all/Linux
./setup.sh
./build.sh
```
Showing the errors below:
```
[ 67%] Building C object iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/build.make:62: recipe for target 'iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o' failed
make[2]: *** [iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o] Error 4
CMakeFiles/Makefile2:6351: recipe for target 'iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/all' failed
make[1]: *** [iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
With the command `./build.sh --use-websockets --skip-unittests` the build process is successful.

**Comment by chrit-msft** [comment] 2016-10-13 21:58
@rishikeshayre1310 & @bluemurder since the build issues have been resolved by using the --skip-unittests I will be closing this GitHub thread.

@rishikeshayre1310 for the python sample issues please open a new GitHub thread so we can properly track the different issues.

**Closed by chrit-msft** 2016-10-13 21:58 UTC
Labels: CSS, help wanted
