### ISSUE TITLE
Cannot open source file "provisioning_api.h"   CC3200 

### ISSUE THREAD

**Issue by ruthpozuelo** [Azure/azure-iot-sdks#576] opened 2016-05-23 17:55 UTC
Hi,

I am following the guide: Run a simple sample on the TI CC3200 launchpad board for C and getting the following error:
C:\TI\azure-iot-sdks\c\build_all\tirtos [master ≡ +2 ~2 -0 !]> C:\TI\xdctools_3_31_01_33_core\gmake.exe all
building packages...
making all: Mon May 23 19:36:59 WEDT 2016 ...
======== .interfaces [../../azure-c-shared-utility/build_all/tirtos] ========
.interfaces files complete: Mon May 23 19:37:00 WEDT 2016.
======== .libraries [../../azure-c-shared-utility/build_all/tirtos] ========
clem4 ../../adapters/httpapi_tirtos.c ...
"C:\TI\CC3200SDK_1.2.0\cc3200-sdk\simplelink\include\../user.h", line 51: fatal error: cannot open source file "provisioning_api.h"
1 catastrophic error detected in the compilation of "../../adapters/httpapi_tirtos.c".
Compilation terminated.

>> Compilation failure
gmake[1]: *** [package/lib/lib/common_sl/httpapi_tirtos.oem4] Error 1
xdctools_3_31_01_33_core\gmake.exe: *** [../../azure-c-shared-utility/build_all/tirtos,.libraries] Error 2
gmake: *** [all] Error 2

My products.mak is configured as follows:

#
#  ======== products.mak ========
#

##################### All platforms ####################

XDCTOOLS_INSTALLATION_DIR ?= C:/TI/xdctools_3_31_01_33_core

##################### TI-RTOS ####################

TIRTOS_INSTALLATION_DIR ?= C:/TI/tirtos_simplelink_2_14_01_20
BIOS_INSTALLATION_DIR   ?= $(TIRTOS_INSTALLATION_DIR)/products/bios_6_42_02_29
UIA_INSTALLATION_DIR    ?= $(TIRTOS_INSTALLATION_DIR)/products/uia_2_00_02_39
NS_INSTALLATION_DIR     ?= C:/TI/ns_1_10_00_00_eng

##################### TI-RTOS (CC3200) ####################

CC3200SDK_VERSION = 1.1.0
CCWARE_INSTALLATION_DIR    ?= $(TIRTOS_INSTALLATION_DIR)/products/CC3200_driverlib_1.1.0
CC3200SDK_INSTALLATION_DIR ?= C:/TI/CC3200SDK_1.2.0/cc3200-sdk

# Leave assignment empty to disable this toolchain
ti.targets.arm.elf.M4  ?= C:/TI/ti-cgt-arm_5.2.5

What can I do to solve the error?
Thanks in advance

**Comment by markrad** [comment] 2016-06-01 00:14
Hi @ruthpozuelo,

I have reproduced your problem locally. Further research revealed that TI have upgraded their SDK from 1.1 to 1.2 and this appears to have introduced the issue. It is not confined to the Azure IoT Hub SDK since I have seen others mention this issue in the TI forum such as here: https://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/p/499850/1871440.

Unfortunately the response is a little lacking on a reliable resolution. I will continue to research this issue using the SDK version 1.2. 

I can, however, provide you with a temporary circumvention to this issue. Instead of using the the SDK version 1.2, download and install the SDK version 1.1. You can download this from here: http://processors.wiki.ti.com/index.php/CC32xx_Release_Notes_1.1.0. I have checked that the code will still build as expected with this version of the SDK. 

Please let me know if you have any further questions.

_Mark Radbourne MSFT_

**Comment by ruthpozuelo** [comment] 2016-06-01 13:05
Hi Mark,

I read about it in the TI forum and did exactly that, and I managed to compile the sample_http.bin file. I haven't flashed it yet to the Launchpad to verify that is working, but hopefully it all works okey.

On the instructions it said that I had to update the date and time in the wifi file which I did, but why do I have to update the time? It will never be correct by the time I flash it to the Launchpad.

Thanks for your support, I will compile all the errors I found while following the tutorial and send it to you guys so you can update it. Hopefully it will help others.

Many thanks for the help,

Ruth



________________________________

**Comment by markrad** [comment] 2016-06-01 22:53
Hi @ruthpozuelo,

The date and time in that instance are used to validate the server's certificate. As long as it falls between the start and end of the certificate's valid time period you will be fine. 

I did manage to get the project to build against the 1.2 version of the SDK by forcing the additional directory to be searched for includes. Unfortunately, due to my lack of experience with the TI make system, I haven't found a clean way to do that which doesn't depend upon hard coded paths.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-06-03 17:50
Hi @ruthpozuelo,

If you have a requirement for the 1.2 version of the SDK then I have a fix for you. It has not been pushed to the code yet but it is a simple change that you can make for yourself for the time being.

In the file _azure-iot-sdks\c\build_all\tirtos\Makefile_ append the following to line 36 that sets the variable XDCPATH - 
```
;$(CC3200SDK_INSTALLATION_DIR)/simplelink_extlib/provisioninglib
```
 which will add the additionally required include directory to the search path. We will make this change shortly and push it to the repository.

_Mark Radbourne MSFT_

**Comment by ruthpozuelo** [comment] 2016-06-07 19:15
Hi @markrad ,

I added the code to the line 36:
`# Set XDCPATH to contain necessary repositories.
XDCPATH = $(NS_INSTALLATION_DIR)/packages;$(BIOS_INSTALLATION_DIR)/packages;$(TIRTOS_INSTALLATION_DIR)/packages;$(WOLFSSL_INSTALLATION_DIR)/tirtos/packages;$(NDK_INSTALLATION_DIR)/packages
export XDCPATH;$(CC3200SDK_INSTALLATION_DIR)/simplelink_extlib/provisioninglib`

But now I am getting a different error:
`C:\TI\azure-iot-sdks\c\build_all\tirtos [master ≡ +7 ~6 -0 !]> C:\ti\xdctools_3_31_01_33_core\gmake.exe all
building packages...
making all: Tue Jun 7 21:08:41 WEDT 2016 ...
======== .interfaces [../../azure-c-shared-utility/build_all/tirtos] ========
making package.mak (because of package.bld) ...
js: "C:/TI/azure-iot-sdks/c/build_all/tirtos/azureiot.bld", line 68: xdc.services.global.XDCException: xdc.PACKAGE_NOT_FOUND: can't locate the package 'ti.targets.arm.elf' along the path: 'C:/TI/xdctools_3_31_01_33_core/packages;../..;'. Ensure that the package path is set correctly.
gmake[1]: *** No rule to make target `package.mak', needed by `.interfaces'.  Stop.
xdctools_3_31_01_33_core\gmake.exe: *** [../../azure-c-shared-utility/build_all/tirtos,.interfaces] Error 2
gmake: *** [all] Error 2
`
Any ideas why?

/Ruth

**Comment by ruthpozuelo** [comment] 2016-06-07 19:34
Hi again @markrad,
I am also having problems when building the sdk1.1.0.
Everything compiles as it should, I falsh the simplesample_http.bin to my board, but nothing happens.

I am flashing this service pack version:
CC3100_CC3200_ServicePack_1.0.1.6-2.6.0.5

 Here is the compile messages from uniflash if it helps:
`[21:26:22] Begin Format operation.
[21:26:22] INFO: > Executing Operation: Connect
[21:26:24] INFO: setting break signal
[21:26:24] INFO: connection succeeded
[21:26:24] INFO: getting storage list
[21:26:24] INFO: > Executing Operation: Init
[21:26:24] INFO: reading version info
[21:26:24] INFO: DEVICE CC3200 ES1.33
[21:26:24] INFO: reading version info
[21:26:25] INFO: reading version info
[21:26:27] INFO: > Executing Operation: Format
[21:26:27] INFO: Erase storage SFLASH 
[21:26:28] INFO: erase storage succeeded
[21:26:28] INFO: erase storage completed
[21:26:28] INFO: > Executing Operation: Disconnect
[21:26:29] Operation Format returned. 
[21:26:37] Begin ServicePackProgramming operation.
[21:26:38] INFO: > Executing Operation: Connect
[21:26:40] INFO: setting break signal
[21:26:41] INFO: detecting FTDI for device reset
[21:26:42] INFO: connection succeeded
[21:26:42] INFO: getting storage list
[21:26:43] INFO: > Executing Operation: ServicePackProgramming
[21:26:43] INFO: Path to the service pack file: C:/TI/CC3100_CC3200_ServicePack_1.0.1.6-2.6.0.5/servicepack_1.0.1.6-2.6.0.5.bin
[21:26:43] INFO: reading version info
[21:26:43] INFO: CC3200R Device detected.
[21:26:43] INFO: NWP/MAC/PHY Version from Service Pack: 
[21:26:43] INFO:  NWP Patch version: 2.6.0.5
[21:26:43] INFO:  MAC Patch version: 1.4.0.1
[21:26:43] INFO:  PHY Patch version: 1.0.3.34
[21:26:43] INFO: reading version info
[21:26:43] INFO: DEVICE CC3200 ES1.33
[21:26:43] INFO: reading version info
[21:26:44] INFO: reading version info
[21:26:46] INFO: Downloading file "/sys/servicepack.ucf" with size 25820
[21:26:48] INFO: 

New Token is 0x891B421A
[21:26:48] INFO: Download complete
[21:26:48] INFO: > Executing Operation: Disconnect
[21:26:48] Operation ServicePackProgramming returned. 
[21:27:16] Begin AddFile operation.
[21:27:17] Operation AddFile returned. 
[21:28:03] Begin Program operation.
[21:28:03] INFO: > Executing Operation: Connect
[21:28:05] INFO: setting break signal
[21:28:06] INFO: detecting FTDI for device reset
[21:28:08] INFO: connection succeeded
[21:28:08] INFO: getting storage list
[21:28:08] INFO: > Executing Operation: Init
[21:28:08] INFO: reading version info
[21:28:08] INFO: DEVICE CC3200 ES1.33
[21:28:08] INFO: reading version info
[21:28:09] INFO: reading version info
[21:28:11] INFO: > Executing Operation: Program
[21:28:11] INFO: > File name: /sys/mcuimg.bin, Update: true, Erase: true
[21:28:11] INFO: > Erase File: /sys/mcuimg.bin
[21:28:11] INFO: erasing file "/sys/mcuimg.bin"
[21:28:11] INFO: deleting file "/sys/mcuimg.bin"
[21:28:11] INFO: erase file completed
[21:28:11] INFO: > Size of file = 219544
[21:28:11] INFO: > Update File: /sys/mcuimg.bin
[21:28:11] INFO: Downloading file "/sys/mcuimg.bin" with size 219544
[21:28:18] INFO: 

New Token is 0x0
[21:28:18] INFO: Download complete
[21:28:18] INFO: Verifying Data...
[21:28:18] INFO: get file
[21:28:23] INFO: Done. Reading 219544  bytes
[21:28:23] INFO: 

Verification OK
[21:28:24] INFO: > Updated Token value: 0x0
[21:28:24] INFO: > File name: /cert/ca.pem, Update: false, Erase: false
[21:28:24] INFO: > File name: /cert/client.pem, Update: false, Erase: false
[21:28:24] INFO: > File name: /cert/private.key, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/macadd.bin, Update: false, Erase: true
[21:28:24] INFO: > Erase File: /sys/macadd.bin
[21:28:24] INFO: erasing file "/sys/macadd.bin"
[21:28:24] INFO: deleting file "/sys/macadd.bin"
[21:28:24] INFO: erase file completed
[21:28:24] INFO: > File name: /sys/mode.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/ipcfg.ini, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/ap.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/devname.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/mdns.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/dhcpsrv.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/httpsrv.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/pref.net, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/smartconfigkeys.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/stacfg.ini, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/p2p.cfg, Update: false, Erase: false
[21:28:24] INFO: > File name: /sys/pmcfg.ini, Update: false, Erase: false
[21:28:24] INFO: > File name: /cert/ms.der, Update: true, Erase: true
[21:28:24] INFO: > Erase File: /cert/ms.der
[21:28:24] INFO: erasing file "/cert/ms.der"
[21:28:24] INFO: deleting file "/cert/ms.der"
[21:28:24] INFO: erase file completed
[21:28:24] INFO: > Size of file = 891
[21:28:24] INFO: > Update File: /cert/ms.der
[21:28:24] INFO: Downloading file "/cert/ms.der" with size 891
[21:28:24] INFO: 

New Token is 0x0
[21:28:24] INFO: Download complete
[21:28:24] INFO: Verifying Data...
[21:28:24] INFO: get file
[21:28:24] INFO: Done. Reading 891  bytes
[21:28:24] INFO: 

Verification OK
[21:28:25] INFO: > Updated Token value: 0x0
[21:28:25] INFO: > Executing Operation: Disconnect
[21:28:25] Operation Program returned. 
`

**Comment by ruthpozuelo** [comment] 2016-06-09 10:33
Hi @markrad 
I have created a tutorial on how to connect to the hub using SDK1.1.0 in you tube. I post it here in case it helps others:
https://www.youtube.com/watch?v=EpgOghMBuj0
/Ruth

**Comment by markrad** [comment] 2016-06-09 23:25
Hi @ruthpozuelo,

No I'm not sure why you would see that error. I'm a little reluctant to dig into it too much at this time since I know that the fix to the makefiles is currently in code review and will likely be in the develop branch shortly. If you are still encountering the same error after the fix is committed we could research it further at that time.

Thanks.

_Mark Radbourne MSFT_

**Comment by ruthpozuelo** [comment] 2016-06-10 06:57
Hi @markrad,

No problem, I don't have a requirement for SDk1.2.0. I just thought i give it a try and let you know if it works.

Many thanks for you support,
Ruth


________________________________

**Comment by markrad** [comment] 2016-07-05 23:27
Hi @ruthpozuelo, 
A fix has been developed and checked in for your build issue. It should be available in the master branch now. Should you have any additional problems please feel free to reopen this thread.

_Mark Radbourne MSFT_

**Closed by markrad** 2016-07-05 23:27 UTC
Labels: CSS, help wanted
