### ISSUE TITLE
Microsoft.Azure.Devices.Client in an Azure Function

### ISSUE THREAD

**Issue by jantielens** [Azure/azure-iot-sdks#978] opened 2016-11-22 09:00 UTC
I'm trying to connect to an IoT Hub from an Azure Function (that acts as cloud API for demo purposes). I've added the NuGet package in the project.json file. But when I execute the function, I get an exception:

`Could not load file or assembly 'Validation, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7' or one of its dependencies. The system cannot find the file specified.`

I tried adding the Validation NuGet package manually to the project.json as well, but no change.

Any ideas?
Thanks!
Jan

**Comment by anhashia** [comment] 2016-11-28 19:12
Investigating !

**Comment by anhashia** [comment] 2016-12-02 02:25
Hi @jantielens 
Issue seems specific to Azure Function Service environment. Checking with Azure Function team on this issue.

**Comment by anhashia** [comment] 2016-12-03 02:13
Hi @jantielens 
Below is the root cause and workaround for your issue

**Root Cause**
`````
2016-11-18T22:59:32.594 Error in sample System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Validation, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7' or one of its dependencies. The system cannot find the file specified.
   at PCLCrypto.MacAlgorithmProvider.CreateHash(Byte[] keyMaterial)
   at Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.Sign(String requestString, String key)
   at Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.BuildSignature(String keyName, String key, String target, TimeSpan timeToLive)
   at Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.ToSignature()
`````````
Looks like PCLCrypto tries to load older version of validation assembly which doesn't exist in Azure Service Environment because it uses newer version Validation (>= 2.2.8) 
The reason you don't see this issue in console application is because of **bindingredirect** https://msdn.microsoft.com/en-us/library/eftw1fys(v=vs.110).aspx element
````
<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
````
Currently, it seems Azure function **doesn't** support `<bindingRedirect>` element and hence it doesn't work in Azure Function App Service environment.

So **workaround** would be to force PCLCrypto to use older version of **validation.dll**
Below is the workaround for the issue

**Workaround**
Use following in your **project.json**. This will install **latest** version of the available Azure IoT SDK assemblies but will install older version of validation.dll

```````
{
"frameworks": {
    "net46":{
        "dependencies": {
            "Microsoft.Azure.Devices.Client": "1.1.1",
             "Microsoft.Azure.Devices.Shared": "1.0.2",
             "Validation": "2.0.6.15003"
                    }
                }
        }
}
````````````

**Comment by anhashia** [comment] 2016-12-03 02:14
Linking to https://github.com/Azure/azure-webjobs-sdk-script/issues/1017

**Comment by anhashia** [comment] 2016-12-09 23:32
Closing this. Please re-activate if you have any further questions on this. Thanks !

**Closed** 2016-12-12 23:24 UTC
Labels: CSS, help wanted
