### ISSUE TITLE
Error when loading assembly Microsoft.Azure.Devices.Shared due to strongly-named assembly required

### ISSUE THREAD

**Issue by boontje** [Azure/azure-iot-sdks#1022] opened 2016-12-08 05:30 UTC
I get this error in my project.
Could not load file or assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

This is also reproduced when using the "Send a cloud-to-device message" example app from 
https://docs.microsoft.com/nl-nl/azure/iot-hub/iot-hub-csharp-csharp-c2d.

**Comment by jaideepkekre** [comment] 2016-12-08 10:27
Hi 
I also got the same error , looks like a bad dependency on Microsoft.Azure.Devices.Shared .

**Comment by jaideepkekre** [comment] 2016-12-08 10:42
Duplicate of https://github.com/Azure/azure-iot-sdks/issues/1014

**Comment by BertKleewein** [comment] 2016-12-08 17:22
fix is coming soon.

**Comment by BertKleewein** [comment] 2016-12-08 19:57
This is fixed in Microsoft.Azure.Devices v 1.1.3 (if you're using the service SDK) and Microsoft.Azure.Devices.Client v  1.1.2 (if you're using the device SDK).  I'm going to close this issue for now, please re-activate (or open a new issue) if you still have problems.

**Closed by BertKleewein** 2016-12-08 19:57 UTC
