### ISSUE TITLE
[Python][Linux]Send D2C message Python / MQTT unreliable

### ISSUE THREAD

**Issue by taunusflieger** [Azure/azure-iot-sdks#642] opened 2016-06-21 08:30 UTC
I’m using the Python SDK to send message to to the cloud using MQTT. I see a large amount of ERROR in the result in send_confirmation_callback(message, result, user_context) (see log dump below). Is there any way to get a more detailed error description? I know that the network connection is not the problem, as I’m sending at the same time successful the data to another service. Any thoughts how to further debug? I need more information than just ERROR as a result.

2016-06-21 10:01:07,381 - __main__ - INFO - Confirmation[282] received for message with result = ERROR
2016-06-21 10:01:24,161 - __main__ - INFO - Confirmation[283] received for message with result = OK
2016-06-21 10:01:40,915 - __main__ - INFO - Confirmation[284] received for message with result = OK
2016-06-21 10:01:57,074 - __main__ - INFO - Confirmation[285] received for message with result = OK
2016-06-21 10:02:13,829 - __main__ - INFO - Confirmation[286] received for message with result = OK
2016-06-21 10:02:30,111 - __main__ - INFO - Confirmation[287] received for message with result = OK
2016-06-21 10:02:46,950 - __main__ - INFO - Confirmation[288] received for message with result = OK
2016-06-21 10:02:52,000 - __main__ - INFO - Confirmation[281] received for message with result = ERROR
2016-06-21 10:03:03,608 - __main__ - INFO - Confirmation[289] received for message with result = OK
2016-06-21 10:03:19,909 - __main__ - INFO - Confirmation[290] received for message with result = OK
2016-06-21 10:03:36,155 - __main__ - INFO - Confirmation[291] received for message with result = OK
2016-06-21 10:03:52,758 - __main__ - INFO - Confirmation[292] received for message with result = OK
2016-06-21 10:04:08,976 - __main__ - INFO - Confirmation[293] received for message with result = OK
2016-06-21 10:04:25,636 - __main__ - INFO - Confirmation[294] received for message with result = OK
2016-06-21 10:04:58,755 - __main__ - INFO - Confirmation[296] received for message with result = ERROR
2016-06-21 10:05:15,473 - __main__ - INFO - Confirmation[297] received for message with result = OK
2016-06-21 10:05:31,943 - __main__ - INFO - Confirmation[298] received for message with result = OK
2016-06-21 10:05:48,040 - __main__ - INFO - Confirmation[299] received for message with result = OK
2016-06-21 10:06:04,176 - __main__ - INFO - Confirmation[300] received for message with result = OK
2016-06-21 10:06:20,354 - __main__ - INFO - Confirmation[301] received for message with result = OK
2016-06-21 10:06:36,552 - __main__ - INFO - Confirmation[302] received for message with result = OK
2016-06-21 10:06:44,001 - __main__ - INFO - Confirmation[295] received for message with result = ERROR
2016-06-21 10:06:52,781 - __main__ - INFO - Confirmation[303] received for message with result = OK
2016-06-21 10:07:08,663 - __main__ - INFO - Confirmation[304] received for message with result = OK
2016-06-21 10:07:25,640 - __main__ - INFO - Confirmation[305] received for message with result = OK
2016-06-21 10:07:42,089 - __main__ - INFO - Confirmation[306] received for message with result = OK
2016-06-21 10:07:58,107 - __main__ - INFO - Confirmation[307] received for message with result = OK
2016-06-21 10:08:46,283 - __main__ - INFO - Confirmation[310] received for message with result = ERROR
2016-06-21 10:09:02,864 - __main__ - INFO - Confirmation[311] received for message with result = OK
2016-06-21 10:09:19,163 - __main__ - INFO - Confirmation[312] received for message with result = OK
2016-06-21 10:09:35,511 - __main__ - INFO - Confirmation[313] received for message with result = OK
2016-06-21 10:09:51,929 - __main__ - INFO - Confirmation[314] received for message with result = OK
2016-06-21 10:10:08,328 - __main__ - INFO - Confirmation[315] received for message with result = OK
2016-06-21 10:10:15,000 - __main__ - INFO - Confirmation[308] received for message with result = ERROR
2016-06-21 10:10:24,362 - __main__ - INFO - Confirmation[316] received for message with result = OK
2016-06-21 10:10:32,001 - __main__ - INFO - Confirmation[309] received for message with result = ERROR
2016-06-21 10:10:40,403 - __main__ - INFO - Confirmation[317] received for message with result = OK
2016-06-21 10:10:55,901 - __main__ - INFO - Confirmation[318] received for message with result = OK
2016-06-21 10:11:11,888 - __main__ - INFO - Confirmation[319] received for message with result = OK
2016-06-21 10:11:27,765 - __main__ - INFO - Confirmation[320] received for message with result = OK
2016-06-21 10:11:43,486 - __main__ - INFO - Confirmation[321] received for message with result = OK
2016-06-21 10:11:59,403 - __main__ - INFO - Confirmation[322] received for message with result = OK
2016-06-21 10:12:31,753 - __main__ - INFO - Confirmation[324] received for message with result = ERROR
2016-06-21 10:12:47,864 - __main__ - INFO - Confirmation[325] received for message with result = OK
2016-06-21 10:13:03,595 - __main__ - INFO - Confirmation[326] received for message with result = OK
2016-06-21 10:13:19,945 - __main__ - INFO - Confirmation[327] received for message with result = OK
2016-06-21 10:13:35,938 - __main__ - INFO - Confirmation[328] received for message with result = OK
2016-06-21 10:13:52,197 - __main__ - INFO - Confirmation[329] received for message with result = OK
2016-06-21 10:14:08,376 - __main__ - INFO - Confirmation[330] received for message with result = OK
2016-06-21 10:14:17,001 - __main__ - INFO - Confirmation[323] received for message with result = ERROR
2016-06-21 10:14:24,385 - __main__ - INFO - Confirmation[331] received for message with result = OK
2016-06-21 10:14:40,635 - __main__ - INFO - Confirmation[332] received for message with result = OK
2016-06-21 10:14:57,302 - __main__ - INFO - Confirmation[333] received for message with result = OK
2016-06-21 10:15:13,617 - __main__ - INFO - Confirmation[334] received for message with result = OK
2016-06-21 10:15:29,854 - __main__ - INFO - Confirmation[335] received for message with result = OK
2016-06-21 10:15:45,968 - __main__ - INFO - Confirmation[336] received for message with result = OK
2016-06-21 10:16:02,143 - __main__ - INFO - Confirmation[337] received for message with result = OK
2016-06-21 10:16:34,892 - __main__ - INFO - Confirmation[339] received for message with result = ERROR
2016-06-21 10:16:50,963 - __main__ - INFO - Confirmation[340] received for message with result = OK
2016-06-21 10:17:07,074 - __main__ - INFO - Confirmation[341] received for message with result = OK
2016-06-21 10:17:23,496 - __main__ - INFO - Confirmation[342] received for message with result = OK
2016-06-21 10:17:40,258 - __main__ - INFO - Confirmation[343] received for message with result = OK
2016-06-21 10:17:56,170 - __main__ - INFO - Confirmation[344] received for message with result = OK
2016-06-21 10:18:12,514 - __main__ - INFO - Confirmation[345] received for message with result = OK
2016-06-21 10:18:20,000 - __main__ - INFO - Confirmation[338] received for message with result = ERROR
2016-06-21 10:18:28,145 - __main__ - INFO - Confirmation[346] received for message with result = OK
2016-06-21 10:18:44,890 - __main__ - INFO - Confirmation[347] received for message with result = OK
2016-06-21 10:19:01,343 - __main__ - INFO - Confirmation[348] received for message with result = OK
2016-06-21 10:19:17,568 - __main__ - INFO - Confirmation[349] received for message with result = OK
2016-06-21 10:19:34,475 - __main__ - INFO - Confirmation[350] received for message with result = OK
2016-06-21 10:19:50,826 - __main__ - INFO - Confirmation[351] received for message with result = OK
2016-06-21 10:20:23,292 - __main__ - INFO - Confirmation[353] received for message with result = ERROR
2016-06-21 10:20:40,128 - __main__ - INFO - Confirmation[354] received for message with result = OK
2016-06-21 10:20:56,449 - __main__ - INFO - Confirmation[355] received for message with result = OK

**Comment by jtanner-msft** [comment] 2016-06-21 22:18
So I can see if I can reproduce the issue, can you please comment on what platform or device you are running on when you see the error happen?
Also, if you try one of the other transport protocols like http or amqp, do you still see the problem?  Or is it only with MQTT?

Alternatively, if you try the C sample with MQTT on the device does that work okay?

**Comment by taunusflieger** [comment] 2016-06-22 07:21
Thanks for looking into this. The device is a Raspberry PI 3 running Debian Jessie. 
Running this interactive / in the debugger I see the following additional error messages
`Error: Time:Wed Jun 22 09:00:36 2016 File:/home/pi/src/azure-iot-sdks/c/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_send Line:449 Failure: sending socket failed.

Error: Time:Wed Jun 22 09:00:36 2016 File:/home/pi/src/azure-iot-sdks/c/azure-c-shared-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:118 Error in xio_send.

Error: Time:Wed Jun 22 09:00:36 2016 File:/home/pi/src/azure-iot-sdks/c/azure-c-shared-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:681 Error in write_outgoing_bytes.
680: Failure sending control packet data`

I’ve tested the same code with AMQP - here I don’t see these errors - seems to be related to MQTT

**Comment by jtanner-msft** [comment] 2016-06-22 23:37
You might want to sync to the latest 'Develop' branch instead for testing as I'm currently seeing a build issue with the current master branch for Python.  If that does resolve your problem please let us know.
Thanks,

**Comment by taunusflieger** [comment] 2016-06-23 08:03
I’m not able to build the develop branch. I get the following error:

pi@raspilogger:~/src/azure-iot-sdks/python/build_all/linux $ ./build.sh --build-python 3.4
~/src/azure-iot-sdks/c/cmake/iotsdk_linux ~/src/azure-iot-sdks
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:69 (add_subdirectory):
  The source directory

    /home/pi/src/azure-iot-sdks/c/azure-c-shared-utility

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:70 (add_subdirectory):
  The source directory

    /home/pi/src/azure-iot-sdks/c/azure-uamqp-c

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:71 (add_subdirectory):
  The source directory

    /home/pi/src/azure-iot-sdks/c/azure-umqtt-c

  does not contain a CMakeLists.txt file.


-- Looking for __x86_64__
-- Looking for __x86_64__ - not found
-- Looking for __i386__
-- Looking for __i386__ - not found
-- Looking for __arm__
-- Looking for __arm__ - found
-- iothub architecture: ARM
CMake Error at iothub_client/tests/iothubclient_ll_unittests/CMakeLists.txt:21 (build_test_artifacts):
  Unknown CMake command "build_test_artifacts".

**Comment by mregen** [comment] 2016-06-24 06:18
@taunusflieger looks like missing submodules. Please run the follwoing commands:

> git submodule init --recursive

or 

> git submodule update --init --recursive

**Comment by jtanner-msft** [comment] 2016-06-27 22:29
Have you been able to build and test with the submodules present?
You can also just create a new develop branch clone using:
git clone -b develop --recursive https://github.com/Azure/azure-iot-sdks.git azure-iot-develop

If you don't already have a location called azure-iot-develop it will create it and should pull down everything you need as part of a new clone.

**Comment by taunusflieger** [comment] 2016-06-29 07:26
Sorry for the late response. Yes I was able to build. I’m now using  IoT Hub SDK for C, version 1.0.9. Still getting the same error on a regular basis:

Error: Time:Wed Jun 29 09:20:50 2016 File:/home/pi/src/azure-iot-sdks/c/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_send Line:456 Failure: sending socket failed. errno=107 (Transport endpoint is not connected).
Error: Time:Wed Jun 29 09:20:50 2016 File:/home/pi/src/azure-iot-sdks/c/azure-c-shared-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:303 Error in xio_send.
Error: Time:Wed Jun 29 09:20:50 2016 File:/home/pi/src/azure-iot-sdks/c/azure-c-shared-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:879 Error in write_outgoing_bytes.
878: Failure sending control packet data

**Comment by jtanner-msft** [comment] 2016-07-07 21:40
Hi taunusflieger,

  I’ve tried to repro the problem you had reported on both an Ubuntul 16.04 VM, and on my Rpi2 device running Raspbian, both running the current development branch of the Azure-IoT-Sdk.  I’ve set the message count for the iothub_client_sample.py up to 500, but all of them seem to get delivered without any problems using the MQTT transport.  I’ve tried running the test multiple times in a row and don’t see any errors or missed messages.  The IoT Hub that I’m using for the testing is an S1 – Standard tier, with a single unit.  Were you maybe using a ‘Free’ tier IoT Hub for your testing?

  At the moment I’d suggest checking again with a clean git clone of the SDK.  If you are still seeing the issue, if you can try running the test on a different network environment to see if that changes what you are seeing.  Maybe a particular router or firewall on your current network doesn’t like MQTT packets for some reason?

  Please let me know if you no longer are seeing the issue, or if any of my suggestions have helped.  Thanks.

**Comment by jtanner-msft** [comment] 2016-07-13 17:04
Closing as I haven't seen any response.  If you still see this with the latest development branch please let us know.

**Closed by jtanner-msft** 2016-07-13 17:04 UTC
Labels: CSS, help wanted
