### ISSUE TITLE
[C][MQTT] sample daemon be killed ????

### ISSUE THREAD

**Issue by chaolong0129** [Azure/azure-iot-sdks#740] opened 2016-07-28 03:16 UTC
Hi,
   I ran the iothub_client_sample_mqtt daemon and test it overnight. In the morning, I used the Device_Explorer utility to check my device status.  I found my device status was disconnected. I checked my sample daemon and it was killed and no any odd-debug messages. I feel confused. Which situation could it cause the problem ? Is my network not-stable ?
Just only one clue "MQTT_CLIENT_NO_PING_RESPONSE", it means my sample daemon does not receive the ping response. It should not kill my daemon. Could I set it to retry because it retry in normal ?

-- Log --
./c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt
Info: IoT Hub SDK for C, version 1.0.11
...
Error: Time:Thu Jul 28 08:13:47 2016 File:/home/test/Project/test/azure-iot-sdks/c/iothub_client/src/iothubtransportmqtt.c Func:MqttOpCompleteCallback Line:436 Mqtt Ping Response was not encountered.  Reconnecting device...
-> 08:13:47 CONNECT: ...
<- 08:13:47 CONNACK: 0x20 0x02 0x01 0x00
-> 08:13:47 SUBSCRIBE: ...
<- 08:13:47 SUBACK: 0x90 0x03 0x00 0x18 0x01
-> 08:17:38 PINGREQ: 0xc0 0x00
<- 08:17:38 PINGRESP: 0xd0 0x00
-> 08:21:29 PINGREQ: 0xc0 0x00
Error: Time:Thu Jul 28 08:23:00 2016 File:/home/test/Project/test/azure-iot-sdks/c/iothub_client/src/iothubtransportmqtt.c Func:MqttOpCompleteCallback Line:436 Mqtt Ping Response was not encountered.  Reconnecting device...
-> 08:23:00 CONNECT: ...
<- 08:23:01 CONNACK: 0x20 0x02 0x01 0x00
-> 08:23:01 SUBSCRIBE: ...
<- 08:23:01 SUBACK: 0x90 0x03 0x00 0x19 0x01

----------

**Comment by jtanner-msft** [comment] 2016-08-02 21:51
Thank you for reporting the issue.  I'll see if I can reproduce the issue locally and let you know if I have any other questions or suggestions.

**Comment by jtanner-msft** [comment] 2016-08-10 23:05
Hello,

  I was reviewing your comments further and believe I’ll need a little more information before I can attempt to reproduce the problem you saw for investigation locally.

  Based upon the data you provided I can see that you were using C, MQTT and some version of Linux.

  Can you please clarify what version of Linux you were using and what device you might have been running on?

  Also what client test did you launch for your test?  Did you just use the default 4 packets to send, or did you increase it slightly or make any other changes?

  Have you tried running the test again with the latest master branch?  I know that there were some changes being made to the MQTT transport back at the time you reported this problem.

Thanks,

**Comment by jtanner-msft** [comment] 2016-08-17 17:52
Hi @chaolong0129, 

  Since I haven’t seen any response or update for a week now I’m going to close the issue at this time.  If you are still seeing the odd behavior and can provide the details I had asked for please re-activate the issue and add that information.

Thanks,

**Closed by jtanner-msft** 2016-08-17 17:52 UTC
Labels: CSS, investigation-required

**Comment by chaolong0129** [comment] 2016-08-18 02:25
Hi Jtanner,
    Sorry, I forgot to reply. I run it on my Hyper-V. I test it with new release version and new version seems more stable. I already ran it on Monday and it still works well now.

    Azure-IOT-SDKs Test
   -------------------------------
    OS : Ubuntu 14.04,  4.2.0-42-generic
    git branch  : 2016-07-15-release
    Duration : 1 day
    Test Program : iothub_client_sample_mqtt
    Test Result : Fail
   -------------------------------
    OS : Ubuntu 14.04, 4.2.0-42-generic
    git branch  : release-20160812
    Duration : 4 days
    Test Program : iothub_client_sample_mqtt
    Test status : keep going.
   In current, it works well.
  --------------------------------
  
Thanks your help,
