### ISSUE TITLE
ReadDeviceToCloudMessages.js not working - Get started with Azure IoT Hub for Node.js

### ISSUE THREAD

**Issue by alianal89** [Azure/azure-iot-sdks#984] opened 2016-11-22 15:54 UTC
At a command-prompt in the readdevicetocloudmessages folder,when I run the command to begin monitoring IoT hub, 
node ReadDeviceToCloudMessages.js

on Command Prompt, I can see only the following message
Created partition receiver: 1
Created partition receiver: 0

Unlike as shown in the tutorial where we can see that 
Message received is also displayed.

At my command prompt, it is not the case and after partition receiver :0 , it seems that command prompt is stuck and I cannot type any further commands even after waiting for few minutes. I have checked the code in ReadDeviceToCloudMessages.js, it looks fine.

Could you please help me in identifying what caould be wrong.

In a new command prompt if I run  node SimulatedDevice.js, then although message is shown but status says that message is Enqued instead of message sent

**Comment by anhashia** [comment] 2016-11-28 19:08
Investigating !

**Comment by anhashia** [comment] 2016-12-07 00:04
Looking into the issue.

**Comment by anhashia** [comment] 2016-12-07 20:05
Hi @alianal89 
I am not able to reproduce the issue locally. Below are my local reproduction steps for your reference. You can try with these steps with the latest available code.

a.) Use node\device\samples\simple_sample_device.js to send D2C messages after putting the valid device connection string
b.)  Create **ReadDeviceToCloudMessages.js** as per https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted. Replace connectionString with valid Hub connection string

- Run **simple_sample_device.js** to send messages
- Run **ReadDeviceToCloudMessages.js** to receive messages

**Log: send side**
``````
Client connected
Sending message: {"deviceId":"myFirstDevice","windSpeed":11.596172165125608}
send status: MessageEnqueued
Sending message: {"deviceId":"myFirstDevice","windSpeed":12.24133980460465}
send status: MessageEnqueued
Sending message: {"deviceId":"myFirstDevice","windSpeed":13.67323022056371}
send status: MessageEnqueued
````````

**Log: receive side**
````````
node --debug-brk=17366 --nolazy device\samples\ReadDeviceToCloudMessages.js 
Debugger listening on port 17366
Created partition receiver: 0
Created partition receiver: 1

Message received: 
{"deviceId":"myFirstDevice","windSpeed":11.596172165125608}
Message received: 
{"deviceId":"myFirstDevice","windSpeed":12.24133980460465}
Message received: 
{"deviceId":"myFirstDevice","windSpeed":13.67323022056371}
``````````

**Comment by anhashia** [comment] 2016-12-28 00:09
Closing. Please re-activate if you still are having issues. Thanks !

**Closed by anhashia** 2016-12-28 00:09 UTC
Labels: CSS, help wanted
