### ISSUE TITLE
remote_monitoring CMakeLists.txt File Missing

### ISSUE THREAD

**Issue by swarlyyy** [Azure/azure-iot-sdks#718] opened 2016-07-20 00:05 UTC
Hi!

When trying to run the remote_monitoring program with the command below, I get an error:
Command: "sudo ~/cmake/serializer/samples/remote_monitoring/remote_monitoring"
Error: "sudo: /home/pi/cmake/serializer/samples/remote_monitoring/remote_monitoring: command not found"

I tried navigating to the directory and running cmake directly. The directory that appears to be the right one is:
"/home/pi/cmake/serializer/samples/remote_monitoring/**CMakeFiles**/remote_monitoring.dir"

But inside that directory is no CMakeLists.txt. I get the error:
Command: "sudo cmake remote_monitoring.dir"
Error: "CMake Error: The source directory "/home/pi/cmake/serializer/samples/remote_monitoring/CMakeFiles/remote_monitoring.dir" does not appear to contain CMakeLists.txt"

Is the CMakeLists.txt file available somewhere, or am I doing something else wrong?

Thank you!

**Comment by swarlyyy** [comment] 2016-07-20 00:37
I just tried adding the CMakeLists.txt file "c/serializer/samples/remote_monitoring/CMakeLists.txt" to the remote_monitoring.dir directory and running cmake. I get the new error below:

"Unknow CMake command "compileAsC99" ... "Configuring incomplete, errors occurred!"

To help, I've attached the CMakeOutput.log file.
[CMakeOutput.log.txt](https://github.com/Azure/azure-iot-sdks/files/372687/CMakeOutput.log.txt)

**Comment by markrad** [comment] 2016-07-20 21:43
Hi @swarlyyy,

Can you please provide me a little more information about your environment? Are you building on Windows, Linux, something else? Did you build support for all of the protocols (AMQP, MQTT, HTTP)?

I'm not sure why you don't have a CMakeLists.txt in your clone of our repository. As you can see [here](https://github.com/Azure/azure-iot-sdks/blob/master/c/serializer/samples/remote_monitoring/CMakeLists.txt) it is in the directory you referenced in GitHub.

Perhaps you should try taking another clone of our GitHub repository. 

By chance are you using the Get Started with Microsoft Azure IoT Starter Kit - Raspberry Pi found at https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-raspberrypi-getstartedkit/? If so then there are a couple of known issues with these instructions. I can help you resolve them.

_Mark Radbourne MSFT_

**Comment by swarlyyy** [comment] 2016-07-20 22:18
Hi @markrad ,

Thanks for your reply! I'm building on Linux, Raspian Jessie OS. Sorry, but I don't know how to answer your question about the different protocols. I don't remember having an option to choose which protocol...but that's probably because I'm just ignorant about them.

I actually tried starting over with a different GitHub repository, but it seems almost identical to the other one and I got the same results (https://github.com/Azure-Samples/iot-hub-c-raspberrypi-getstartedkit). The link you listed is indeed the tutorial I followed yesterday.

I tried manually creating the CMakeLists.txt file again and commented out the line, "compileAsC99()" that was giving the error. It then gave me two other errors saying that the directory didn't have "samples" or "tests" directories. Creating these directories then led to more errors saying those directories didn't have CMakeList.txt files of their own. This is as far down the rabbit hole I got...

I'm glad that I'm using the GitHub repositories that have some known issues, at least. Any more advice you have is very welcome!

**Comment by markrad** [comment] 2016-07-20 22:57
Hi @swarlyyy,
The issue with the get started kit is this step:
```
cp -a iot-hub-c-raspberrypi-getstartedkit/azure-iot-sdks/. azure-iot-sdks/
```
This smashes the remote_monitoring directory. In my opinion it is badly designed and I will take this up with the page owner. Try this:
1) Get a new clone of the Azure-IoT-SDKs but clone it from the develop branch. There is an issue with the build on the Raspberry Pi that has been fixed in the develop branch but not the master. Use this command:
```
git clone --recursive -b develop https://github.com/azure/azure-iot-sdks.git <optional location to save in>
```
2) Change to /c/build_all/linux
3) Run ./build.sh
4) Check that the build is successful

At this point I'm going to need to find a mechanism for you to build the Getting Started version. Bear with me for a day or two. 

Thanks.

_Mark Radbourne MSFT_

**Comment by swarlyyy** [comment] 2016-07-21 00:50
Hi @markrad ,

Thank you very much for the explanation and clear instructions to try!

The build actually crashed the RasPi the first time I ran it at 34% (Building C object azure-c-shared-utility/tests/httpapiexsas_...). The build hung at 32% for a few minutes with the mouse and everything frozen, got to 34% and hung again before shutting down. But, it got further the second time.

The second time, the build error-ed out at 43% with the prompt:
"[43%] Built target httpapiex_unittests_exe
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2"

Should I try again after deleting the Azure  IoT directories and re-cloning?

**Comment by markrad** [comment] 2016-07-21 19:05
Hi @swarlyyy,

I think I know what the issue is. It's been fixed in the develop branch but has not yet made it to the master branch. The Raspberry Pi has four CPU cores so the build script attempts to utilize them all and passes jobs=$CORES where $CORES has a value of 4 as a parameter to make in build.sh. Unfortunately the Pi is too RAM constrained to run four build jobs simultaneously. If you edit the build script and find the line that reads
```
make --jobs=$CORES
```
and change it to 
```
make --jobs=1
```
you should be able to successfully build it.

_Mark Radbourne MSFT_

**Comment by swarlyyy** [comment] 2016-07-21 21:23
Hi @markrad ,

You were right! Making the change you recommended let the build end successfully. The results from the tests are below. Only four failed (I assume that's quasi-ok and expected):

"96% tests passed, 4 tests failed out of 96

Total Test time (real) =   3.81 sec

The following tests FAILED:
	27 - constbuffer_unittests (Failed)
	34 - httpapiex_unittests (Failed)
	41 - sastoken_unittests (Failed)
	63 - mqtt_client_unittests (Failed)
Errors while running CTest"

Looking forward to working with you on the Getting Started example. Thanks for everything!

**Comment by markrad** [comment] 2016-08-02 00:55
Hi @swarlyyy,
Closing this issue since we dealt with the problems directly. 

The issues with the Raspberry Pi Get Started page are being addressed.

_Mark Radbourne MSFT_

**Closed by markrad** 2016-08-02 00:55 UTC
Labels: CSS, help wanted
