### ISSUE TITLE
[C][Linux] Unit test failures on Raspberry Pi 2 running Raspbian

### ISSUE THREAD

**Issue by laurawalker** [Azure/azure-iot-sdks#556] opened 2016-05-13 12:50 UTC
Hi all,

I'm using the Azure IoT SDK (cloned from master branch as of today) on a RPi 2 running Raspbian. I've followed the instructions at https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/raspbian-raspberrypi2-c.md - the build completes and the sample (simplesample_ampq) seems to work but I'm getting the following unit test failures from the build:

> The following tests FAILED:
         12 - umocktypes_c_unittests (Failed)
         18 - constbuffer_unittests (Failed)
         25 - httpapiex_unittests (Failed)
         31 - sastoken_unittests (Failed)
         60 - iothubclient_http_e2etests (Failed)
         62 - iothubclient_mqtt_e2etests (Failed)
         64 - iothubclient_amqp_e2etests (Failed)

(The full test output is here: [log.txt](https://github.com/Azure/azure-iot-sdks/files/263253/log.txt))

I gather from https://github.com/Azure/azure-iot-sdks/issues/442 that the e2e tests are expected to fail without the environment vars configured, but I can't see anything suggesting the other unit tests should be failing (or why they might be) - is there something simple I've missed? Any help much appreciated!

**Comment by tameraw** [comment] 2016-05-13 17:12
@laurawalker - Thanks for submitting this issue. We'll investigate it.

**Comment by markrad** [comment] 2016-05-16 22:21
Hi @laurawalker,

Apparently something has changed that impacted the Raspberry Pi build. This was working on older clones of the repository but now I too see the same issue. I will research further and tell you what I find.

_Mark Radbourne MSFT_

**Comment by laurawalker** [comment] 2016-05-17 08:58
@markrad Thanks!

**Comment by markrad** [comment] 2016-05-18 00:22
Hi @laurawalker,

I reviewed the first failing test in umocktypes_c_unittests. The test is basically broken as designed. It has no hope of ever passing. However, apparently these tests are not run as part of the build on other platforms such as Ubuntu which is why this has not come to light earlier. 

I suspect that all of the failing tests are simply bad and it is not indicative of a problem in your environment. I will check each of the other tests over the next couple of days to confirm my believe. I think you should be okay to build and test your IoT application though. I'll respond on here when I know more.

_Mark Radbourne MSFT_

**Comment by laurawalker** [comment] 2016-05-18 10:07
@markrad Ok, good to know, thanks again :)

**Comment by markrad** [comment] 2016-05-27 18:17
Hi @laurawalker,

I am still researching this issue. I need a few more days to get to the bottom of the issue. I'm assuming that this does not impact your actual use of the SDK. Please let me know if that is not true.

_Mark Radbourne MSFT_

**Comment by laurawalker** [comment] 2016-06-01 13:14
@markrad You are correct - this is not preventing us from progressing for the moment. But it would be good to have it resolved :) thanks!

**Comment by markrad** [comment] 2016-07-08 03:33
Hi @laurawalker,

A defect has been filed to address this issue and it will be fixed at some point in the future. Unfortunately it is a fairly low priority at this time but it will be fixed.

_Mark Radbourne MSFT_

**Comment by anhashia** [comment] 2016-09-10 01:28
We have captured this in our product backlog as a low priority work item. If you are blocked because of this at some point in future, please feel free to open the issue.

**Closed by anhashia** 2016-09-10 01:28 UTC
Labels: CSS, enhancement
