### ISSUE TITLE
Not able to deploy the IoT Client SDK on device running an Android OS version 4.4

### ISSUE THREAD

**Issue by mileychen** [Azure/azure-iot-sdks#942] opened 2016-11-10 09:49 UTC
We did some test with IoT Client SDK, we found we are not able to deploy the IoT Client SDK on device running an Android OS version 4.4, but it works with Android OS version 5.0.

error/exceptions as bellow:
$ adb shell am start -n "com.iothub.azure.microsoft.com.androidsample/com.iothub.azure.microsoft.com.androidsample.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 2061 on device emulator-5554
I/System.out: Event Message 1
I/System.out: Event Message 2
I/System.out: Event Message 3
I/System.out: Event Message 4
D/OpenGLRenderer: Enabling debug mode 0
**I/System.out: Exception while opening IoTHub connection: java.io.IOException: Error initializing MQTT connection:MqttException**

From the description of this blog, this SDK should support an Android OS version 4.0.3 or greater:
"This section walks you through building, deploying and validating the IoT Client SDK on your device running an Android OS version 4.0.3 or greater. You will install the necessary prerequisites on your device. Once done, you will build and deploy the IoT Client SDK, and validate the sample tests required for IoT certification with the Azure IoT SDK."

so could you help to double check this issue and help us to figure out how to fix this error?

**Comment by anhashia** [comment] 2016-11-13 21:01
Hi @mileychen 
Unable to reproduce the issue. Able to successfully send and receive packets using **MQTT** protocol with sample located at java\device\samples**\\android-sample**. Below are the configuration details.


**SDK details**
 iothub-java-device-client:**1.0.14** (Updated samples\android-sample\app\build.gradle to use latest available client library)

**Emulator details**
CPU/ABI: ARM (armeabi-v7a)
image.sysdir.1: system-images\android-19\default\armeabi-v7a\
hw.cpu.model: cortex-a8
Target : **Android 4.4**

**Log**
I/System.out: Event Message 1
I/System.out: IoT Hub responded to message 1 with status OK_EMPTY
I/System.out: Event Message 2
I/System.out: IoT Hub responded to message 2 with status OK_EMPTY
I/System.out: Event Message 3
I/System.out: IoT Hub responded to message 3 with status OK_EMPTY
I/System.out: Event Message 4
I/System.out: IoT Hub responded to message 4 with status OK_EMPTY

**Comment by mileychen** [comment] 2016-11-15 08:54
Hi @anhashia ,

Thank you for your update, and I did a quick test with 1.0.14 Java SDK and armeabi-v7a/x86 android emulator, but i still got same error message.
11-15 03:42:33.010 2070-2070/com.iothub.azure.microsoft.com.androidsample I/System.out: Exception while opening IoTHub connection: java.io.IOException: Error initializing MQTT connection:MqttException

BTW, i use China Azure IoT account, is there anything different between China IoT and Global IoT?

**Comment by mileychen** [comment] 2016-11-16 08:09
Hi @anhashia,

I try to use Global IoT to do some test, and I found I can send message successfully to android 4.4 emulator with Mqtt Protocol. So I think there should have something different between ChinaToT and Global IoT.

And I debug the exception, and got the certification error as bellow:

java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by anhashia** [comment] 2016-11-16 23:42
Hi @mileychen 
Check for the cert chain from the corresponding Azure IoT Hub HTTPS endpoint and check if root CA is trusted for the device running Android 4.4.

**Comment by existenz31** [comment] 2016-11-17 09:38
Hi @anhashia 
I am facing the same problem with Android 6.0 (API 23) using the latest SDK IoT Client 1.0.14.

It seems the IoT Hub is not responding at all ... after a while I get a generic error:
`Error when connection: java.io.IOException: Error initializing MQTT connection:MqttException at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:139)
`

If I use the MQTTfx client, I cannot either connect the MQTT Server:

`org.eclipse.paho.client.mqttv3.MqttException: Unable to connect to server
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79) 
...
Caused by: java.net.ConnectException: Connection timed out: connect
`

Is there any extra settings in the IoT Hub to allow the MQTT protocol

PS: the HTTPS works fine with the SDK IoT client

**Comment by anhashia** [comment] 2016-11-22 18:56
Closing this. Please re-activate if you have any further questions on this. Thanks !

**Closed by anhashia** 2016-11-22 18:56 UTC
Labels: CSS, investigation-required
