### ISSUE TITLE
[C][Linux][AMQPWS] Behavior on connection lost

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#748] opened 2016-08-03 10:24 UTC
Hi,

While testing a bit, we encounter a weird behavior upon  network lost.
1. Let say we establish a connection with the iotHub send
2. A message to be sure the connection is ok.
3. After that, bring the network down
4. Send a new message, IoTHubClient_SendEventAsync returns ok (sounds ok, the message is stored in the queue)
5. Wait few  minutes (to be sure the connection is broken at websocket level)
6. Bring the network up, you'll see the following logs

```
#### on_ws_callback 10
#### on_ws_callback 35
#### on_ws_callback 34
#### on_ws_callback 36
#### on_ws_callback 35
#### on_ws_callback 34
#### on_ws_callback 36
#### on_ws_callback 10
#### on_ws_callback 35
#### on_ws_callback 33
#### on_ws_callback 36
#### on_ws_callback 4
#### on_ws_callback 30
[1470217923:0027] ERR: lws_callback_on_writable: failed to find socket 6
[1470217923:0029] NOTICE: lws_context_destroy
#### on_ws_callback 28
```
#### logs are additional logs to see the call reason of static int on_ws_callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len), in wsio.c

Reconnection seems to occurs a long time after that

```
[1470217923:0027] ERR: lws_callback_on_writable: failed to find socket 6
[1470217923:0029] NOTICE: lws_context_destroy
#### on_ws_callback 28
Error: Time:Wed Aug  3 12:10:10 2016 File:/home/lmussier/workspace/Agents/iothub/agent/external/azure-iot-sdks/c/azure-c-shared-utility/src/consolelogger.c Func:consolelogger_log Line:31 AMQP transport authentication timed out.
[10:10:10.002][ERROR]{simulator.cpp:396}                Message id=[4] failed to send (err = 1)
[10:10:10.002][DEBUG]{simulator.cpp:334}                Delete Message id=[4] sent
[1470219010:0046] NOTICE: Initial logging level 7
[1470219010:0049] NOTICE: Libwebsockets version: 1.6.0 f1cf5be
[1470219010:0050] NOTICE: IPV6 not compiled in
[1470219010:0052] NOTICE: libev support not compiled in
[1470219010:0054] NOTICE:  ctx mem: 21088 bytes
[1470219010:0058] NOTICE:  canonical_hostname = lmussier-virtual-machine
[1470219010:0059] NOTICE:  per-conn mem: 256 + 2126 headers + protocol rx buf
```

So the question is, how the SDK recovers from a network lost ? Obviously it seems to recover, but could you explain the conditions and the times. For me, we have something like 15 to 20 minutes of blackout.

**Comment by Jokymon** [comment] 2016-08-15 10:00
On my side it looks very similar with the difference that my first message indicating an issue is
`[1471252510:8235] ERR: lws_issue_raw: wsi 0x7f8f48026c20: LWS_SSL_CAPABLE_ERROR`

Also after a while the SendConfirmationCallback is called with `IOTHUB_CLIENT_CONFIRMATION_ERROR` for all messages sent so far, which to me means that the queued messages are now suddenly being dropped.

Once the connection is restored I again get a list of `IOTHUB_CLIENT_CONFIRMATION_ERROR` for all messages sent during the missing connection.

Could all of this be somehow related?

**Comment by anhashia** [comment] 2016-09-14 00:23
Investigating !

**Comment by anhashia** [comment] 2016-09-20 01:06
Working on local reproduction of the issue.

**Comment by anhashia** [comment] 2016-09-23 00:01
Hi @lmussier 
I updated to **latest develop** branch and then I tried following 2 tests by increasing `MESSAGE_COUNT ` in `iothub_client_sample_amqp_websockets`  sample for test purposes.

1.) Start client (Ubuntu machine) in **disconnected** state. Run `iothub_client_sample_amqp_websockets sample.`  Send will fail as expected with message "`AMQP transport failed to establish connection with service`".  Now connect the device to Internet. As soon as client got connected to Internet, it was able to establish connection to Azure IoT Hub and send packets to Azure IoT Hub. **Device Explorer** tool shows connection state from disconnected to connected.

2.) In connected state, send packets. Wait for **confirmation** callbacks. Disconnect the client as you soon as you start getting confirmation messages. Client will stop receiving the confirmation messages as expected.  Check connection state in Device Explorer tool. It will show device state from connected to disconnected.

**Comment by lmussier** [comment] 2016-09-23 07:45
@anhashia I'm ok with 1.) and certainly with 2.) (I don't check device state)
but you are missing 3.) 

3.)Is 2.) with with a reconnection.
In connected state send messages, wait for confirmations. Disconnect the client (in linux we eth0 down, on device we pull the cable), wait some time (at least 4/5 messages sending) and reconnect the device.

The reconnection take ages (at least last time I've checked). Your two tests does not cover the issue, you need to go further on 2.)

**Comment by anhashia** [comment] 2016-09-24 01:44
Investigating scenario 3 described above.

**Comment by anhashia** [comment] 2016-09-27 01:06
Hi @lmussier 
These are repro steps that I tried for **scenario 3**. Let me know if these look correct.
Changes made in **iothub_client_sample_amqp_websockets.c** sample
- Set `MESSAGE_COUNT 100 `and between each send add sleep of `3 seconds`.


**Repro steps**
1.) Start the sample with above modified changes
2.) Wait for **30 seconds**. You will see around 10 successful send attempts with `IOTHUB_CLIENT_CONFIRMATION_OK`
3.) Un-plug the ethernet cable. Make sure WLAN is disabled. 
4.) Wait for 30 seconds. During this time you will see `IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub` messages.
5.) Re-plug the ethernet cable
6.) Within around 10-15 seconds, you will see connection back and you will start receving confirmation with `IOTHUB_CLIENT_CONFIRMATION_OK`

If the above repro steps look correct, in that case can you please re-test with **latest** develop branch.

**Comment by lmussier** [comment] 2016-09-27 12:21
@anhashia I'll retry thi son my side, but sounds good so far :+1:

**Comment by rolandkru** [comment] 2016-09-29 07:14
Thank you for investigating this issue. This is a real stopper in several of our projects. 
However, we could not notice any improvement in the described behavior so far. Could you point to the commit where this issue should have been fixed?

**Comment by anhashia** [comment] 2016-09-29 20:11
Hi @rolandkru 
I started the test itself with latest **develop** branch few days back. Which IoT Hub client **sample** are you using for testing of scenario 3 ? What OS is running on your device ? Does your repro steps match above repro steps or do you have any variation in your repro steps? If you have some variation in your repro steps, can you please provide those.

**Comment by rolandkru** [comment] 2016-09-30 12:24
@anhashia Thank you for your response.

We've repeated our tests with the latest *develop* branch of today morning.
If we do the test according to your instructions ("wait for 30seconds") everything works as expected.
But if we do it in the same way as @lmussier ("Wait few minutes") we're getting confirmation errors as soon as the socket is closed (after around 15 minutes, checked with `netstat`):
```
Confirmation[651] received for message tracking id = 651 with result = IOTHUB_CLIENT_CONFIRMATION_ERROR
Confirmation[652] received for message tracking id = 652 with result = IOTHUB_CLIENT_CONFIRMATION_ERROR
Confirmation[653] received for message tracking id = 653 with result = IOTHUB_CLIENT_CONFIRMATION_ERROR
...
```
Confirmation errors are reported for the messages 651 - 1017 (we disconnected just after the first packet was confirmed, so what happened to message 2-650???) 

After these confirmation errors we see the buffering again (network cable still disconnected):
```
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
...
```

After 10 minutes the console gets flooded with the following messages repeating again and again:
```
Error: Time:Fri Sep 30 11:32:00 2016 File:xxx/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:establishConnection Line:563 Failed to open the connection with CBS.
Error: Time:Fri Sep 30 11:32:00 2016 File:xxx/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1462 AMQP transport failed to establish connection with service.
[1475227920:4707] NOTICE: Initial logging level 7
[1475227920:4707] NOTICE: Libwebsockets version: 1.6.0 f1cf5be
[1475227920:4708] NOTICE: IPV6 not compiled in
[1475227920:4708] NOTICE: libev support not compiled in
[1475227920:4709] NOTICE:  ctx mem: 16916 bytes
[1475227920:4710] NOTICE:  canonical_hostname = yyy
[1475227920:4711] NOTICE:  per-conn mem: 160 + 2126 headers + protocol rx buf
[1475227920:4924] NOTICE: lws_context_destroy
...
```

If we re-plug the network cable it takes between 10-30 minutes until we get a connection again!

Our test environment:
- imx6 dual core
- Linux OS
- *iothub_client_sample_amqp_websockets.c* modified to sleep 3sec after each send and set `#define MESSAGE_COUNT 10000`

**Comment by anhashia** [comment] 2016-09-30 17:28
Hi @rolandkru 
Thanks for the update ! I will investigate this further based on your repro steps.

**Comment by lmussier** [comment] 2016-10-04 09:11
@anhashia I've retested and results are the same as @rolandkru.
The weird behavior is still there.

Thanks for investigating.

**Comment by anhashia** [comment] 2016-10-04 23:36
Hi @lmussier @rolandkru 
Yeah, I am able to reproduce the issue if I use **longer** disconnect interval (like 5 minutes versus 30 seconds that I was previously using).

Right now, server (Azure IoT Hub) is configured to send ping after **105** seconds and client is also configured to send pings. If server  doesn't hear back from the client in number of attempts it will just disconnect the client. It is when the problem starts. 

When network comes back after 5 minutes, the client needs to re-establish the connection and re-authenticate quickly.  For smaller interval like 30 seconds or 1 minute disconnect you don't see the issue because during that time client is not disconnected from the IoT Hub.

There is work going on Service side around this area covered under https://github.com/Azure/azure-iot-sdks/issues/653. There is also work going on client side by the feature team to manage retries to improve the behavior around scenario in which network goes down temporarily.

**Comment by Jokymon** [comment] 2016-10-06 09:49
@anhashia is the work on the client side what is tracked in [Project 2](../projects/2)? Do you already have any time frame for when this will be implemented?

**Comment by anhashia** [comment] 2016-10-06 16:31
@Jokymon  Yeah, I think so.

**Comment by tameraw** [comment] 2016-11-07 08:54
Enhancements to the retry logic is currently a work-in-progress. We'll update here again soon.

**Comment by tmaltesen** [comment] 2016-11-10 14:14
I have additional information regarding similar issue.
What I observe is complete loss of reconnection.
If the network connection is dropped for a short period, and the network comes up using with a new IP address, then it seems that the connection is not taking a long time reconnecting, it is not reconnecting at all.
This case is very likely in case the connection is mobile (GPRS/LTE), even after a short drop of connection you will be assigned a new IP address on the interface.

**Comment by tameraw** [comment] 2016-11-28 19:20
First part of the retry work has been released for C client for the MQTT protocol.
Retry logic for AMQP will follow next.
Also the "ping" issue mentioned here is tracked in #653  as mentioned by @anhashia.

Closing this thread as issues are tracked.
If something is missed, please let us know. Thanks.

**Closed by tameraw** 2016-11-28 19:20 UTC
Labels: enhancement
