### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#427] opened 2016-03-30 09:50 UTC
Fantastic to see the first python support in the latest release. Thank you :) 

Just wondering if there could be a build switch to support python3?

**Comment by mregen** [comment] 2016-03-30 14:36
Hi Damien, would be great if you could give us more feedback for the Python 2 release. 
We are currently investigating the effort to enable Python3 as this release doesn't build yet for it, some small changes to the boost::python layer might be necessary beside a build switch

Thanks,
Martin

**Comment by damienpontifex** [comment] 2016-03-31 01:46
Thanks @mregen on initial look and testing with the samples, the python2 support seems good. The function callbacks for async functions was what I expected for python2.

My current python IoT project is all in python3 so will try something like python-future.org to see if I can use it in my current code.

For any enhancements for python3, it'd be great to see the async calls utilise the asyncio library for async-await syntax.

**Comment by damienpontifex** [comment] 2016-04-13 00:36
@mregen I'd be happy to close this as I can reliably build for py3.5 as desired now. Although can keep it open if you want to track further efforts in this area?

**Comment by mregen** [comment] 2016-04-13 09:53
@damienpontifex I'm just pushing now the last updates to enable Py3 builds and to fix a remaining segment violation issue. Doc updates are still due.

Are you planning to provide also the doc updates for your contributions? Would be great.

Please close the issue if you are a happy camper now and keep sending the good feedback!

Cheers!

**Comment by damienpontifex** [comment] 2016-04-13 12:18
I can add the changes to documentation. Shouldn't be too much for the version flag.

Will leave this open and close with a docs PR

**Closed** 2016-04-14 08:46 UTC
Labels: enhancement

**Comment by damienpontifex** [comment] 2016-04-18 08:28
@mregen have you successfully tested retrieving properties from a cloud to device message in the python sdk?

I am currently adding a message type on the server as
```csharp
Microsoft.Azure.Devices.Message commandMessage;
// Initialize message here
commandMessage.Properties.Add("Type", sentFrom.ToString());
```

and then on the client retrieving them like:
```python
map_properties = message.properties()
msg_properties = map_properties.get_internals()
self.logger.debug("Got msg properties {}".format(msg_properties))
```

But I get an empty dictionary as `msg_properties`. Just checking if you had successfully tested this and hence it may be something in my development?

Thanks in advance

**Comment by mregen** [comment] 2016-04-19 10:30
@damienpontifex when I implemented get_internals I always got at least one property from DeviceExplorer. Now not anymore. I also tried manually adding key/value pairs wo success, they neither show up in C and Python client. Please open an issue.

**Comment by mregen** [comment] 2016-04-21 14:35
@damienpontifex quick update, I added the map tests to verify the get_internal is working. In another test I was able to receive the properties with http, not with mqtt and amqp, so the issue is in the protocol layer.
