### ISSUE TITLE
Device by default in disable mode when created

### ISSUE THREAD

**Issue by UmerF920** [Azure/azure-iot-sdks#275] opened 2016-02-03 06:50 UTC
The device is by default disabled and disconnected when created using create Identity API in Java.

**Comment by tameraw** [comment] 2016-02-03 10:23
@UmerF920 - Thanks for bringing this up. This is a duplicate of issue #225 

The fix is already checked into the develop branch.

If you are using the master branch you will see the changes after our next release (which should happen later today or tomorrow).
Thanks,
-Tamer

**Closed by tameraw** 2016-02-03 10:23 UTC
