### ISSUE TITLE
[C][Linux][WS] iothub_client_sample_amqp_websockets seems to be broken

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#433] opened 2016-03-31 13:25 UTC
Hi,

I'm trying to make a websocket enable client using the SDK. Currently I can't manage to make iothub_client_sample_amqp_websockets connect to the IoTHub.

Compiled like this

```
cmake ../azure-iot-sdks/c -Duse_amqp:BOOL=ON -Duse_http:BOOL=OFF -Duse_mqtt:BOOL=OFF -Drun_e2e_tests:BOOL=OFF -Duse_wsio:BOOL=ON -Drun_longhaul_tests:BOOL=OFF -Dskip_unittests:BOOL=ON\ -DcompileOption_C:STRING=-std=c99 -DcompileOption_CXX:STRING=-fpermissive
```
I get that

```
Starting the IoTHub client sample AMQP over WebSockets...
Info: IoT Hub SDK for C, version 1.0.3
Error: Time:Thu Mar 31 15:24:41 2016 File:/home/lmussier/workspace/azure-iot-sdks/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_Create Line:318 Registering device in transport failedError: Time:Thu Mar 31 15:24:41 2016 File:/home/lmussier/workspace/azure-iot-sdks/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_CreateFromConnectionString Line:220 IoTHubClient_LL_Create failed
Error: Time:Thu Mar 31 15:24:41 2016 File:/home/lmussier/workspace/azure-iot-sdks/c/iothub_client/src/iothub_client.c Func:IoTHubClient_CreateFromConnectionString Line:143 IoTHubClient_LL_CreateFromConnectionString failed
ERROR: iotHubClientHandle is NULL!
```

However iothub_client_sample_amqp works perfeclty !
Do we have to enable something on IoTHub side ?

**Comment by lmussier** [comment] 2016-03-31 13:32
Add compile command

**Comment by ewertons** [comment] 2016-03-31 18:34
That is unexpected. 
Please give us a day, I'll check it out and see what's going on.
Thanks for reporting the issue.

**Comment by ewertons** [comment] 2016-04-05 23:25
@lmussier, I was able to reproduce the error you experienced. 
Thanks for reporting it.

It was caused by a recent change that was not extended properly to the _C SDK over websockets_ source code.
I got it fixed and tested, and it is currently checked in develop branch.

Please try it out and let us know if you experience any other issues.
Thanks for using the Azure IoT Hub Client SDK.

**Closed by ewertons** 2016-04-05 23:25 UTC
Labels: help wanted

**Comment by lmussier** [comment] 2016-04-06 13:00
Hi,

The sample weems to work, but I don't see my device as connected on device explorer.
I'll investgate further, thanks.

**Comment by lmussier** [comment] 2016-04-06 13:15
Forget that, the sample is running perfectly.
Thanks !
