### ISSUE TITLE
Status of device management (dmpreview) branch

### ISSUE THREAD

**Issue by volkanceylan** [Azure/azure-iot-sdks#559] opened 2016-05-15 16:18 UTC
Hi,

I was using some NuGet package from presumably dmpreview branch to test managing DeviceProperties and ServiceProperties.

Microsoft.Azure.Devices 1.1.0-preview-002

It was working fine, was able to tag devices, read properties etc. till last week when it stopped working. Now these properties are always returning null.

Also the NuGet package version above can't be seen in NuGet Gallery anymore. I can't see these properties in any of current branches too.

Can you give some information about what happened to this branch, and device management in general, e.g. samples there about updating firmware.

Thanks.

**Comment by damonbarry** [comment] 2016-05-16 00:09
The NuGet package is available at http://www.nuget.org/packages/Microsoft.Azure.Devices/1.1.0-preview-002.

Regarding properties always returning null, can you provide more details? Are you running one of our samples against a registered and running device?

**Comment by volkanceylan** [comment] 2016-05-16 20:31
I was testing with virtual devices, than we added a real one, but it started to return null for both. 

Now i have two test, one real device, all with status Enabled, but connection state Disconnected.

Now i'm getting empy DeviceProperties/ServiceProperties with one virtual one, while other two returns null. Should i share GenerationIDs?

I think it should always return empty dictionary, as if it returns null, it's not possible to update tags, as these are readonly properties, or is there another method?

Can you direct me where is source to this preview package, so that i can use JSON post directly instead of having to depend on C# api.

**Comment by volkanceylan** [comment] 2016-05-16 20:35
FYI, i'm using RegistryManager.GetDeviceAsync method to retrieve a device by its ID.

**Comment by markrad** [comment] 2016-06-03 23:13
Hi @volkanceylan,

I looked at your issue and I was able to reproduce it. However, when I created a new IoT device, I was not able to reproduce it on that device, only devices that I had created earlier. 

I am suspecting that something changed that caused previously created devices to experience this issue. Can you try creating a new device and see if you are observing the same behavior please?

Thank you.

_Mark Radbourne MSFT_

**Comment by volkanceylan** [comment] 2016-06-07 18:28
Hi,

One older one is still null but added two devices, they don't seem to be returning null.

Thanks

**Comment by damonbarry** [comment] 2016-06-13 20:26
I'll follow up with the service team about whether this is a known issue (older devices returning null for deviceProperties).  Closing this since the behavior doesn't happen on new devices.

**Closed by damonbarry** 2016-06-13 20:26 UTC
Labels: CSS, DM
