### ISSUE TITLE
IoT Hub Sample Client for C/HTTP not working behind Corporate Proxy

### ISSUE THREAD

**Issue by harishbhattbhatt** [Azure/azure-iot-sdks#396] opened 2016-03-16 13:43 UTC
Hi,

I am unable to send any messages from my Win 2012 server to IoT hub using C SDK, while the C# SDK works fine.

I can used the C SDK from my home environment (without proxy), what needs to be done to use C SDK/Http behind corporate proxy.

**Comment by tameraw** [comment] 2016-03-16 17:41
@harishbhattbhatt - Thanks for reporting your issue.
Please confirm that you're able to configure the proper proxy settings on your Windows server.

https://technet.microsoft.com/en-us/library/cc754834.aspx

http://thesolving.com/server-room/how-to-force-proxy-settings-via-group-policy-on-windows-server-2012/

**Comment by shazz** [comment] 2016-03-16 20:15
I have the same issue. My C based devices are behind a proxy to access the Azure IoT hub, any wat to support HTTP proxies at least for HTTP ?

**Comment by harishbhattbhatt** [comment] 2016-03-17 05:27
All other programs even the C# SDK for IOT hub works without any issue on my Win 2012.

Finally i also need to run C SDK in linux enviornment, can you provide some help to set the proxy from code itself ? 

So in nutshell C SDK does not work in Windows or Linux enviornment behind proxy.

**Comment by srberard** [comment] 2016-03-20 12:02
I too need the ability to operate behind a NAT/Firewall.  The approach we've been thinking of is to to leverage AMQP over Websockets.  Since Websockets can be proxy friendly this should work reliably and in a wide variety of network environments.  In looking over the SDK, it appears that Websockets is available but is only being compiled for the Windows port.  Like @shazz I need this on our Linux-based devices as well.

**Comment by harishbhattbhatt** [comment] 2016-03-21 08:24
I am unable to even build the C SDK on my CenOS 7.2 machine, can you please provide some detail on how to build on it ? Currently it only provides information for ubuntu.

**Comment by tameraw** [comment] 2016-03-21 20:32
Currently the SDKs do not have support for configuring proxy settings. We rely on OS settings at this point.

**Comment by ashokkhurana** [comment] 2016-03-22 07:05
@harishbhattbhatt , could you please share the details of issue you are facing while building C SDK on CenOS?

**Comment by harishbhattbhatt** [comment] 2016-03-23 09:09
By default CentOS supports GCC 4.8.5 there is no information provided on how to upgrade to GCC 4.9.2.

After lot of difficulty i was able to build the C SDK with GCC 4.8.5 but i need to disable all type of tests and atomic feature which is only available with GCC 4.9

When we compile/build the code we get Amqp, MQTT and http sample client in bin folder but no amqp with websocket.

After close look at the "build.sh" it seems that Amqp with websocket does not getting compiled.

Can you please provide steps to upgrade GCC on CentOS ?
Did you guys tested this SDK on CentOS or Redhat ?
Is Amqp with websocket supported with current version of C device SDK ?

Its really painful to build the C SDK and get it working, please improve the documentation and make the task seemless.

Hope to hear soon from you guys.

**Comment by ewertons** [comment] 2016-04-14 22:54
Hello @srberard 
Although WebSockets is supported by Azure IoT C SDK on Linux, indeed there is a gap on the build scripts, which are not exposing the option to enable using WebSocket. This issue will be addressed immediately.

**Comment by srberard** [comment] 2016-04-14 22:57
Awesome, appreciate it!

**Comment by ewertons** [comment] 2016-04-15 20:00
Alright @srberard , the fixes are in for building the C SDK with support for AMQP over WebSockets. 
All you need to do is run <root>\build\windows_c.cmd --use-websockets (for Windows) or <root>/build/Linux_c.sh --use-websockets (for Linux).

Note that there were changes in uAMQP to get that working, and they were not released to master yet. Until we release the next version of uAMQP you will need to go to <root>/c/azure-uamqp-c and checkout develop before building the Azure-IoT-SDK with support for WebSockets.

**Comment by ewertons** [comment] 2016-04-15 20:36
Hi @harishbhattbhatt ,

please refer to the [list of platforms currently supported](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/) by Azure IoT SDK.

Cent OS has not been tested yet, although you can make the necessary changes to support it and submit a pull request.

As per your requests, 
1. Can you please provide steps to upgrade GCC on CentOS ?
A: Doing quick search on Bing I got this result: https://www.experts-exchange.com/questions/27472822/Upgrading-GCC-on-CentOS.html.

2. Did you guys tested this SDK on CentOS or Redhat ?
A: No, the C SDK has not been tested on CentOS or RedHat (please see the [list of supported platforms](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/))

3. Is Amqp with websocket supported with current version of C device SDK ?
A: Yes it is. Please see the comnents above. Also refer to instructions to run the [AMQP  over WebSockets sample](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/amqp-c-websockets-run-sample.md).

The Azure IoT Client C SDK was designed to offer the most straightforward build experience for the supported platforms. Please share your specific questions and comments about building Azure IoT Client C SDK and we will address those right away.

Thanks for using the Azure IoT Hub Client SDK.

**Comment by ewertons** [comment] 2016-04-15 20:39
Hi @harishbhattbhatt, in regards to running the Azure IoT Client C SDK behind a proxy yes please use AMQP over WebSockets. 
Please refer to these [instructions](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/amqp-c-websockets-run-sample.md) and try running the sample on your machine.
If you still experience connection failures, please share the details and we will work to address any issues.

Thanks for using the Azure IoT Hub Client SDK.

**Comment by srberard** [comment] 2016-04-15 23:32
@ewertons Thanks!  We'll test this out ASAP and let you know if we have any troubles.

**Comment by ewertons** [comment] 2016-04-22 18:36
Please try the solution, and let us know if you have any other issue.
I'll close the issue for now, but please feel free to re-open it if you need.

Thanks for using Azure IoT SDK

**Closed by ewertons** 2016-04-22 18:36 UTC
Labels: enhancement

**Comment by varwnosg** [comment] 2016-09-01 10:43
Trying to use AMQP over Websockets as a more firewall friendly solution I encountered a few issues which guide me in this closed thread. I read the instructions to build the necessary libraries for AMQP over websockets. I was wondering if there is available an AMQP over Websockets Nuget Package fro Visual Studio?
