### ISSUE TITLE
Compilation error in xlogging.h if the source code has #include "syslog.h" 

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdks#1003] opened 2016-12-01 05:55 UTC
I am getting compilation error in xlogging.h when I include syslog.h in my source code. Look like there is  variable name ( LOG_INFO) clash between syslog.h and Xlogging.h Please check the below details.

```

make[2]: Entering directory `/home/connector'
g++ -Wall -fstack-protector-all -fbounds-check  -O2 -g -pipe -fPIC -I/home/ -c -o CloudConnector.o CloudConnector.cpp
In file included from /usr/include/syslog.h:1:0,
                 from CloudConnector.h:11,
                 from CloudConnector.cpp:8:
/usr/include/azure_c_shared_utility/xlogging.h:18:5: error: expected identifier before numeric constant
     LOG_INFO,
     ^
/usr/include/azure_c_shared_utility/xlogging.h:18:5: error: expected ‘}’ before numeric constant
/usr/include/azure_c_shared_utility/xlogging.h:18:5: error: expected unqualified-id before numeric constant
In file included from /usr/include/azure_c_shared_utility/xio.h:9:0,
                 from /usr/include/iothub/iothub_client_ll.h:55,
                 from /usr/include/iothub/iothub_client.h:20,
                 from CloudTransceiver.h:18,
                 from CloudConnector.h:138,
                 from CloudConnector.cpp:8:
/usr/include/azure_c_shared_utility/xlogging.h:20:1: error: expected declaration before ‘}’ token
} LOG_CATEGORY;
^
make[2]: *** [CloudConnector.o] Error 1
make[2]: Leaving directory `/home//CloudConnector/connector'
make[1]: *** [connector] Error 2
make[1]: Leaving directory `/home/CloudConnector'
make: *** [all] Error 1

```

**Comment by damonbarry** [comment] 2017-01-06 21:44
Closing, duplicate of https://github.com/Azure/azure-c-shared-utility/issues/41

**Closed by damonbarry** 2017-01-06 21:44 UTC
