### ISSUE TITLE
complete messagge using http is always reported as rejected

### ISSUE THREAD

**Issue by rcoccia** [Azure/azure-iot-sdks#85] opened 2015-10-16 09:06 UTC
using HttpDeviceClient, both methods OnCompleteAsync and OnRejectAsync send an HTTP DELETE with the same URL parameters. This behavior seems to cause that messages are always reported has rejected on the command feedback endpoint. More detailed: the querystring invoked by OnCompleteAsync  has a final "&reject" instead of "&accept".

**Comment by dcristoloveanu** [comment] 2015-10-19 17:44
This sounds like a bug, we are investigating it.

**Comment by dcristoloveanu** [comment] 2015-10-19 17:55
Duplicate of #63.

**Closed by dcristoloveanu** 2015-10-19 17:55 UTC
