### ISSUE TITLE
Add the proxy server configuration support in the device sdk

### ISSUE THREAD

**Issue by haogu** [Azure/azure-iot-sdks#108] opened 2015-10-23 18:57 UTC
Many devices are deployed behind a proxy server in an enterprise. How do we setup the proxy server settings in the device side sdk? For example, if amqp is used.

**Comment by haogu** [comment] 2015-10-26 13:40
Is it a documentation issue? Does the API SDK actually support configuring the proxy settings?

**Comment by dominicbetts** [comment] 2015-10-26 14:46
@CarlosAlayo can you confirm if the SDKs support setting a proxy for device connection to IoT Hub?

**Comment by dominicbetts** [comment] 2015-11-12 11:19
@olivierbloch  can you confirm if the SDKs support setting a proxy for device connection to IoT Hub?

**Comment by olivierbloch** [comment] 2015-11-13 05:24
At this point there is no API for setting a proxy for device connection. Not sure that belongs in the SDK itself.

**Comment by NNM11** [comment] 2015-11-19 20:03
This is a very critical issue for IoT devices.  Without a meaningful proxy configuration support/document from the azure-iot-sdks, the SDK is not usable in real applications except demos.  Azure SDK team needs to step up since AWS and BlueMix handled the proxy issue with ease.

**Comment by Mike-Stanley** [comment] 2015-11-19 20:20
Some guidelines for dealing with this type of issue would be welcome.  I've hit a couple issues when operating behind a corporate firewall:
1. Device Explorer creates an Error dialog with "An existing connection was forcibly closed by the remote host" when the Monitor button is pressed on the Data tab.  It's correlated with an exception issued from eventHubClient.GetRuntimeInformation().PartitionCount in MonitorEventHubAsync().  I'm still waiting for my corporate IT types to open up the firewall port where I'm being blocked.  Also noodling over ways to work around the problem in the Device Explorer code.
2. In the temp_sensor_anomoly example, I discovered that our corporate network had an internal NTP servers, so accesses to 0.pool.ntp.org in function setupRealTime() failed.  The workaround included modifying the NTP client to return a failed status after a small number of retries, at which point setupRealTime() makes a second call to the internal NTP server.
But THANK YOU for the great tutorial.  It's gone a long way to helping me come up to speed.
Regards

**Comment by ateare** [comment] 2015-11-22 23:12
I was able to get the Device Explorer working through a proxy server by adding this to the App.config (DeviceExplorer.exe.config):
  ```
  <system.net>
    <defaultProxy useDefaultCredentials="true" />
  </system.net> 
```
Add it to the end of the file just before the ```</configuration>```.  I had a similar problem with sending messages via WCF and this addressed it.

**Comment by charlehsin** [comment] 2015-11-24 22:37
@ateare  I am facing the exact same issue as you for both Device Explorer and a sample device C# example.   I will try to run the stuff at my home (not at office) to see if it will work without the proxy stuff.

**Comment by Mike-Stanley** [comment] 2015-11-24 22:41
I was able to move past my issue #1 after our corporate IT adjusted the settings for our firewall.

**Comment by guidoffm** [comment] 2015-12-03 09:09
I am facing the exact same issue as you for both Device Explorer and a sample device C# example.

**Comment by tameraw** [comment] 2016-01-06 19:36
This has been added to our backlog and will be prioritized as it appears the issue is faced by several people.

**Closed by tameraw** 2016-01-06 19:36 UTC
Labels: enhancement

**Comment by myamama** [comment] 2016-12-27 07:01
Any update on this?

**Comment by cyrilzh** [comment] 2017-02-09 06:04
Has this been fixed already?
