### ISSUE TITLE
UWP apps only HTTP support ?

### ISSUE THREAD

**Issue by ppatierno** [Azure/azure-iot-sdks#79] opened 2015-10-15 19:28 UTC
Hi,
deeping into the source code for C# client I saw that AMQP protocol isn't supported for UWP apps.
I found this in the CreateFromConnectionString method of DeviceClient class : 

if (transportType == TransportType.Amqp)
{
#if WINDOWS_UWP
                throw new NotImplementedException();
#else
                return new DeviceClient(new AmqpDeviceClient(iotHubConnectionString));
#endif

Why ?
I'm wondering if it depends on Microsoft.Azure.Amqp Nuget package used inside the C# client.
Does it work only on .Net Framework and not on UWP apps ?
If yes, why don't use a more universal implementation like AMQP .Net Lite library ?

Thanks,
Paolo.

**Comment by MaxKhlupnov** [comment] 2015-10-15 19:53
Confirmed. Had the same issue. Looks like Win 10 IoT core supports only http as a messaging protocol.

**Comment by dcristoloveanu** [comment] 2015-10-19 17:50
Having AMQP for UWP is on our backlog (we plan to actually use AMQPLite).

**Comment by ppatierno** [comment] 2015-10-19 17:52
It's a great news ... using AMQP .Net Lite is the best choice :-)

**Comment by aribeironovaes** [comment] 2015-11-02 19:11
Thanks for the feedback @ppatierno  and @MaxKhlupnov. 

Closing this issue since, according to @dcristoloveanu  it's on our backlog. 

Angelo Ribeiro.

**Closed by aribeironovaes** 2015-11-02 19:11 UTC

**Comment by MaxKhlupnov** [comment] 2015-11-08 09:16
Hello, @dcristoloveanu, @aribeironovaes and @ppatierno !
 why you going to use AMQP .Net Lite for .Net UWP? 
Looks like most Azure-iot-sdks code based on Apache.Qpid.Proton.
This might case inconsistency and multiply efforts required for support AMQP stack.

**Comment by sonukushwah221** [comment] 2016-04-26 10:12
i want to communicate the Dragon board to azure and get back massage to the dragon board can some one help me
