### ISSUE TITLE
Platform.h error when building for Python on Win10

### ISSUE THREAD

**Issue by tbaggs** [Azure/azure-iot-sdks#610] opened 2016-06-05 01:41 UTC
I keep getting this same error when trying to build Python for Win10.  I got the C sdk to compile with no problem.  I'm using Python 3.4. I've tried on 2 different Win10 machines with the same result.

..\..\src\iothub_client_python.cpp(10): fatal error C1083: Cannot open include file: 'azure_c_shared_utility/platform.h': No such file or directory [U:\Projects\Repos\IoTSDK\python\device\iothub_client_python\windows\client\iothub_client.vcxproj]

**Comment by mregen** [comment] 2016-06-06 12:15
@tbaggs Sorry this is a known issue since the last release a ref in the vcproj file is pointing the includes to a mismatched nuget package: #597. Fixed by the upcoming release in master and is already fixed in develop.

**Comment by tameraw** [comment] 2016-06-06 17:28
@tbaggs - Closing as duplicate of #597 
As @mregen stated, we're currently working on a release. ETA, end-of-day today.

**Closed by tameraw** 2016-06-06 17:28 UTC
