### ISSUE TITLE
[Python]Install via pip

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#727] opened 2016-07-23 05:53 UTC
Utilising the python sdk, it would be great if the azure-iot-sdk was able to be installed with pip. Thus making it more aligned with other libraries that a project may utilise.

**Comment by tameraw** [comment] 2016-09-22 07:00
@damienpontifex - Thanks for filing this. Closing as duplicate of #560 
 which we're hoping to provide in the near future.

**Closed by tameraw** 2016-09-22 07:00 UTC
Labels: enhancement
