### ISSUE TITLE
about IOException

### ISSUE THREAD

**Issue by JakeRed** [Azure/azure-iot-sdks#923] opened 2016-11-07 07:44 UTC
Hi:
    We using iot in android phone，It is very good;but in samsung (android 5.0),An error occurred：
Exception while opening IoTHub connection: java.io.IOException: Error initializing MQTT connection:无权连接

We also encountered some problems in the use of：
such：in android 4.4，SDKS won't support it 。
and network is bad ，Infinite reconnection，android Log ：
java.lang.IllegalStateException: The MQTT connection is currently closed. Call open() before attemptingto receive a message.: The MQTT connection is currently closed. Call open() before attemptingto receive a message.

thanks！

**Comment by anhashia** [comment] 2016-11-07 20:25
Investigating !

**Comment by JakeRed** [comment] 2016-11-08 01:48
Sorry,We solve this exception “ Error initializing MQTT connection:无权连接”， But the other two questions remain to be resolved. 
Focus on this error "java.lang.IllegalStateException: The MQTT connection is currently closed. Call open() before attemptingto receive a message.: The MQTT connection is currently closed. Call open() before attemptingto receive a message."

**Comment by JakeRed** [comment] 2016-11-08 03:35
I use the com.microsoft.azure.iothub-java-client:iothub-java-device-client-dev:1.0.9,No more highly used versions in android studio.

**Comment by anhashia** [comment] 2016-11-13 05:56
Hi @JakeRed 
Unable to reproduce the issue on Samsung-SM-G900 running **Android 5.0** using MQTT protocol. Able to successfully send and receive messages using MQTT protocol.
Updated  `build.gradle` file to use  latest available `iothub-java-device-client:1.0.14` library

**Comment by anhashia** [comment] 2016-11-16 23:35
#942

**Comment by anhashia** [comment] 2016-11-21 23:12
Closing. Please re-activate if you still are having issues. Thanks !

**Closed by anhashia** 2016-11-21 23:12 UTC
Labels: CSS, question
