### ISSUE TITLE
DeviceClient.CreateFromConnectionString() fails when '+' character is present in DeviceId string

### ISSUE THREAD

**Issue by alinapopa** [Azure/azure-iot-sdks#481] opened 2016-04-13 21:16 UTC
DeviceClient.CreateFromConnectionString() fails with this exception message: 
"The connection string has an invalid value for property: DeviceId\r\nParameter name: iotHubConnectionString" 

When calling:
DeviceClient.CreateFromConnectionString(connectionStr, TransportType.Http1);

Connection string had the format:
"HostName=hostName;DeviceId=deviceId;SharedAccessKey=sharedAccessKey"

Failure was caused by the presence of '+' character in the DeviceId string. The '+' character is on the list of accepted characters for Device Id based on documentation https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide/

**Comment by tameraw** [comment] 2016-04-14 05:35
@alinapopa - Thanks for filing this issue. We'll investigate it.

**Comment by markrad** [comment] 2016-04-25 21:47
Hi @alinapopa 
I'll take a look at this and get back to you.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-04-26 01:57
Hi @alinapopa ,

I am able to reproduce this issue. It appears that WebUtility::UrlDecode takes issue with the + sign. I will need to do some further research.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-04-26 23:40
Hi @alinapopa,

I discussed your issue with the product group and they agree that it is a bug. However they are currently undecided if it is a code bug or a documentation bug. I'll let you know when I hear back from them.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-05-02 23:28
Hi @alinapopa,

I am still working on this. I hope to have further information for you soon.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-05-06 23:38
Hi @alinapopa,

This has been deemed a defect but the product group need to do additional research to find out how much impact fixing it will have.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-05-13 22:09
Hi @alinapopa,

A fix for this issue is expected to be checked into the develop branch next week.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-05-24 17:53
Hi @alinapopa,

This issue is caused because the device identity in the connection string is supposed to be URL encoded before it is passed to the SDK. Unfortunately this was not properly implemented in either the device explorer or the Azure portal website. Both of these return a connection string that does **not** contain a URL encoded device identity. If you were to encode the device identity yourself, just the actual identity, the rest of the string should be left as is, then you will be able to successfully circumvent the issue. 

There will be a fix coming for all software that generates a connection string to address this problem. Due to the wider impact to various software components, this will be a little delayed. Given that I am going to close this issue now since a fix is coming. However, if you are still having problems after URL encoding the device identity please feel free to reopen the issue.

Thank you for bringing this to our attention.

_Mark Radbourne MSFT_

**Closed by markrad** 2016-05-24 17:53 UTC
Labels: bug, CSS

**Comment by Clinerg59** [comment] 2016-07-03 06:37
I have a '+' plus in my Device Key too.  Now what am I supposed to do from above?

**Comment by ginaospina** [comment] 2016-08-08 12:48
I am trying to follow up this sample to send a simple message to the iot hub however I have this error: The connection string has an invalid value for property: HostName

The code is exactly the same as shown here,
Taking a look at google, the only result that seems to be the same as mine is this: https://github.com/Azure/azure...

My connection string and device key is the followin:
static string iotHubUri = "HostName=IoTHubImasDTest1.azure-devices...;SharedAccessKeyName=iothubowner;SharedAccessKey=4iyaZcFxDdMm8sUz+vgTU/iB/jFVGKBGz0AQ3CoJh1w=";
static string deviceKey = "4pURrcHCPdKz7LzvdF3kMVzL7u0Kuy5FZz2TXh07z4w=";

As you can see the device key does not have a plus sign, but the sharedaccesskey does have it.

What can I do in this case?
