### ISSUE TITLE
problem sending application properties when added to amqp sample in the C sdk on windows.

### ISSUE THREAD

**Issue by alfintatorkace** [Azure/azure-iot-sdks#794] opened 2016-08-30 20:34 UTC
Using the latest code as of today.
I'm having some trouble with the send side of adding application properties to amqp messages.  
First I used service bus explorer to send the messages with a few properties, and I can retrieve the properties when I receive the messages.  That all works fine.

I added some application properties to the message_sender sample, but when I send the messages nothing shows up in the queue I'm sending to.  If I don't add the properties, the messages go into the queue just fine.  I don't see any errors returned, and I stepped through the code and watch it pull the properties out of the messages I added and encode them before sending, all looks fine from what I could tell.  I see the send_one_message functions logging them before they are sent.

Seems fairly simple, below is the code I added just befor sending the message:

			//set properties here
			AMQP_VALUE prop_map = amqpvalue_create_map();

			char* keys[2] = { "value1", "value2" };
			char* values[2] = { "this is value1", "this is value2" };
			for (unsigned int i = 0; i < 2; i++)
			{
				AMQP_VALUE key = amqpvalue_create_string(keys[i]);
				AMQP_VALUE value = amqpvalue_create_string(values[i]);
				amqpvalue_set_map_value(prop_map, key, value);
			}

			AMQP_VALUE application_properties = amqpvalue_create_application_properties(prop_map);

			message_set_application_properties(message, application_properties);

I thought this would be pretty straight forward after getting the receive side to work, but no luck.  

Is there something I'm missing?

alf

**Comment by dcristoloveanu** [comment] 2016-09-06 21:39
Hi @alfintatorkace,

Sorry for the delay in the reply.
I think the problem is that message_set_application_properties expects a uAMQP map.

Doing message_set_application_properties(message, prop_map); should do the trick.

Let me know if this does not work.

Cheers,
/Dan

**Comment by alfintatorkace** [comment] 2016-09-07 01:52
Thanks Dan, that worked great, figured it was something simple.  Guess I over reverse engineered what I did on the receive side.

One other question that wasn't obvious from the simple samples.  I notice if I connect and start sending right away, I get a send error in the send confirmation callback as the message_sender_instance state is not yet MESSAGE_SENDER_STATE_OPEN.  Is there a connect callback I should be using to wait until the connection is really opened before I start sending?  What is the recommended procedure?

thanks
alf

**Comment by dcristoloveanu** [comment] 2016-09-07 04:12
Hi @alfintatorkace,

on_message_sender_state_changed passed to messagesender_create can tell you when the message sender state has changed to _OPEN (or any of the other states).

Hope this helps,
/Dan

**Comment by alfintatorkace** [comment] 2016-09-12 20:31
I've got another issue with setting message properties, specifically "SessionId".  I saw somewhere that this translates to group-id, and when I set session id in a message using service bus explorer, I can receive messages in my c code using properties_get_group_id.

Using the message_sender sample, I tried this code before sending a message:
			PROPERTIES_HANDLE properties = NULL;
			message_get_properties(message, &properties);

			if (!properties)
			{
				properties = properties_create();
			}
			if (properties)
			{
				properties_set_group_id(properties, "01234");
				message_set_properties(message, properties);
			}

When I send a message, service bus explorer shows x number of messages in the queue, but I am not able to receive them with either service bus explorer or my C code, the messages are just stuck there and I have to delete the queue and recreate it.

Is there some magic to  setting message properties?

thanks
alf

**Comment by jtanner-msft** [comment] 2016-09-22 22:43
Hi @alfintatorkace ,
Since you have opened the new issue where Tamer suggested, I'll proceed with closing this current issue now.  Let's continue our discussion / investigation in this issue:
https://github.com/Azure/azure-uamqp-c/issues/21 

Thanks,

**Closed by jtanner-msft** 2016-09-22 22:43 UTC
Labels: help wanted
