### ISSUE TITLE
I'm getting this error when runing build.sh in c/build_all/linux folder on Mac OS X 10.11.5. Can you help me?

### ISSUE THREAD

**Issue by jiangzhibin** [Azure/azure-iot-sdks#574] opened 2016-05-23 02:08 UTC
I'm getting this error when runing build.sh in c/build_all/linux folder on Mac OS X 10.11.5. Can you help me?

In file included from /Users/jasonryan/Desktop/CodeFactory/Developer/azure-iot-sdks-copy/c/azure-c-shared-utility/testtools/micromock/inc/timediscretemicromock.h:408:
/Users/jasonryan/Desktop/CodeFactory/Developer/azure-iot-sdks-copy/c/azure-c-shared-utility/testtools/micromock/inc/timediscretemicromockcallmacros.h:2136:15: error: 
      'registerCallXArg' is a private member of 'stims_base'
                stims_base::registerCallXArg(this);
                            ^
/Users/jasonryan/Desktop/CodeFactory/Developer/azure-iot-sdks-copy/c/azure-c-shared-utility/testtools/micromock/inc/timediscretemicromock.h:388:17: note: 
      declared private here
    static void registerCallXArg(canPlay* someStim...
                ^
5 errors generated.

If I change the registerCallXArg(...) to public , there will be a new error about source code.

**Comment by anhashia** [comment] 2016-05-23 22:28
Looking into this issue

**Comment by anhashia** [comment] 2016-05-27 18:40
This is coming while compiling tests tools. What is the compiler that you are using ? The error is coming because compiler is not able to use friend class definition to access the private method. I don’t see build issue on Ubuntu by following instructions on https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#linux . Can you please provide more details of your build configuration and repro steps so that I can do local reproduction of the issue ? That way I will be in better position to assist you on this.

**Comment by anhashia** [comment] 2016-06-21 22:53
Closing this. Please let us know if you're still having issues. Thanks !

**Closed by anhashia** 2016-06-21 22:53 UTC
Labels: CSS, help wanted
