### ISSUE TITLE
Need better exception thrown since IoT Device SDK PCL requires that platform specific projects have reference to nuget package

### ISSUE THREAD

**Issue by nicolehaugen79** [Azure/azure-iot-sdks#489] opened 2016-04-15 15:15 UTC
The MyDriving app (which was released for //build 2016) has a PCL called MyDriving that contains all common code that is shared by the iOS\Android\WinPhone platform projects.  The code that connects and sends data to the IoT Hub is contained within the MyDriving PCL and as a result, the MyDriving PCL must reference the PCL version of the Azure IoT device SDK in order to implement this functionality.
What is not as obvious is that the iOS\Android\WinPhone platform projects must also reference the Azure IoT device SDK, even though they don’t directly call into this API – instead, the platform projects are simply calling into the MyDriving PCL.  If you are missing a reference to the SDK from within the platform projects, you get an unintuitive exception thrown when you attempt to send a message to the IoT Hub by calling into the MyDriving PCL:
•	Not implemented in reference assembly.  at PCLCrypto.WinRTCrypto.get_MacAlgorithmProvider()
It’s unclear from this exception that to fix this, the developer must add references to each of the platform projects to the Azure IoT device SDK .

What would be most ideal, is if our tooling could be better here so that this is handled automatically for the developer.

But if this is not possible, at a minimum, we should provide a better exception and also indicate this requirement in the SDK’s nuget package information.

**Comment by tameraw** [comment] 2016-04-15 18:10
Thanks @nicolehaugen79 - Per our conversation, we'll be looking at this.

**Comment by markmnl** [comment] 2016-08-30 02:06
I have been scratching my head over this, add Microsoft.Azure.Devices.Client.PCL from Xamarin.Android app and always get the "Not implemented in reference assembly" when attempting to send. Stack trace below.

Is the problem the method is indeed not implemented?? How do I use IoT Hub from Android in that case?


  at PCLCrypto.WinRTCrypto.get_MacAlgorithmProvider () [0x00000] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.Sign (System.String requestString, System.String key) [0x00000] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.BuildSignature (System.String keyName, System.String key, System.String target, TimeSpan timeToLive) [0x0002d] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.ToSignature () [0x00018] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.IotHubConnectionString.BuildToken (System.TimeSpan& ttl) [0x00078] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.IotHubConnectionString.GetPassword () [0x0000d] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.IotHubConnectionString.GetAuthorizationHeader () [0x00000] in <filename unknown>:0 
  at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper+<ExecuteAsync>d__20.MoveNext () [0x0008a] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler+<ExecuteWithErrorHandlingAsync>d__14.MoveNext () [0x00103] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler+<SendEventAsync>d__11.MoveNext () [0x000d6] in <filename unknown>:0

**Comment by markmnl** [comment] 2016-08-30 02:25
OK I was able to fix this by as the OP says add adding the Microsoft.Azure.Devices.Client package to my Android app... super confusing :worried:

**Comment by tameraw** [comment] 2016-09-22 07:27
@nicolehaugen79 - @markmnl.
We'll look into indicating the requirements in the nuget package information as mentioned in the original post.

**Comment by anhashia** [comment] 2016-09-23 00:36
Investigating !

**Comment by markmnl** [comment] 2016-09-23 02:29
@tameraw @anhashia I don't think extra documentation will help developers looking at the error: "Not implemented in reference assembly"..

**Comment by anhashia** [comment] 2016-09-30 00:05
Looking into the issue

**Comment by anhashia** [comment] 2016-10-09 00:10
Hi @markmnl @nicolehaugen79 

I **wasn't** able to reproduce the issue (exception) described above.

Below are the steps I followed
1.) Clone the latest develop branch
2.) Go to csharp\device folder and open **iothub_csharp_deviceclient.sln** in VS 2015 IDE.
3.) Select **DeviceClientSampleAndroid** as Set as StartUp Project
4.) Go to \samples\DeviceClientSampleAndroid\MainActivity.cs and set `DeviceConnectionString` to point to **valid** device connection string
5.) Press F5 to build and run the sample on emulator.
6.) Once sample is running on the emulator. Enter the string you want to send and press "Send message to IoTHub" button. Also test receive side.

**Result Observed**:
- Both send and receive seem to work fine.

As far calling
`
var algorithm = WinRTCrypto.MacAlgorithmProvider.OpenAlgorithm(MacAlgorithm.HmacSha256);`
in Microsoft.Azure.Devices.Client\Common\Security\SharedAccessSignatureBuilder.cs
I **don't** see any exception. I see `algorithm` variable getting set to `PCLCrypto.MacAlgorithm.HmacSha256`

Below is the output log for your reference
`
10-08 19:54:45.350 D/Mono    ( 3288): Assembly Ref addref System.Net.Requests[0xb78a0010] -> System[0xb7944148]: 9
10-08 19:54:45.500 D/Mono    ( 3288): Assembly Ref addref Microsoft.Azure.Devices.Client.PCL[0xb787ef80] -> PCLCrypto[0xb7880c08]: 2
10-08 19:54:45.500 D/Mono    ( 3288): Assembly Ref addref PCLCrypto[0xb7880c08] -> mscorlib[0xb7834110]: 21
Resolved pending breakpoint at 'SharedAccessSignatureBuilder.cs:147,1' to string Microsoft.Azure.Devices.Client.SharedAccessSignatureBuilder.Sign (string requestString, string key) [0x00001].
10-08 19:54:45.650 D/Mono    ( 3288): Assembly Ref addref Microsoft.Azure.Devices.Client.PCL[0xb787ef80] -> System.Text.Encoding[0xb78a1bc0]: 2
`

If your reproduction steps are different then above steps, please send those steps for local reproduction of the issue.

**Comment by markmnl** [comment] 2016-10-09 23:35
@anhashia we both experiance the problem with the MyDriving sample not device client sample

**Comment by anhashia** [comment] 2016-10-11 01:10
Hi @markmnl @nicolehaugen79 
MyDriving assembly is referencing  `Microsoft.Azure.Devices.Client.PCL.1.0.3` which is an **old** client library version  from March timeframe. 

I did a following test
- I built MyDriving assembly from https://github.com/Azure-Samples/MyDriving project on GitHub.

I then added  MyDriving assembly (MyDriving) reference  in a  simple C# console application calling iotHub.Initialize and iotHub.SendEvent . On building the application, it  pulled 1.0.3 version of Microsoft.Azure.Devices.Client.PCL along with PCLCrypto.dll. But on running the application it threw
`Exception thrown: 'System.NotImplementedException' ` in PCLCrypto.dll

I then went though NuGet manager and installed/updated PCL library to latest available **1.0.16**.
It also added PCLCrypto in reference under References. On rebuilding the application, it was able to send the message to Azure IoT Hub successfully.
 
So issue is more of MyDriving.Dll assembly referencing (using) an older version of PCL library and those references getting pulled in as you add MyDriving assembly. If you override it with latest version of PCL then you don't see the issue.

**Comment by markmnl** [comment] 2016-10-11 02:53
If the problem is there is an issue with old versions of PCL (not that old - this year even) then perhaps we should make it clear is an issue with old PCLs? I didn't come across anything about PCL version being the issue when I encountered the issue. I think it is quite reasonable to expect others will not be using the latest PCL versions..

**Comment by markmnl** [comment] 2016-10-11 02:54
By the way how come this labelled as CSS?!

**Comment by anhashia** [comment] 2016-10-11 03:36
Hi @markmnl 
Issue is not per se in older version PCL version 1.0.3. You can consume it directly in an application using a NuGet package manager. NuGet will also install PCLCrypto (separate dependent package) and you should be good to go.  I tested it in C# console application.
There is also no issue with **DeviceClientSampleAndroid** (which is part of Azure IoT SDK sample) that also uses PCL library.

Issue seems to be specific to  MyDriving.Dll assembly which is from a separate GitHub project. It is not part of Azure IoT SDK.  It references older PCL library and these seems to be some issue around using PCLCrypto. You can try to build MyDriving.Dll  against latest PCL library and see if resolves your issue.

https://www.nuget.org/packages/Microsoft.Azure.Devices.Client.PCL has link to versions and dependencies of PCL.  NuGet update manager in VS2015 will prompt you for new available updates (if updates are available for package).

If you find any issue with directly consuming PCL library using NuGet manager, let me know.

**Comment by anhashia** [comment] 2016-10-25 22:08
Closing this. Please re-activate if you have any further questions on this. Thanks !

**Closed by anhashia** 2016-10-25 22:08 UTC
Labels: CSS, enhancement
