### ISSUE TITLE
Java SDK samples throwing "Not authorized to connect" for MQTT

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-iot-sdks#409] opened 2016-03-22 19:34 UTC
I am experiencing an issue with the Java SDK samples when trying to use MQTT on both Ubuntu and Raspbian. I've double-checked my connection string created using the iothub-explorer tool, but the samples throw the following exception. Am I missing something simple? The Node.js samples worked for me out-of-the-box. Any guidance is greatly appreciated.

Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
Successfully created an IoT Hub client.
Exception in thread "main" java.io.IOException: Error initializing MQTT connection:Not authorized to connect
	at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:146)
	at com.microsoft.azure.iothub.transport.mqtt.MqttTransport.open(MqttTransport.java:87)
	at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:162)
	at samples.com.microsoft.azure.iothub.SendEvent.main(SendEvent.java:109)

**Comment by jim-mclean** [comment] 2016-03-23 12:53
I'm having the same issue.  Trying to dig into what the root cause is on this.

**Comment by bcraun** [comment] 2016-03-23 16:45
I understand this is a reproducible issue with the samples. Until they are updated, the approach described in this article has been confirmed to work.

[Get started with Azure IoT Hub for Java](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-java-java-getstarted/)

**Comment by zolvarga** [comment] 2016-03-25 20:26
Hi,

We were able to repro the issue. We are looking at it.

Thanks,
Zoltan

**Comment by jim-mclean** [comment] 2016-03-25 20:55
I don't have a code fix handy, but if but the issues seems to be with the SAS Token generation.  If I hard code in a token I am able to connect.

**Comment by iluican** [comment] 2016-03-25 21:38
Hi,

This is fixed in our develop branch. It will be merged into master sometime today. Thank you again for using our SDKs.

Ilie.

**Closed by iluican** 2016-03-25 21:38 UTC
Labels: help wanted
