### ISSUE TITLE
Long polling issue bug

### ISSUE THREAD

**Issue by asebak** [Azure/azure-iot-sdks#392] opened 2016-03-13 20:35 UTC
I am not 100% sure if this is a bug, but I am getting the error for this code:
I am on UWP Platform.
In the file located here:

https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/HttpDeviceClient.cs

You use the default value for receive timeout as   0     
` static readonly TimeSpan DefaultReceiveTimeoutInSeconds = TimeSpan.FromSeconds(0);`

But in the OnReceiveAsync method you do the following:
```

           // Long-polling is not supported 
if (!TimeSpan.Zero.Equals(timeout)) 
{ 
                throw new ArgumentOutOfRangeException("timeout", "Http Protocol does not support a non-zero receive timeout"); 
            } 
```
This OnReceiveAsync uses the value of timeout = DefaultReceiveTimeoutInSeconds
This is creating a bug in my Windows_UWP Application.  Any workarounds for fixing this?

**Comment by asebak** [comment] 2016-03-13 23:30
Just figured it out, this is a bug on your end

deviceClient.ReceiveAsync()  => works fine

deviceClient.ReceiveAsync(TimeSpan.FromSeconds(30)) => this crashes and says the timespan is 0 with the argument out of range expcetion.

**Comment by tameraw** [comment] 2016-03-15 18:04
@asebak - Thanks for reporting this issue. We're looking at it.

**Comment by iluican** [comment] 2016-03-22 03:10
Hello,

Thank you for using our SDK. I did investigate this issue, and it doesn't seem to be a bug, but expected behavior. HTTP is the only protocol we support for the UWP platform, and for HTTP we do not support non-zero timeouts. That is why the exception is being thrown. If you were to target full .NET framework, you would be able to use one of the other two protocols, AMQP or MQTT, which do support non-zero timeouts as well.

Since you mentioned ReceiveAsync() works fine, do you have an issue using that?

Thank you,
Ilie.

**Comment by iluican** [comment] 2016-03-28 06:10
I will now close this. Please feel free to reopen it if you still have issues.

Thank you,
Ilie.

**Closed by iluican** 2016-03-28 06:10 UTC
Labels: bug
