### ISSUE TITLE
Intel Edison - Execute ./build.sh and make -f linux Error

### ISSUE THREAD

**Issue by cnvery** [Azure/azure-iot-sdks#353] opened 2016-02-28 17:07 UTC
First, I have one issue after executed _./build.sh_ at _/azure-iot-sdks/c/build_all/linux_.

It shows error as per below:

> **root@edison:~/azure-iot-sdks/c/build_all/linux# ./build.sh --no-mqtt**
> -sh: ./build.sh: not found

> **root@edison:~/azure-iot-sdks/c/build_all/linux# ls**
> build.sh                
> print_failed_tests.sed  
> setup.sh                
> setup_opensuse.sh

However, _./build.sh_ is appeared after I type _ls_ command to check files in current directory

The latest Azure IoT SDK in C (Updated 29 days ago) no longer have _build_proton.sh_, which can be seen in https://github.com/Azure/azure-iot-sdks/tree/develop/c/build_all/linux. I wonder the _build_proton.sh_ have effect, which eventually lead to this error?

Second, I faced another issue after executed _make -f linux_ at _/azure-iot-sdks/c/iothub_client/samples/iothub_client_sample_amqp/linux_ directory

It shows error as per below:

> **root@edison:~/azure-iot-sdks/c/iothub_client/samples/iothub_client_sample_amqp/linux# make -f linux**
> make: linux: No such file or directory
> make: *** No rule to make target 'linux'.  Stop.

I followed the instructions exactly same as https://software.intel.com/en-us/articles/intel-edison-board-microsoft-azure-iot-suite-setup and https://github.com/Azure/azure-iot-sdks/blob/26e81a7a3358815bfee9553678f546ffe6f3d3ce/c/doc/run_sample_on_intel_edison.md.

Hope someone can solve my doubts.

Thank you.

**Comment by jebrando** [comment] 2016-02-29 21:33
It sounds like your build.sh file has lost it's execute permission.  You can do one of a few things, but the easiest would be to do a chmod on the file and see if that should work.

**Comment by cnvery** [comment] 2016-03-01 02:55
I have added the permission by _chmod +x build.sh_.

But, the results is same.

**root@edison:~/azure-iot-sdks/c/build_all/linux# chmod +x build.sh
root@edison:~/azure-iot-sdks/c/build_all/linux# ./build.sh**
-sh: ./build.sh: not found

**Comment by cnvery** [comment] 2016-03-08 10:33
Bump

**Comment by cnvery** [comment] 2016-03-09 09:39
I executed the latest commands based on https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md

Then, finally Intel Edison can execute ./build.sh file.

However, it poped up follwoing errors:

`root@edison:~/azure-iot-sdks/c/build_all/linux# ./build.sh --no-mqtt --no-amqp --no-http
~/cmake ~/azure-iot-sdks/c/build_all/linux
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/share/cmake-3.4/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/bin/c++" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /home/root/cmake/CMakeFiles/CMakeTmp



  Run Build Command:"/usr/bin/make" "cmTC_5d8ca/fast"

  /usr/bin/make -f CMakeFiles/cmTC_5d8ca.dir/build.make
  CMakeFiles/cmTC_5d8ca.dir/build

  make[1]: Entering directory '/home/root/cmake/CMakeFiles/CMakeTmp'

  Building CXX object CMakeFiles/cmTC_5d8ca.dir/testCXXCompiler.cxx.o

  /usr/bin/c++ -o CMakeFiles/cmTC_5d8ca.dir/testCXXCompiler.cxx.o -c
  /home/root/cmake/CMakeFiles/CMakeTmp/testCXXCompiler.cxx

  Linking CXX executable cmTC_5d8ca

  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5d8ca.dir/link.txt
  --verbose=1

  /usr/bin/c++ -L/lib/ CMakeFiles/cmTC_5d8ca.dir/testCXXCompiler.cxx.o -o
  cmTC_5d8ca -rdynamic

  /usr/lib/gcc/i586-poky-linux/4.8.2/../../../../i586-poky-linux/bin/ld:
  cannot find -lstdc++

  collect2: error: ld returned 1 exit status

  CMakeFiles/cmTC_5d8ca.dir/build.make:97: recipe for target 'cmTC_5d8ca'
  failed

  make[1]: *** [cmTC_5d8ca] Error 1

  make[1]: Leaving directory '/home/root/cmake/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_5d8ca/fast' failed

  make: *** [cmTC_5d8ca/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)


-- Configuring incomplete, errors occurred!
See also "/home/root/cmake/CMakeFiles/CMakeOutput.log".
See also "/home/root/cmake/CMakeFiles/CMakeError.log".`

Due to error above, I cannot execute
`./iothub_client_sample_amqp`

Any solution for this?

**Comment by cnvery** [comment] 2016-03-29 08:16
Any update on this?

**Comment by zolvarga** [comment] 2016-03-29 23:17
Hi cnvery,

We found the problem and testing the workaround. We will get back to you as soon as we finalized the necessary steps.

Thanks,
Zoltan

**Comment by zolvarga** [comment] 2016-03-30 16:24
Hi cnvery,

Here is the root cause of this issue: Intel Edison has older Git version installed which doesn't support submodules. Our C SDK uses submodules for each protocol implementation and because of those submodules were not exist the build script failed.

The best option in this case to cross compile our SDK for Edison platform. Follow the instruction from here:
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md

I am closing this issue. Please open a new one if you hit new issues with the cross compilation.

Thanks,
Zoltan

**Closed by zolvarga** 2016-03-30 16:24 UTC
Labels: help wanted
