### ISSUE TITLE
c Azure-iot-sdks fail to build out of github. (Target board is Raspberry Pi). Please help

### ISSUE THREAD

**Issue by kbhatti800** [Azure/azure-iot-sdks#758] opened 2016-08-07 18:08 UTC
Linking C executable iothub_client_sample_http_shared
[ 94%] Built target remote_monitoring
[ 94%] Built target iothub_client_sample_http
Scanning dependencies of target iothub_client_sample_upload_to_blob
Scanning dependencies of target iothub_client_sample_x509
../../../iothub_client/libiothub_client_amqp_transport.a(iothub_client_ll.c.o):(.data+0x14): multiple definition of `IOTHUB_CLIENT_CONFIRMATION_RESULTStringStorage'
CMakeFiles/simplesample_amqp.dir/simplesample_amqp.c.o:(.data+0xf4): first defined here
../../../iothub_client/libiothub_client_amqp_transport.a(iothub_client_ll.c.o): In function `IOTHUB_CLIENT_CONFIRMATION_RESULTStrings':
iothub_client_ll.c:(.text+0xe8): multiple definition of `IOTHUB_CLIENT_CONFIRMATION_RESULTStrings'
CMakeFiles/simplesample_amqp.dir/simplesample_amqp.c.o:simplesample_amqp.c:(.text+0x11e0): first defined here
../../../iothub_client/libiothub_client_amqp_transport.a(iothub_client_ll.c.o): In function `IOTHUB_CLIENT_CONFIRMATION_RESULT_FromString':
iothub_client_ll.c:(.text+0x12c): multiple definition of `IOTHUB_CLIENT_CONFIRMATION_RESULT_FromString'
CMakeFiles/simplesample_amqp.dir/simplesample_amqp.c.o:simplesample_amqp.c:(.text+0x1224): first defined here
collect2: error: ld returned 1 exit status
serializer/samples/simplesample_amqp/CMakeFiles/simplesample_amqp.dir/build.make:116: recipe for target 'serializer/samples/simplesample_amqp/simplesample_amqp' failed
make[2]: *** [serializer/samples/simplesample_amqp/simplesample_amqp] Error 1
CMakeFiles/Makefile2:1993: recipe for target 'serializer/samples/simplesample_amqp/CMakeFiles/simplesample_amqp.dir/all' failed
make[1]: *** [serializer/samples/simplesample_amqp/CMakeFiles/simplesample_amqp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] [ 96%] [ 97%] Building C object iothub_client/samples/iothub_client_sample_upload_to_blob/CMakeFiles/iothub_client_sample_upload_to_blob.dir/linux/main.c.o
Building C object iothub_client/samples/iothub_client_sample_upload_to_blob/CMakeFiles/iothub_client_sample_upload_to_blob.dir/iothub_client_sample_upload_to_blob.c.o
Building C object iothub_client/samples/iothub_client_sample_x509/CMakeFiles/iothub_client_sample_x509.dir/iothub_client_sample_x509.c.o
[ 97%] Built target iothub_client_sample_http_shared
Linking C executable iothub_client_sample_upload_to_blob
Linking C executable iothub_client_sample_x509
[ 97%] Built target iothub_client_sample_upload_to_blob
[ 97%] Built target iothub_client_sample_x509
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chrit-msft** [comment] 2016-08-09 16:17
@kbhatti800 Thank you for raising this issue.  I can't tell from the output but are you using Raspbian and is this a pi2 or 3?

**Comment by kbhatti800** [comment] 2016-08-09 18:51
pi3 B

**Comment by chrit-msft** [comment] 2016-08-12 16:09
@kbhatti800 I wanted to give you an update that I have been unable to reproduce your issue.  I have installed a clean raspbian build on my pi3.  Installed the sdks using:
git clone https://github.com/azure/azure-iot-sdks --recursive. 

I then ran setup.sh to prepare the c build environment.  After that I ran build.sh and hit a known issue that doesn't have the same failure signature as yours.  To get around this known issue, I modified build.sh to use only 1 core which limits the numbers of jobs created.  This modification allowed me to successfully build the c SDK.  Can you provide any more data on what your environment is that might help me reproduce this issue?

**Comment by chrit-msft** [comment] 2016-08-22 20:16
@kbhatti800 Due to lack of repro I am going to close this thread.  If you continue to see this problem please re-open the thread and reach out immediately.

**Closed by chrit-msft** 2016-08-22 20:16 UTC
Labels: CSS, investigation-required
